### ISSUE TITLE
camera.times > camera.dlc

### ISSUE THREAD

**Issue by mschart** [int-brain-lab/iblenv#103]
For session eid = '862ade13-53cd-4221-a3fa-dda8643641f2' and camera 'left',  there are 446026 time stamps but only 416769 dlc entires. I.e. about 8 min worth more time stamps than dlc entries. This doesn't matter in this case as the last trial was already done 28 min before that. (That's quite some idle period.)

I don't know if the camera.times must match camera.dlc in length. If not, ignore this issue.

**Comment by k1o0** [comment]
They should but don't currently.  I assume the dlc timestamps match the number of frames of the video.  If so then the new camera extractor will fix this by ensuring the camera timestamps match the number of frames.

**Comment by GaelleChapuis** [comment]
Seems related to #76
