### ISSUE TITLE
len(wheel['timestamps']) >> len(wheel['position']) for some eids

### ISSUE THREAD

**Issue by mschart** [int-brain-lab/iblenv#109]
Hello,
For this session there are nearly (but not exactly) double the number of wheel timestamps than wheel position entries:

eid = 'aad23144-0e52-4eac-80c5-c4ee2decb198'
cortexlab/Subjects/KS023/2019-12-10/001
wheel = alf.io.load_object(alf_path, 'wheel', namespace = 'ibl')
print(len(wheel['timestamps']), len(wheel['position']))
649426 324744

Also for these here is a mismatch of wheel times and positions:

614e1937-4b24-4ad3-9055-c8253d089919  
a4000c2f-fa75-4b3e-8f06-a7cf599b87ad
a3df91c8-52a6-4afa-957b-3479a7d0897c

**Comment by k1o0** [comment]
I've patched 21 sessions with this problem, including the ones you listed here.  There were 10 sessions that I couldn't re-extract so I just left them as is.
