### ISSUE TITLE
mac/linux difference for one.list command

### ISSUE THREAD

**Issue by mschart** [int-brain-lab/iblenv#110]
Hello,
On Ubuntu one.list(eid) gives a list of dataset type names, each a string. On map that's a list of posix paths to these datasets. Is that intentional? Am I missing something? 

Ubuntu:
![ubuntu](https://user-images.githubusercontent.com/17218515/99442633-93747d80-2911-11eb-9c98-18143c27fb45.png)

Mac:
<img width="567" alt="mac" src="https://user-images.githubusercontent.com/17218515/99442648-98393180-2911-11eb-8b4f-c9e4c7075aa2.png">

**Comment by oliche** [comment]
It's a version thing.
We are moving away from dataset-type identification to full collection + name for each dataset.

This is completely unrelated to OS: your Mac is up to date while your Linux is outdated, `git pull` !
