### ISSUE TITLE
The current Numpy installation fails to pass a sanity check due to a bug in the windows runtime.

### ISSUE THREAD

**Issue by julius-benson** [int-brain-lab/iblenv#111]
A Windows update was applied to our ephys and video pcs last night (2020-11-18), I pulled the latest version of the code this morning, and now I'm getting this error when I try to transfer the ephys:

> (iblenv) C:\iblscripts\deploy\ephyspc>python transfer_ephys_session.py
>  ** On entry to DGEBAL parameter number  3 had an illegal value
>  ** On entry to DGEHRD  parameter number  2 had an illegal value
>  ** On entry to DORGHR DORGQR parameter number  2 had an illegal value
>  ** On entry to DHSEQR parameter number  4 had an illegal value
> Traceback (most recent call last):
>   File "transfer_ephys_session.py", line 7, in <module>
>     from ibllib.pipes.misc import confirm_ephys_remote_folder, get_iblscripts_folder
>   File "C:\Users\IBL Video\.conda\envs\iblenv\lib\site-packages\ibllib\__init__.py", line 1, in <module>
>     from ibllib.misc import logger_config
>   File "C:\Users\IBL Video\.conda\envs\iblenv\lib\site-packages\ibllib\misc\__init__.py", line 1, in <module>
>     from .misc import (pprint, structarr, logger_config, print_progress)
>   File "C:\Users\IBL Video\.conda\envs\iblenv\lib\site-packages\ibllib\misc\misc.py", line 5, in <module>
>     import numpy as np
>   File "C:\Users\IBL Video\.conda\envs\iblenv\lib\site-packages\numpy\__init__.py", line 305, in <module>
>     _win_os_check()
>   File "C:\Users\IBL Video\.conda\envs\iblenv\lib\site-packages\numpy\__init__.py", line 302, in _win_os_check
>     raise RuntimeError(msg.format(__file__)) from None
> RuntimeError: The current Numpy installation ('C:\\Users\\IBL Video\\.conda\\envs\\iblenv\\lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86

**Comment by nbonacchi** [comment]
After activating the environment try again after typing:
`pip install numpy==1.19.3`

**Comment by n-lavrenko** [comment]
> After activating the environment try again after typing:
> `pip install numpy==1.19.3`

Thank! That's helped me.

**Comment by rapkshn47** [comment]
> After activating the environment try again after typing:
> `pip install numpy==1.19.3`

that did'nt work for me... can you a suggest a different method

**Comment by EvenGal** [comment]
Thanks!

**Comment by Sanblacky** [comment]
I am having the same issue.
I 

> After activating the environment try again after typing:
> `pip install numpy==1.19.3`

It didn't work for me. 
It's saying ERROR : Could not find a version that satisfies the requirement numpy ==1.19.3(from versions :none)

**Comment by Adityagurati** [comment]
> I am having the same issue.
> I
> 
> > After activating the environment try again after typing:
> > `pip install numpy==1.19.3`
> 
> It didn't work for me.
> It's saying ERROR : Could not find a version that satisfies the requirement numpy ==1.19.3(from versions :none)

u can dounload it as a wheel from unofficial python  binaries site

**Comment by Adityagurati** [comment]
> After activating the environment try again after typing:
> `pip install numpy==1.19.3`

that really worked man thx a lot

**Comment by SVijayB** [comment]
Try, 
`pip uninstall numpy`
and then
`pip install numpy==1.19.3`. Should work.

**Comment by errorsolve** [comment]
Here Is All Possible Solution added [**runtimeError: package fails to pass a sanity check for numpy and pandas in python**](https://exerror.com/runtimeerror-package-fails-to-pass-a-sanity-check-for-numpy-and-pandas/)

**Comment by adifdwimaulana** [comment]
> After activating the environment try again after typing:
> `pip install numpy==1.19.3`

That's worked. Thanks man!

**Comment by tomuch94** [comment]
gracias
     After activating the environment try again after typing:
     pip install numpy==1.19.3

**Comment by Anonymousdevilx** [comment]
I 

> After activating the environment try again after typing:
> `pip install numpy==1.19.3`

I am so glad that it worked!!! Thanks man!!!! I am now relaxed❤️❤️❤️

**Comment by LWeatherbie** [comment]
Installing 1.19.3 worked here too, thanks!

**Comment by Petra-hub** [comment]
I recently encountered this problem and found it only happens in my base environment. I have a second environment I'm running, both have the same version of Numpy, but I have the newer versions of most other applications in my secondary environment, so there could be any number of dependencies.

**Here's my base env conda list:**
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py38_0
absl-py                   0.11.0                   pypi_0    pypi
alabaster                 0.7.12                     py_0
anaconda-client           1.7.2                    py38_0
anaconda-navigator        1.9.12                   py38_0
anaconda-project          0.8.4                      py_0
argh                      0.26.2                   py38_0
asn1crypto                1.3.0                    py38_0
astroid                   2.4.2                    py38_0
astunparse                1.6.3                    pypi_0    pypi
atomicwrites              1.4.0                      py_0
attrs                     19.3.0                     py_0
autopep8                  1.5.3                      py_0
babel                     2.8.0                      py_0
backcall                  0.2.0                      py_0
backports                 1.0                        py_2
backports.functools_lru_cache 1.6.1              pyhd3eb1b0_0
backports.shutil_get_terminal_size 1.0.0                    py38_2
backports.tempfile        1.0                        py_1
backports.weakref         1.0.post1                  py_1
bcrypt                    3.1.7            py38he774522_1
beautifulsoup4            4.9.1                    py38_0
bitarray                  1.4.0            py38he774522_0
blas                      1.0                         mkl
bleach                    3.1.5                      py_0
blosc                     1.19.0               h7bd577a_0
boto                      2.49.0                   py38_0
brotlipy                  0.7.0           py38he774522_1000
bzip2                     1.0.8                he774522_0
ca-certificates           2020.12.8            haa95532_0
cachetools                4.2.0                    pypi_0    pypi
certifi                   2020.12.5        py38haa95532_0
cffi                      1.14.0           py38h7a1dbc1_0
chardet                   3.0.4                 py38_1003
click                     7.1.2                      py_0
cloudpickle               1.5.0                      py_0
clyent                    1.2.2                    py38_1
colorama                  0.4.3                      py_0
comtypes                  1.1.7                 py38_1001
conda                     4.9.2            py38haa95532_0
conda-build               3.18.11                  py38_1
conda-env                 2.6.0                         1
conda-package-handling    1.7.2            py38h76e460a_0
conda-verify              3.4.2                      py_1
console_shortcut          0.1.1                         4
contextlib2               0.6.0.post1                py_0
cryptography              2.9.2            py38h7a1dbc1_0
curl                      7.71.1               h2a8f88b_1
cycler                    0.10.0                   py38_0
cython                    0.29.21          py38ha925a31_0
cytoolz                   0.10.1           py38he774522_0
dask-core                 2.20.0                     py_0
decorator                 4.4.2                      py_0
defusedxml                0.6.0                      py_0
diff-match-patch          20200713                   py_0
dill                      0.3.2                    pypi_0    pypi
distributed               2.20.0                   py38_0
dlx                       1.0.4                    pypi_0    pypi
docplex                   2.15.194                 pypi_0    pypi
docutils                  0.16                     py38_1
entrypoints               0.3                      py38_0
et_xmlfile                1.0.1                   py_1001
fastcache                 1.1.0            py38he774522_0
fastdtw                   0.3.4                    pypi_0    pypi
fastjsonschema            2.14.5                   pypi_0    pypi
filelock                  3.0.12                     py_0
flake8                    3.8.3                      py_0
flask                     1.1.2                      py_0
flatbuffers               1.12                     pypi_0    pypi
freetype                  2.10.4               hd328e21_0
fsspec                    0.7.4                      py_0
future                    0.18.2                   py38_1
gast                      0.3.3                    pypi_0    pypi
get_terminal_size         1.0.0                h38e98db_0
gevent                    20.6.2           py38he774522_0
glob2                     0.7                        py_0
gmpy2                     2.0.8            py38h7edee0f_3
google-auth               1.24.0                   pypi_0    pypi
google-auth-oauthlib      0.4.2                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
greenlet                  0.4.16           py38he774522_0
grpcio                    1.32.0                   pypi_0    pypi
hdf5                      1.10.4               h7ebc959_0
heapdict                  1.0.1                      py_0
html5lib                  1.1                        py_0
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha925a31_3
idna                      2.10                       py_0
imagesize                 1.2.0                      py_0
importlib-metadata        1.7.0                    py38_0
importlib_metadata        1.7.0                         0
inflection                0.5.1                    pypi_0    pypi
intel-openmp              2020.2                      254
intervaltree              3.0.2                      py_1
ipykernel                 5.3.2            py38h5ca1d4c_0
ipython                   7.16.1           py38h5ca1d4c_0
ipython_genutils          0.2.0                    py38_0
ipywidgets                7.5.1                      py_0
isort                     4.3.21                   py38_0
itsdangerous              1.1.0                      py_0
jdcal                     1.4.1                      py_0
jedi                      0.17.1                   py38_0
jinja2                    2.11.2                     py_0
joblib                    0.16.0                     py_0
jpeg                      9b                   hb83a4c4_2
json5                     0.9.5                      py_0
jsonschema                3.2.0                    py38_0
jupyter                   1.0.0                    py38_7
jupyter_client            6.1.6                      py_0
jupyter_console           6.1.0                      py_0
jupyter_core              4.6.3                    py38_0
jupyterlab                2.1.5                      py_0
jupyterlab_server         1.2.0                      py_0
keras-preprocessing       1.1.2                    pypi_0    pypi
keyring                   21.2.1                   py38_0
kiwisolver                1.2.0            py38h74a9793_0
krb5                      1.18.2               hc04afaa_0
lazy-object-proxy         1.4.3            py38he774522_0
libarchive                3.4.2                h5e25573_0
libcurl                   7.71.1               h2a8f88b_1
libiconv                  1.15                 h1df5818_7
liblief                   0.10.1               ha925a31_0
libllvm9                  9.0.1                h21ff451_0
libpng                    1.6.37               h2a8f88b_0
libsodium                 1.0.18               h62dcd97_0
libspatialindex           1.9.3                h33f27b4_0
libssh2                   1.9.0                h7a1dbc1_1
libtiff                   4.1.0                h56a325e_1
libxml2                   2.9.10               hb89e7f3_3
libxslt                   1.1.34               he774522_0
llvmlite                  0.33.0           py38ha925a31_0
locket                    0.2.0                    py38_1
lxml                      4.5.2            py38h1350720_0
lz4-c                     1.9.2                hf4a77e7_3
lzo                       2.10                 he774522_2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markdown                  3.3.3                    pypi_0    pypi
markupsafe                1.1.1            py38he774522_0
mccabe                    0.6.1                    py38_1
menuinst                  1.4.16           py38he774522_1
mistune                   0.8.4           py38he774522_1000
mkl                       2020.2                      256
mkl-service               2.3.0            py38hb782905_0
mkl_fft                   1.2.0            py38h45dec08_0
mkl_random                1.1.1            py38h47e9c7a_0
mock                      4.0.2                      py_0
more-itertools            8.4.0                      py_0
mpc                       1.1.0                h7edee0f_1
mpfr                      4.0.2                h62dcd97_1
mpir                      3.0.0                hec2e145_1
mpmath                    1.1.0                    py38_0
msgpack-python            1.0.0            py38h74a9793_1
msys2-conda-epoch         20160418                      1
multipledispatch          0.6.0                    py38_0
multitasking              0.0.9                    pypi_0    pypi
navigator-updater         0.2.1                    py38_0
nb_conda_kernels          2.3.1            py38haa95532_0
nbconvert                 5.6.1                    py38_0
nbformat                  5.0.7                      py_0
nest-asyncio              1.4.1                    pypi_0    pypi
networkx                  2.4                        py_1
nltk                      3.5                        py_0
nose                      1.3.7                    py38_2
notebook                  6.0.3                    py38_0
ntlm-auth                 1.5.0                    pypi_0    pypi
numpy                     1.19.2           py38hadc3359_0
numpy-base                1.19.2           py38ha3acd2a_0
numpydoc                  1.1.0                      py_0
oauthlib                  3.1.0                    pypi_0    pypi
olefile                   0.46                       py_0
openpyxl                  3.0.4                      py_0
openssl                   1.1.1i               h2bbff1b_0
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 20.4                       py_0
pandoc                    2.11                 h9490d1a_0
pandocfilters             1.4.2                    py38_1
paramiko                  2.7.1                      py_0
parso                     0.7.0                      py_0
partd                     1.1.0                      py_0
path                      13.1.0                   py38_0
path.py                   12.4.0                        0
pathlib2                  2.3.5                    py38_0
pathtools                 0.1.2                      py_1
pep8                      1.7.1                    py38_0
pexpect                   4.8.0                    py38_0
pickleshare               0.7.5                 py38_1000
pillow                    7.2.0            py38hcc1f983_0
pip                       20.1.1                   py38_1
pkginfo                   1.5.0.1                  py38_0
pluggy                    0.13.1                   py38_0
ply                       3.11                     py38_0
powershell_shortcut       0.0.1                         3
prometheus_client         0.8.0                      py_0
prompt-toolkit            3.0.5                      py_0
prompt_toolkit            3.0.5                         0
protobuf                  3.14.0                   pypi_0    pypi
psutil                    5.7.0            py38he774522_0
py                        1.9.0                      py_0
py-lief                   0.10.1           py38ha925a31_0
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pybind11                  2.5.0                    pypi_0    pypi
pycodestyle               2.6.0                      py_0
pycosat                   0.6.3            py38he774522_0
pycparser                 2.20                       py_2
pycurl                    7.43.0.5         py38h7a1dbc1_0
pydocstyle                5.0.2                      py_0
pyflakes                  2.2.0                      py_0
pygments                  2.6.1                      py_0
pylatexenc                2.7                      pypi_0    pypi
pylint                    2.5.3                    py38_0
pynacl                    1.4.0            py38h62dcd97_1
pyodbc                    4.0.30           py38ha925a31_0
pyopenssl                 19.1.0                     py_1
pyparsing                 2.4.7                      py_0
pyqt                      5.9.2            py38ha925a31_4
pyreadline                2.1                      py38_1
pyrsistent                0.16.0           py38he774522_0
pysocks                   1.7.1                    py38_0
pytest                    5.4.3                    py38_0
python                    3.8.3                he1778fa_2
python-constraint         1.4.0                    pypi_0    pypi
python-dateutil           2.8.1                      py_0
python-jsonrpc-server     0.3.4                      py_1
python-language-server    0.34.1                   py38_0
python-libarchive-c       2.9                        py_0
pytz                      2020.1                     py_0
pywin32                   227              py38he774522_1
pywin32-ctypes            0.2.0                 py38_1000
pywinpty                  0.5.7                    py38_0
pyyaml                    5.3.1            py38he774522_1
pyzmq                     19.0.1           py38ha925a31_1
qdarkstyle                2.8.1                      py_0
qiskit                    0.22.0                   pypi_0    pypi
qiskit-aer                0.6.1                    pypi_0    pypi
qiskit-aqua               0.7.5                    pypi_0    pypi
qiskit-ibmq-provider      0.10.0                   pypi_0    pypi
qiskit-ignis              0.4.0                    pypi_0    pypi
qiskit-terra              0.15.2                   pypi_0    pypi
qt                        5.9.7            vc14h73c81de_0
qtawesome                 0.7.2                      py_0
qtconsole                 4.7.5                      py_0
qtpy                      1.9.0                      py_0
quandl                    3.5.2                    pypi_0    pypi
regex                     2020.6.8         py38he774522_0
requests                  2.24.0                     py_0
requests-ntlm             1.1.0                    pypi_0    pypi
requests-oauthlib         1.3.0                    pypi_0    pypi
retworkx                  0.5.0                    pypi_0    pypi
rope                      0.17.0                     py_0
rsa                       4.6                      pypi_0    pypi
rtree                     0.9.4            py38h21ff451_1
ruamel_yaml               0.15.87          py38he774522_1
send2trash                1.5.0                    py38_0
setuptools                49.2.0                   py38_0
simplegeneric             0.8.1                    py38_2
singledispatch            3.4.0.3                  py38_0
sip                       4.19.13          py38ha925a31_0
six                       1.15.0                     py_0
snappy                    1.1.8                h33f27b4_0
snowballstemmer           2.0.0                      py_0
sortedcollections         1.2.1                      py_0
sortedcontainers          2.2.2                      py_0
soupsieve                 2.0.1                      py_0
sphinx                    3.1.2                      py_0
sphinxcontrib             1.0                      py38_1
sphinxcontrib-applehelp   1.0.2                      py_0
sphinxcontrib-devhelp     1.0.2                      py_0
sphinxcontrib-htmlhelp    1.0.3                      py_0
sphinxcontrib-jsmath      1.0.1                      py_0
sphinxcontrib-qthelp      1.0.3                      py_0
sphinxcontrib-serializinghtml 1.1.4                      py_0
sphinxcontrib-websupport  1.2.3                      py_0
spyder                    4.1.4                    py38_0
spyder-kernels            1.9.2                    py38_0
sqlalchemy                1.3.18           py38he774522_0
sqlite                    3.33.0               h2a8f88b_0
sympy                     1.6.1                    py38_0
tbb                       2020.0               h74a9793_0
tblib                     1.6.0                      py_0
tensorboard               2.4.0                    pypi_0    pypi
tensorboard-plugin-wit    1.7.0                    pypi_0    pypi
tensorflow                2.4.0                    pypi_0    pypi
tensorflow-estimator      2.4.0                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.8.3                    py38_0
testpath                  0.4.4                      py_0
threadpoolctl             2.1.0              pyh5ca1d4c_0
tk                        8.6.10               he774522_0
toml                      0.10.1                     py_0
toolz                     0.10.0                     py_0
tornado                   6.0.3                    pypi_0    pypi
tqdm                      4.47.0                     py_0
traitlets                 4.3.3                    py38_0
typing_extensions         3.7.4.2                    py_0
ujson                     1.35             py38he774522_0
unicodecsv                0.14.1                   py38_0
urllib3                   1.25.9                     py_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
watchdog                  0.10.3                   py38_0
wcwidth                   0.2.5                      py_0
webencodings              0.5.1                    py38_1
websockets                8.1                      pypi_0    pypi
werkzeug                  1.0.1                      py_0
wheel                     0.36.2                   pypi_0    pypi
widgetsnbextension        3.5.1                    py38_0
win_inet_pton             1.1.0                    py38_0
win_unicode_console       0.5                      py38_0
wincertstore              0.2                      py38_0
winpty                    0.4.3                         4
wrapt                     1.12.1                   pypi_0    pypi
xlrd                      1.2.0                      py_0
xlsxwriter                1.2.9                      py_0
xlwings                   0.19.5                   py38_0
xlwt                      1.3.0                    py38_0
xmltodict                 0.12.0                     py_0
xz                        5.2.5                h62dcd97_0
yaml                      0.2.5                he774522_0
yapf                      0.30.0                     py_0
yfinance                  0.1.55                   pypi_0    pypi
zeromq                    4.3.2                ha925a31_3
zict                      2.0.0                      py_0
zipp                      3.1.0                      py_0
zlib                      1.2.11               h62dcd97_4
zope                      1.0                      py38_1
zope.event                4.4                      py38_0
zope.interface            4.7.1            py38he774522_0
zstd                      1.4.5                h04227a9_0

**Here's my secondary env conda list:**
# Name                    Version                   Build  Channel
_tflow_select             2.3.0                     eigen
absl-py                   0.10.0                   pypi_0    pypi
aiohttp                   3.7.3            py38h2bbff1b_1
argon2-cffi               20.1.0                   pypi_0    pypi
astunparse                1.6.3                      py_0
async-generator           1.10                     pypi_0    pypi
async-timeout             3.0.1                    py38_0
attrs                     20.3.0             pyhd3eb1b0_0
backcall                  0.2.0                      py_0
blas                      1.0                         mkl
bleach                    3.2.1                    pypi_0    pypi
blinker                   1.4                      py38_0
brotlipy                  0.7.0           py38h2bbff1b_1003
ca-certificates           2020.12.8            haa95532_0
cachetools                4.1.1                      py_0
certifi                   2020.12.5        py38haa95532_0
cffi                      1.14.4           py38hcd4344a_0
chardet                   3.0.4           py38haa95532_1003
click                     7.1.2                      py_0
colorama                  0.4.4              pyhd3eb1b0_0
cryptography              3.2.1            py38hcd4344a_1
cycler                    0.10.0                   pypi_0    pypi
decorator                 4.4.2                      py_0
defusedxml                0.6.0                    pypi_0    pypi
dill                      0.3.3                    pypi_0    pypi
entrypoints               0.3                      pypi_0    pypi
flatbuffers               1.12                     pypi_0    pypi
future                    0.18.2                   pypi_0    pypi
gast                      0.3.3                    pypi_0    pypi
google-auth               1.23.0             pyhd3eb1b0_0
google-auth-oauthlib      0.4.2              pyhd3eb1b0_2
google-pasta              0.2.0                      py_0
googleapis-common-protos  1.52.0                   pypi_0    pypi
grpcio                    1.32.0                   pypi_0    pypi
h5py                      2.10.0           py38h5e291fa_0
hdf5                      1.10.4               h7ebc959_0
icc_rt                    2019.0.0             h0cc432a_1
idna                      2.10                       py_0
importlib-metadata        2.0.0                      py_1
importlib-resources       4.1.0                    pypi_0    pypi
intel-openmp              2020.2                      254
ipykernel                 5.3.4            py38h5ca1d4c_0
ipython                   7.19.0           py38hd4e2768_0
ipython_genutils          0.2.0              pyhd3eb1b0_1
ipywidgets                7.6.0                    pypi_0    pypi
jedi                      0.17.2                   pypi_0    pypi
jinja2                    2.11.2                   pypi_0    pypi
joblib                    1.0.0                    pypi_0    pypi
jsonschema                3.2.0                    pypi_0    pypi
jupyter_client            6.1.7                      py_0
jupyter_core              4.7.0            py38haa95532_0
jupyterlab-pygments       0.1.2                    pypi_0    pypi
jupyterlab-widgets        1.0.0                    pypi_0    pypi
keras                     2.4.3                    pypi_0    pypi
keras-applications        1.0.8                      py_1
keras-preprocessing       1.1.2                    pypi_0    pypi
kiwisolver                1.3.1                    pypi_0    pypi
libprotobuf               3.13.0.1             h200bbdf_0
libsodium                 1.0.18               h62dcd97_0
markdown                  3.3.3            py38haa95532_0
markupsafe                1.1.1                    pypi_0    pypi
matplotlib                3.3.3                    pypi_0    pypi
mistune                   0.8.4                    pypi_0    pypi
mkl                       2020.2                      256
mkl-service               2.3.0            py38h196d8e1_0
mkl_fft                   1.2.0            py38h45dec08_0
mkl_random                1.1.1            py38h47e9c7a_0
multidict                 4.7.6            py38he774522_1
nbclient                  0.5.1                    pypi_0    pypi
nbconvert                 6.0.7                    pypi_0    pypi
nbformat                  5.0.8                    pypi_0    pypi
nest-asyncio              1.4.3                    pypi_0    pypi
notebook                  6.1.6                    pypi_0    pypi
numpy                     1.19.2           py38hadc3359_0
oauthlib                  3.1.0                      py_0
openssl                   1.1.1i               h2bbff1b_0
opt-einsum                3.3.0                    pypi_0    pypi
opt_einsum                3.1.0                      py_0
packaging                 20.8                     pypi_0    pypi
pandas                    1.2.0                    pypi_0    pypi
pandocfilters             1.4.3                    pypi_0    pypi
parso                     0.7.1                    pypi_0    pypi
pickleshare               0.7.5           pyhd3eb1b0_1003
pillow                    8.0.1                    pypi_0    pypi
pip                       20.3.3           py38haa95532_0
prometheus-client         0.9.0                    pypi_0    pypi
promise                   2.3                      pypi_0    pypi
prompt-toolkit            3.0.8                      py_0
protobuf                  3.13.0.1         py38ha925a31_1
pyasn1                    0.4.8                      py_0
pyasn1-modules            0.2.8                      py_0
pycparser                 2.20                       py_2
pygments                  2.7.3              pyhd3eb1b0_0
pyjwt                     1.7.1                    py38_0
pyopenssl                 20.0.0             pyhd3eb1b0_1
pyparsing                 2.4.7                    pypi_0    pypi
pyreadline                2.1                      py38_1
pyrsistent                0.17.3                   pypi_0    pypi
pysocks                   1.7.1            py38haa95532_0
python                    3.8.5                h5fd99cc_1
python-dateutil           2.8.1                      py_0
pytz                      2020.5                   pypi_0    pypi
pywin32                   300                      pypi_0    pypi
pywinpty                  0.5.7                    pypi_0    pypi
pyyaml                    5.3.1                    pypi_0    pypi
pyzmq                     20.0.0                   pypi_0    pypi
requests                  2.25.0             pyhd3eb1b0_0
requests-oauthlib         1.3.0                      py_0
rsa                       4.6                        py_0
scikit-learn              0.24.0                   pypi_0    pypi
scipy                     1.5.2            py38h14eb087_0
send2trash                1.5.0                    pypi_0    pypi
setuptools                51.0.0           py38haa95532_2
six                       1.15.0           py38haa95532_0
sqlite                    3.33.0               h2a8f88b_0
tensorboard               2.4.0                    pypi_0    pypi
tensorboard-plugin-wit    1.6.0                      py_0
tensorflow                2.4.0                    pypi_0    pypi
tensorflow-base           2.3.0           eigen_py38h75a453f_0
tensorflow-datasets       4.1.0                    pypi_0    pypi
tensorflow-estimator      2.4.0                    pypi_0    pypi
tensorflow-metadata       0.26.0                   pypi_0    pypi
termcolor                 1.1.0                    py38_1
terminado                 0.9.1                    pypi_0    pypi
testpath                  0.4.4                    pypi_0    pypi
threadpoolctl             2.1.0                    pypi_0    pypi
tornado                   6.0.3                    pypi_0    pypi
tqdm                      4.55.0                   pypi_0    pypi
traitlets                 5.0.5                      py_0
typing-extensions         3.7.4.3                       0
typing_extensions         3.7.4.3                    py_0
tzdata                    2020d                h14c3975_0
urllib3                   1.25.11                    py_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wcwidth                   0.2.5                      py_0
webencodings              0.5.1                    pypi_0    pypi
werkzeug                  1.0.1                      py_0
wheel                     0.36.1             pyhd3eb1b0_0
widgetsnbextension        3.5.1                    pypi_0    pypi
win_inet_pton             1.1.0            py38haa95532_0
wincertstore              0.2                      py38_0
wrapt                     1.12.1           py38he774522_1
yarl                      1.5.1            py38he774522_0
zeromq                    4.3.3                ha925a31_3
zipp                      3.4.0              pyhd3eb1b0_0
zlib                      1.2.11               h62dcd97_4

Hope that helps!

**Comment by bodmin69** [comment]
The temporary solution is to install numpy 1.19.3.
https://youtu.be/0DgOz3hJeC0
