### ISSUE TITLE
[Usage question] - How is probe insertion created

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#112]
**Describe the question you have**
Mayo stumbled on an ephys recording (KS002):
https://alyx.internationalbrainlab.org/admin/actions/ephyssession/2328b53b-0568-4f76-b5a3-d0a6698741a7/change/

which is missing the probe insertion
<img width="1196" alt="Capture d’écran 2020-11-23 à 15 45 21" src="https://user-images.githubusercontent.com/43007596/99976152-61489d00-2da3-11eb-98df-caf0eb0243cd.png">

and thus does not appear on alyx queries;
the session exists:
```
one.alyx.rest('sessions', 'list', id='2328b53b-0568-4f76-b5a3-d0a6698741a7')
Out[18]: 
[{'subject': 'KS002',
  'start_time': '2019-10-14T13:50:28.496000',
  'number': 1,
  'lab': 'cortexlab',
  'project': 'ibl_neuropixel_brainwide_01',
  'url': 'https://alyx.internationalbrainlab.org/sessions/2328b53b-0568-4f76-b5a3-d0a6698741a7',
  'task_protocol': '_iblrig_tasks_ephysChoiceWorld6.0.3'}]
```
but the insertion does not:
```
one.alyx.rest('insertions', 'list', session='2328b53b-0568-4f76-b5a3-d0a6698741a7')
returns []
```

My question is: 
Shouldn't the probe insertion be created upon finishing a recording automatically (by the pybpod task)? How is it done currently? Could this issue be due to an old task version? @nbonacchi 

**Is your question related to a specific product?**
pyBpod

**Comment by nbonacchi** [comment]
Probe insertions are initially created by the ephys transfer script here: 
https://github.com/int-brain-lab/ibllib/blob/f3e9f0e8605b1952fe52a58704730a00295a3909/ibllib/pipes/misc.py#L260

They are also created by the histology register_track_file method if they don't exist here:
https://github.com/int-brain-lab/ibllib/blob/07f21bba2fbdb7d5cb91ab22abb837486c8e5b89/ibllib/pipes/histology.py#L404

and whenever [ephys.spikes.probes_description](https://github.com/int-brain-lab/ibllib/blob/f3e9f0e8605b1952fe52a58704730a00295a3909/ibllib/ephys/spikes.py#L50 ) is called, if they don't exist, during the ephys preprocessing task (SpikeSortingKs2MAtlab task) here:
https://github.com/int-brain-lab/ibllib/blob/f3e9f0e8605b1952fe52a58704730a00295a3909/ibllib/pipes/ephys_preprocessing.py#L190

**Comment by GaelleChapuis** [comment]
Remarking this issue as "bug" as it seems a probe insertion should exist for this session based on the answer above.

**Comment by GaelleChapuis** [comment]
Similarly, there seem to be no insertion for:
ibl_witten_23, 2020-10-01, probe01

**Comment by mayofaulkner** [comment]
For ibl_witten_23 it looks like the data is still stuck on the local server uncompressed. I'm currently talking to Alex to create the correct flags so the data can be registered and extracted
