### ISSUE TITLE
[Bug report] - nyu-27 2020-09-29 trial extraction bug

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#114]
**Describe the bug**
There seem to be >400 trials for the session `eid='d6c86d3c-3980-4f28-b24b-1f9f8c73f0a7'` however when loading the trial data, only 2 trials appear.
This creates quite some confusion as the behavior criterion is computed from the loaded trial datasets (so for now, this session fails to pass the behavior criterion whilst it probably should pass).

**To Reproduce**
```
trials_all = one.load_object(eid, 'trials')
```
or
```
alf_path = one.path_from_eid(eid).joinpath('alf')
dsets = one.alyx.rest('datasets', 'list', session=eid, django='name__icontains,trials')
dsets = one.download_datasets(dsets)
if len(dsets) == 0:
    _logger.warning(f"{i_eid}/{len(eids)} No trials. Skipping. {eid} {alf_path} ")
    continue
tpath = next((d.parent for d in dsets if d))
trials_all = alf.io.load_object(tpath, 'trials', namespace='ibl')
```

**Comment by GaelleChapuis** [comment]
Not sure if it is related, but I am missing extracted trial data for NYU sessions:
754b74d5-7a06-4004-ae0c-72a10b6ed2e6 _iblrig_tasks_ephysChoiceWorld6.4.2 NYU-29 2020-09-21
041ef909-4578-4282-b0be-a58d1522566a _iblrig_tasks_ephysChoiceWorld6.4.2 NYU-27 2020-09-30
7b26ce84-07f9-43d1-957f-bc72aeb730a3 _iblrig_tasks_ephysChoiceWorld 6.4.2 NYU-27 2020-09-28 

And this one (above) needs to be redone because of n trials = 2:
d6c86d3c-3980-4f28-b24b-1f9f8c73f0a7 _iblrig_tasks_ephysChoiceWorld6.4.2 NYU-27 2020-09-29

**Comment by GaelleChapuis** [comment]
Data from NYU-23 also seems fishy:
46dd8a51-cde3-484b-9765-7dfe90a7a40c - 2020-10-16 - perf: [0.63043478]  ;  ntrial: [235]  ;  crit: False
8908c164-8609-49b3-93cb-f3e891a628dc - 2020-10-15 - perf: [0.625]  ;  ntrial: [347]  ;  crit: False
**61866af0-e29d-4ed1-afc0-d47ee7108f63 - 2020-10-14 - perf: [1.]  ;  ntrial: [2]  ;  crit: False**

**Comment by GaelleChapuis** [comment]
Note: 
<img width="1199" alt="Capture d’écran 2020-11-26 à 14 09 43" src="https://user-images.githubusercontent.com/43007596/100355125-80d50500-2ff1-11eb-8430-c3766a1b465a.png">
The session ` eid='d6c86d3c-3980-4f28-b24b-1f9f8c73f0a7'` has the warning
`WARNING  [ephys_fpga.py:303] BPOD/FPGA synchronization: Bpod and FPGA don't have the same amount of trial start events. Patching alf files.`
But the ephys pulses look fine
<img width="859" alt="Capture d’écran 2020-11-26 à 14 08 40" src="https://user-images.githubusercontent.com/43007596/100355119-7f0b4180-2ff1-11eb-8924-00c206f1225c.png">

**Comment by GaelleChapuis** [comment]
Setting manually the extraction job for those sessions as ERROR for now:
d6c86d3c-3980-4f28-b24b-1f9f8c73f0a7
61866af0-e29d-4ed1-afc0-d47ee7108f63
ebe2efe3-e8a1-451a-8947-76ef42427cc9
6527e2f1-8b2b-4b9b-a9dd-2a0206603ad8 

(but it's unclear if other sessions that pass now in a somewhat plausible fashion would also be affected)

**Comment by nbonacchi** [comment]
Some links to the respective Tasks:

754b74d5-7a06-4004-ae0c-72a10b6ed2e6 - [EphysTrials](https://alyx.internationalbrainlab.org/admin/jobs/task/d71ee12f-6c95-4934-a813-3718a4652f35/change/?_changelist_filters=q%3DNYU-29%26p%3D0)
041ef909-4578-4282-b0be-a58d1522566a - [EphysTrials](https://alyx.internationalbrainlab.org/admin/jobs/task/eeb1c767-69a3-464a-b557-13b6dc2f92de/change/?_changelist_filters=q%3DNYU-27) 
7b26ce84-07f9-43d1-957f-bc72aeb730a3 - [EphysTrials](https://alyx.internationalbrainlab.org/admin/jobs/task/1264aaf7-b264-433a-b91a-86a94af975ad/change/?_changelist_filters=q%3DNYU-27) 
d6c86d3c-3980-4f28-b24b-1f9f8c73f0a7 - [EphysTrials](https://alyx.internationalbrainlab.org/admin/jobs/task/dfa0b36e-6f6e-4394-8d84-41fda748c806/change/?_changelist_filters=q%3DNYU-27)

**Comment by nbonacchi** [comment]
Some links to the respective Tasks:

754b74d5-7a06-4004-ae0c-72a10b6ed2e6 - [EphysTrials](https://alyx.internationalbrainlab.org/admin/jobs/task/d71ee12f-6c95-4934-a813-3718a4652f35/change/?_changelist_filters=q%3DNYU-29%26p%3D0)
041ef909-4578-4282-b0be-a58d1522566a - [EphysTrials](https://alyx.internationalbrainlab.org/admin/jobs/task/eeb1c767-69a3-464a-b557-13b6dc2f92de/change/?_changelist_filters=q%3DNYU-27) 
7b26ce84-07f9-43d1-957f-bc72aeb730a3 - [EphysTrials](https://alyx.internationalbrainlab.org/admin/jobs/task/1264aaf7-b264-433a-b91a-86a94af975ad/change/?_changelist_filters=q%3DNYU-27) 
d6c86d3c-3980-4f28-b24b-1f9f8c73f0a7 - [EphysTrials](https://alyx.internationalbrainlab.org/admin/jobs/task/dfa0b36e-6f6e-4394-8d84-41fda748c806/change/?_changelist_filters=q%3DNYU-27)

**Comment by oliche** [comment]
Yup it's a known thing. 
They have several issues in this lab: 

- bpod analog trace on nidq has DC offset, grounding issue which impairs the pulse detection
- bpod start trial pulses exceed 23 ms and are not detected as such

Those issues can be compounded.
There is a case for sync sweeps (spacers) at regular 20 mins intervals because it's quite hard to synchronize bpod and FPGA with this kind of hardware.

**Comment by GaelleChapuis** [comment]
@oliche  thanks for this.
Can you describe what you mean by "DC offset" and "ground issue"? Is this something @jeanpaulnc can fix by changing the hardware configuration?

@nbonacchi @k1o0 this sounds like yet another extractor exception to be written.

**Comment by GaelleChapuis** [comment]
New extraction to deal with this issue ; Release notes: https://github.com/int-brain-lab/ibllib/blob/master/release_notes.md , version 1.5.34

Session eid='d6c86d3c-3980-4f28-b24b-1f9f8c73f0a7' has now 494 trials.
