### ISSUE TITLE
[Bug report] - Inconsistent data structure in two Sessions (DY_020, DY_016) 

### ISSUE THREAD

**Issue by yanliangshi** [int-brain-lab/iblenv#119]
1. Session: ‘4a45c8ba-db6f-4f11-9403-56e06a33dfa4’, DY_020/2020-09-29/001, Cluster_id of clusters.metrics (636,) is not consistent with cluster-id in spikes.clusters, since np.max(spikes.cluster)>635. 

2. Session: DY_016/2020-09-12/001, Inconsistent dimensions for object:spikes (8425832,),  times(8547612,),  clusters; clusters(499,),  depths(491, 20),  metrics(482,),  channels

**Expected behavior**
1. cluster-id clusters.metrics should be larger than spikes.clusters

2. len(spikes.times) should be the same as len(spikes.clusters)
 
3. Dim of clusters.depth should match clusters.metrics

**Comment by mayofaulkner** [comment]
1. The cluster.metrics only contains rows for clusters that have > 1 spike. Although there are 657 cluster_ids, there are only 636 which contain spikes. The following conditions hold
```
np.max(cluster.metrics['cluster_id']) == np.max(spikes.clusters) 
 len(np.unique(spikes.clusters)) == len(clusters.metrics)
```

2. Thanks for pointing this out. The inconsistency came from the spike sorting files coming from two locations. This has been patched now and consistent files should be uploaded on flatiron by tomorrow.

I'll close this but feel free to reopen if you have more questions
