### ISSUE TITLE
[Usage question] - Is there a way that I can search all the Ephys. alignment that one person has done on the Ephys. alignment GUI please? if yes, how? cheers!

### ISSUE THREAD

**Issue by Petrina-Lau** [int-brain-lab/iblenv#121]
**Describe the question you have**
A clear and concise description of the question you have. Ex. How can I do [...] ?

**Is your question related to a specific product?**
Add links to relevant repositories or documents if so.

**Additional context**
Add any other context or screenshots about the usage question here.

**Comment by GaelleChapuis** [comment]
example from Mayo: (change the username)
```
from oneibl.one import ONE
one = ONE()
alyx_username='mayo'
traj = one.alyx.rest('trajectories', 'list', django=f'json__icontains,{alyx_username}')
```
