### ISSUE TITLE
[Usage question] - How to load 1 frame from specific video camera

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#122]
**Describe the question you have**
I would like to get one frame for a given session (ideally the middle frame related to all acquired frames), on a specific camera (e.g. left).

How can I do the following **without** downloading the whole raw video file: 

1. focus on a particular camera data and session eid
2. retrieve how many frames there are in that video (N)
3.  download just the middle frame (floor(N/2))

@yeebc kindly pointed me to this code: 
https://github.com/int-brain-lab/iblapps/blob/master/dlc/wheel_dlc_viewer.py
and I have some usage questions.

I downloaded video data for trial=100 as per the example 1:
```
eid = '77224050-7848-4680-ad3c-109d3bcd562c'
v = Viewer(eid=eid, trial=100)
```
```
Downloading: /Users/gaelle/Downloads/FlatIron/wittenlab/Subjects/ibl_witten_13/2019-11-01/001/raw_video_data/_iblrig_leftCamera.raw.eb86e894-c374-44e6-92f5-cfaafc6349fc.mp4 Bytes: 547335027
Downloading: /Users/gaelle/Downloads/FlatIron/wittenlab/Subjects/ibl_witten_13/2019-11-01/001/alf/_ibl_leftCamera.times.5297e174-02dc-4d67-ac40-221fd3675bde.npy Bytes: 1293936
 |████████████████████████████████████████████████████████████████████████████████████████████████████| 100.0% 2020-12-01 14:39:20.852 INFO     [<ipython-input-9-1d64dc5dbf60>:161] Frame rate = 30Hz
```

- I use the path to that video file in the function `get_video_frame` but get this error:

```
get_video_frame(video_path='/Users/gaelle/Downloads/FlatIron/wittenlab/Subjects/ibl_witten_13/2019-11-01/001/raw_video_data', frame_number=77)
OpenCV: Couldn't read video stream from file "/Users/gaelle/Downloads/FlatIron/wittenlab/Subjects/ibl_witten_13/2019-11-01/001/raw_video_data"
[ERROR:0] global /private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/pip-req-build-ucld1hvm/opencv/modules/videoio/src/cap.cpp (142) open VIDEOIO(CV_IMAGES): raised OpenCV exception:
OpenCV(4.4.0) /private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/pip-req-build-ucld1hvm/opencv/modules/videoio/src/cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): /Users/gaelle/Downloads/FlatIron/wittenlab/Subjects/ibl_witten_13/2019-11-01/001/raw_video_data in function 'icvExtractPattern'
```
I am guessing this is because the whole video is not downloaded?

Also, how to specify which camera ( left / right / body ) to load the data from?

**Comment by k1o0** [comment]
You must provide the full path to the mp4 file you want to load.  You called the function with the folder path, not the file path. 
`frame = get_video_frame('/Users/gaelle/Downloads/FlatIron/wittenlab/Subjects/ibl_witten_13/2019-11-01/001/raw_video_data/_iblrig_leftCamera.raw.mp4', 77)`.

If you can open the video in a movie player like VLC then you should be able to grab a frame via OpenCV.  Please close this issue it it answered your question.

**Comment by GaelleChapuis** [comment]
From @oliche :
```
from oneibl.stream import VideoStreamer
from oneibl.one import ONE
# example 1: with URL directly
frame_id = 4000
url = "http://ibl.flatironinstitute.org/mainenlab/Subjects/ZM_1743/2019" \
      "-06-17/001/raw_video_data/_iblrig_leftCamera.raw.00002677-a6d1-49fb-888b-66679184ee0e.mp4"
vs = VideoStreamer(url)
# example 2: with a dset dict
one = ONE()
eid = "a9fb578a-9d7d-42b4-8dbc-3b419ce9f424"
dset = one.alyx.rest('datasets', 'list', session=eid, name='_iblrig_leftCamera.raw.mp4')
vs = VideoStreamer(dset[0])
f, im = vs.get_frame(frame_id)
```
