### ISSUE TITLE
[Bug report] - Mayavi on Mac does not display image

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#124]
**Describe the bug**
No image display (using Mac OS 10.15.7 ; Python 3.7)
<img width="973" alt="Capture d’écran 2020-12-02 à 12 24 48" src="https://user-images.githubusercontent.com/43007596/100866994-ca15d080-3499-11eb-8d8a-2a89812b96f9.png">

**To Reproduce**
https://docs.enthought.com/mayavi/mayavi/mlab.html#a-demo
```
from numpy import pi, sin, cos, mgrid
dphi, dtheta = pi/250.0, pi/250.0
[phi,theta] = mgrid[0:pi+dphi*1.5:dphi,0:2*pi+dtheta*1.5:dtheta]
m0 = 4; m1 = 3; m2 = 2; m3 = 3; m4 = 6; m5 = 2; m6 = 6; m7 = 4;
r = sin(m0*phi)**m1 + cos(m2*phi)**m3 + sin(m4*theta)**m5 + cos(m6*theta)**m7
x = r*sin(phi)*cos(theta)
y = r*cos(phi)
z = r*sin(phi)*sin(theta)

# View it.
from mayavi import mlab
s = mlab.mesh(x, y, z)
mlab.show()
```

**Expected behavior**
Used to work on Mac OS

**Comment by mayofaulkner** [comment]
Upgrading PyQt to PyQt 5.12 works on my mac! All I had to do was change "pyqt" to "pyqt >= 5.12" in the yaml environment file

Change has been reflected in the iblenv.yaml file https://github.com/int-brain-lab/iblenv/commit/71449ae52ec312ee59b4911a5d7a1fcc654cabd8#diff-502cbcbd03ec6be9ca0a431a1abeabd9fae643b77c4cb22b24ae47523907be7c
