### ISSUE TITLE
[Feature request] - Display camera image + overlaid calibration contours at beginning of session

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#126]
**Is your feature request related to a problem? Please describe.**
It is currently difficult for the experimenters to know whether their camera are well-positioned. We have a Bonsai workflow that allows for this, marking the contour of the objects for positioning and the exposure to set, but it is not regularly checked for.

**Describe the solution you'd like**
Several options (not necessarily mutually exclusive):

- save time of last camera(s) calibration, and launch automatically (frequency TBD) the bonsai workflow upon expiry of the last found calibration
- display 1 frame acquired at beginning of pyBod with Bonsai trace overlaid, so users can quickly check placement

This is beside the QC to be done once the data has been acquired (QC on the raw images and on DLC output), that can also go towards user warning.

**Describe alternatives you've considered**
Plotting frames after an experiment has been performed.

**Comment by nbonacchi** [comment]
For ephys sessions there is a camera view step that is launched right after prepare_video_session.py script runs.
I can overlay the same calibration image to the video so users can verify not only the mouse position but also the camera reference...
