### ISSUE TITLE
EPhys. alignment has to re-download subject 

### ISSUE THREAD

**Issue by Petrina-Lau** [int-brain-lab/iblenv#130]
EPhys. alignment GUI has to re-download the subject that has been previously aligned by the same user on the same computer. User doesn't recognize the alignment too but not sure if it is an upload by mistake or there is a shift in what has been uploaded.

**Comment by mayofaulkner** [comment]
Error in code that propagated alignments from one session to a new session, when the new session had not previously been aligned by anybody. Error has been fixed in latest version of alignment gui https://github.com/int-brain-lab/iblapps/commit/d65d28e994b3be4eaec0d0c0a63e1921ccd43ebd
