### ISSUE TITLE
[Bug report] - Error running camera alignment

### ISSUE THREAD

**Issue by Petrina-Lau** [int-brain-lab/iblenv#131]
Hi all, I was trying to run camera alignment but got an error message about FlyCapture2, "The specified module could not be found" please see attached screen shot for details.
I have follow the protocol to reset Flycapture2, and disconnected and reconnect everything but still get this error message. FYI, The training scripts run fine on bpod. Just when I run bonsai independently, there seems to have an issue. I am using Bonsai version 2.5.2.  

![image](https://user-images.githubusercontent.com/61651331/101375136-f620bf80-38a6-11eb-9b01-649eac64edd4.png)

**Comment by nbonacchi** [comment]
This lookes like a bad installation of Bonsai or lack of camera drivers, is this fixed now?

**Comment by k1o0** [comment]
It's been nearly a month.  Closing for now.
