### ISSUE TITLE
[Bug report] - module 'brainbox.metrics' has no attribute 'cum_drift'

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#132]
**Describe the bug**
I am trying to plot a raster plot using:

```
from oneibl.one import ONE
import alf.io
import matplotlib.pyplot as plt
import brainbox.plot as bbplot

eid = 'dfd8e7df-dc51-4589-b6ca-7baccfeb94b4'
probe_label = 'probe00'

dtypes = ['spikes.times',
          'spikes.depths',
          'spikes.amps']

# Download the data and get paths to downloaded data
_ = one.load(eid, dataset_types=dtypes, download_only=True)
alf_path = one.path_from_eid(eid).joinpath('alf', probe_label)

# Load in spikes object and use brainbox function to plot raster
spikes = alf.io.load_object(alf_path, 'spikes')
bbplot.driftmap(spikes['times'],
                spikes['depths'],
                plot_style='bincount')
plt.show()
```

I get this error message:
```
Traceback (most recent call last):
  File "/Users/gaelle/opt/anaconda3/envs/iblenv/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-11-77cbed35163d>", line 3, in <module>
    plot_style='bincount')
  File "/Users/gaelle/Documents/Git/int-brain-lab/ibllib-repo/brainbox/plot/plot.py", line 660, in driftmap
    cd = bb.metrics.cum_drift(feat[iok])
AttributeError: module 'brainbox.metrics' has no attribute 'cum_drift'
```

inspecting `bb.metrics` from `plot.py` [code [here](https://github.com/int-brain-lab/ibllib/blob/4a0196125af635d132c118894ac1ca57c7f1d187/brainbox/plot/plot.py#L660)] lands me on an __init__ file that only contains 1 line:
`from .metrics import *`

**To Reproduce**
Use example above, on ibllib develop.

**Expected behavior**
A plot to show.

**Comment by GaelleChapuis** [comment]
It looks like lines 660-661 (and the associated return) could simply be deleted?

**Comment by oliche** [comment]
Yes I ran into the same issue earlier and had this fixed in the `unitmetrics` branch.
I've merged this into `develop` so just pull.

**Comment by GaelleChapuis** [comment]
I am confused why this test did not fail in the CI as there is an integrated example using this code? https://github.com/int-brain-lab/ibllib/blob/master/examples/one/ephys/docs_compute_drift.py
