### ISSUE TITLE
[Usage question] - How to change a task status using alyx.rest

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#137]
**Describe the question you have**
I would like to change a task status programmatically, how to do this with one.alyx.rest?

For example, to set this task (id: '460ef106-2b13-4ff0-b464-860d28b34153') status to 'Waiting'
is this the correct nomenclature: (inspired from https://alyx.internationalbrainlab.org/docs/#tasks-update )
`one.alyx.rest('tasks', 'update', id='460ef106-2b13-4ff0-b464-860d28b34153', status='Waiting')`
?

(I'd rather ask before doing something wrong!)

**Comment by mayofaulkner** [comment]
```
task_id = '460ef106-2b13-4ff0-b464-860d28b34153'
stat = {'status': 'Waiting'}
one.alyx.rest('tasks', 'partial_update', id=task_id, data=stat)
```

**Comment by GaelleChapuis** [comment]
Thank you @mayofaulkner !
