### ISSUE TITLE
re-extract ephys session with behavior spread over 2 sessions

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblenv#138]
CSHL049/2020-01-12 has one set of ephys + video files, but the behavior is spread over session 002 and 003 (since I stopped the pybpod task, had to flush the water, and restarted).  session 002 (https://alyx.internationalbrainlab.org/admin/actions/ephyssession/08e25a6c-4223-462a-a856-a3a587146668/change/?_changelist_filters=q%3Dcshl049) has the ephys + video + penetrations, but 003 has all the trials in Alyx.

Can the two sets of behavioral trials be merged, and the ephys re-extracted, so that all the trials can be used?

**Comment by GaelleChapuis** [comment]
There is little bandwidth to deal with this kind of special cases at the moment; this dataset may not be extracted for a while.

**Comment by k1o0** [comment]
I'm marking this as 'wontfix' for now.  At some point we may attack all the sessions with these sorts of issues but right now we have too many normal sessions that need processing.
