### ISSUE TITLE
[Feature request] - No lab assigned to Petrina

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#145]
**Is your feature request related to a problem? Please describe.**
It seems the assignment to lab is missing for Petrina: 
```
users = one.alyx.rest('users','list')
user_str = petrina.lau
[item for item in users if item['username'] in user_str] :

[{'id': '300e4e7d-78f4-4f59-9717-17b60f5d26ed',
  'username': 'petrina.lau',
  'email': 'petrina.lau@internationalbrainlab.org',
  'subjects_responsible': ['PL001', 'PL002', 'PL003', 'PL004'],
  'lab': []}]
```

**Describe the solution you'd like**
Could someone add the hausserlab to this user? (sorry I do not know how to do this from the interface)

**Comment by rossant** [comment]
do you have access to https://alyx.internationalbrainlab.org/admin/misc/labmembership/add/ ?

**Comment by GaelleChapuis** [comment]
Yes, I just found that page actually (I initially thought it would be under lab or member) and added it to the developers recipe :). I was going to ask if this was the right way. Thanks for confirming !
