### ISSUE TITLE
[Bug report] - Discrepancy between trajectory and alignment count

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#146]
**Describe the bug**

This example insertion (id below) has `'alignment_count': 2`, however there is only 1 'Ephys aligned histology track' trajectory
```
ins_id = 'a226c68d-55d8-4b53-9596-7c88a3ffa259'
traj = one.alyx.rest('trajectories', 'list', provenance='Ephys aligned histology track',
                     probe_insertion= ins_id)
# Check if already aligned 2x or more
al_query = one.alyx.rest('insertions', 'list', id=ins_id,
                                          django='json__extended_qc__alignment_count__gt,1')
```

**To Reproduce**
Code above
**Expected behavior**
I thought `'alignment_count'` should be equal to the number of 'Ephys aligned histology track' trajectory for a given insertion?

**Comment by mayofaulkner** [comment]
There is only ever one ephys aligned histology track per probe insertion. This will either be the latest aligned track or the resolved track. The user alignments are stored in the json field of the trajectory which means any users trajectory can be recovered when needed. The alignment_count == len(trajectories['json'])

**Comment by GaelleChapuis** [comment]
I see, then there is no discrepancy, thanks !
