### ISSUE TITLE
[Bug report] - Wrong camera labelling + up-side down image

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#147]
**Describe the bug**
It seems that for 2 sessions, the labels and direction of the camera images are mixed up.
![ZM_3003__2020-07-27__934dd7a4-fbdc-459c-8830-04fe9033bc28](https://user-images.githubusercontent.com/43007596/102217173-7c0ebd00-3edc-11eb-8665-4d3e0c50ef77.png)

![ZM_3003__2020-07-27__934dd7a4-fbdc-459c-8830-04fe9033bc28](https://user-images.githubusercontent.com/43007596/102217239-95176e00-3edc-11eb-9e80-c89a20c121ae.png)

**To Reproduce**
Plot the images using the video streamer.

**Expected behavior**
I am putting an example of a good session here.
![ZM_2245__2020-01-21__cb2ad999-a6cb-42ff-bf71-1774c57e5308](https://user-images.githubusercontent.com/43007596/102217277-a19bc680-3edc-11eb-8942-0e50bddad055.png)

**Screenshots**
See above.

**Comment by k1o0** [comment]
I assume this is a wiring issue or an Bonsai setting the wasn't set correctly.  Could you ask the experimenter about it?

**Comment by GaelleChapuis** [comment]
Yes I already did actually. Leaving this issue open until we get to the bottom on it.

**Comment by k1o0** [comment]
I think it's is safe to assume this is a human error.  If there's nothing in the session notes and the experimenter has no information then there's not much we can do.  Manually fixing the labels and video headers is a lot of work so I am going to make this as 'wontfix'.
