### ISSUE TITLE
[Usage question] - How to get the session status via ONE

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#15]
**Describe the question you have**
How to get the session status (e.g. CRITICAL) via ONE?

**Is your question related to a specific product?**
ibllib

**Additional context**
An example code in the documentation would be great.

**Comment by mayofaulkner** [comment]
One way is to read in the full session info associated with an eid and look at the QC field
```python
eid = '452b2d41-f3ed-4ca8-ad68-79cb6efdd40f'
sess_info = one.alyx.rest('sessions', 'read', id=eid)
qc = sess_info['qc']
```

**Comment by anne-urai** [comment]
While `sess_info = one.alyx.rest('sessions', 'read', id=eid)` works, it's incredibly slow: the rest command returns a huge dictionary with pretty much anything there is to know about that session. 

Is it possible to subset this rest query, to only retrieve the QC and speed this up?
The [ibllib documentation](https://docs.internationalbrainlab.org/en/latest/_autosummary/oneibl.webclient.html?highlight=one.alyx.rest#oneibl.webclient.AlyxClient.rest) is not very clear on this, and I'm not sure where to find the specific REST documentation mentioned there.

**Comment by mayofaulkner** [comment]
If you want to find all the sessions that have a qc of a given status ('critical', 'error', 'not_set', 'warning') you can use the following which is much quicker,
```
sess_with_critical_qc = one.alyx.rest('sessions', 'list', qc='critical')
```
To find the qc of a given session, however, I think the `one.alyx.rest('sessions', 'read', id=eid)` is the only way at the moment (@oliche may have a better suggestion).

[This](https://int-brain-lab.github.io/iblenv/notebooks/one_advanced/one_advanced.html) tutorial has a bit more information about the usage of `one.alyx.rest`. Still WIP but might be useful!

**Comment by anne-urai** [comment]
thanks @mayofaulkner! An example of linking these with DataJoint QC metrics is here https://github.com/int-brain-lab/analysis/blob/master/python/session_qc_overview.ipynb

**Comment by GaelleChapuis** [comment]
Get the eids of sessions with session QC better than critical using ONE:
```
from oneibl.one import ONE
one = ONE()

eids_sess_betterthan_critical = one.alyx.rest('sessions', 'list', django='session__qc__lt,40')

```
For a given `eid` in this list of session, get the session behavior QC status from DJ:

```
from ibl_pipeline import acquisition
from ibl_pipeline.analyses import behavior as behavior_analysis

sessions = acquisition.Session()
session_trainstat = behavior_analysis.SessionTrainingStatus
sess_train_qc = ((sessions & {'session_uuid': eid}).proj() * session_trainstat).fetch(format='frame')

```
List of keys:
```
sess_train_qc.keys() : ['training_status', 'good_enough_for_brainwide_map']
```
Use the key `'good_enough_for_brainwide_map'` to get the behavior QC output (if `=0`, it means the behavior QC is not passed)

**Comment by shenshan** [comment]
Hi @GaelleChapuis, there is a faster query to filter the good data given a list of eids `sess_betterthan_critical`.

`acquisition.Session & [{'session_uuid': eid} for eid in sess_betterthan_critical] & (behavior_analysis.SessionTrainingStatus & 'good_enough_for_brainwide_map=1')`

**Comment by GaelleChapuis** [comment]
@shenshan a similar query does not seem to work for me, example:

Session eids:
```
eids = ['8db36de1-8f17-4446-b527-b5d91909b45a',
 '934dd7a4-fbdc-459c-8830-04fe9033bc28',
 'f312aaec-3b6f-44b3-86b4-3a0c119c0438']
```
Code snippet:
```
data_all = acquisition.Session & [{'session_uuid': i_e} for i_e in eids] & \
           (behavior_analysis.SessionTrainingStatus & 'good_enough_for_brainwide_map=1')
```

I get several errors after running in a row the same snippet of code (most of them because of running through the command lines I presume):
- IndexError: index out of range
- AttributeError: 'NoneType' object has no attribute 'read'
- pymysql.err.InternalError: Packet sequence number wrong - got 102 expected 9
- pymysql.err.InternalError: Packet sequence number wrong - got 98 expected 2

Could you tell me if the code is correct? I cannot run it at present. Thanks !

**Comment by shenshan** [comment]
This code works for me, do you use PyCharm to run the code snippet?

**Comment by GaelleChapuis** [comment]
Yes pyCharm, using Ctrl shift E

**Comment by shenshan** [comment]
Yeah I think pyCharm has some too-fancy features that datajoint is not behaving properly.
