### ISSUE TITLE
register_lasagna_tracks to Alyx returns empty coordinates for non-empty file

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblenv#151]
When uploading histology traces for CSHL060/2020-03-09/002/probe00 (re-did the tracing in Lasagna twice and tried both csv files), the ‘histology track’ trajectory appears on Alyx but with empty values:
https://alyx.internationalbrainlab.org/admin/experiments/probeinsertion/9f99bd34-40d4-4aac-ae2b-7bc7f7086ccb/change/

Not sure how to fix this, since both csv files are normal and uncorrupted. Perhaps there's something off with this particular insertion's logging in Alyx?

Slack message with files https://int-brain-lab.slack.com/archives/CEM70EXTN/p1608631697339700

**Comment by mayofaulkner** [comment]
Thanks for reporting this error. The track was being registered as none as the old implementation of the code was unable to locate the correct brain entry location. In the latest commit to develop https://github.com/int-brain-lab/ibllib/commit/39c610142c24a8942400dafbe0d8c84973b5ebbd we have improved the code to account for these edge cases. I have updated the probe insertion to now have the histology trajectory correctly registered https://alyx.internationalbrainlab.org/admin/experiments/probeinsertion/9f99bd34-40d4-4aac-ae2b-7bc7f7086ccb/change/
