### ISSUE TITLE
one.load: remote protocol and/or hostname does not match HTTP_DATA_SERVER parameter

### ISSUE THREAD

**Issue by mschart** [int-brain-lab/iblenv#152]
Some issue when trying to load data:

```
eid = 'bd456d8f-d36e-434a-8051-ff3997253802'
one.load(eid)

~/miniconda3/envs/DLC2/lib/python3.7/site-packages/oneibl/one.py in download_dataset(self, dset, cache_dir, **kwargs)
    741         assert url.startswith(self._par.HTTP_DATA_SERVER), \
    742             ('remote protocol and/or hostname does not match HTTP_DATA_SERVER parameter:\n' +
--> 743              f'"{url[:40]}..." should start with "{self._par.HTTP_DATA_SERVER}"')
    744         relpath = Path(url.replace(self._par.HTTP_DATA_SERVER, '.')).parents[0]
    745         target_dir = Path(self._get_cache_dir(cache_dir), relpath)

AssertionError: remote protocol and/or hostname does not match HTTP_DATA_SERVER parameter:
"https://ibl.flatironinstitute.org/danlab..." should start with "http://ibl.flatironinstitute.org"
```
Same for any of these 21 eids I've tried:

eids = ['1ec23a70-b94b-4e9c-a0df-8c2151da3761',
 '20c112a1-8a42-44e0-a4cd-e5b932f7bda9',
 '2aa7e80e-102b-41e7-b932-9310eb38684a',
 '3d6f6788-0b99-410f-9703-c43ca3e42a21',
 '4364a246-f8d7-4ce7-ba23-a098104b96e4',
 '4720c98a-a305-4fba-affb-bbfa00a724a4',
 '4fa70097-8101-4f10-b585-db39429c5ed0',
 '549caacc-3bd7-40f1-913d-e94141816547',
 '5522ac4b-0e41-4c53-836a-aaa17e82b9eb',
 '5b44c40f-80f4-44fb-abfb-c7f19e27a6ca',
 '7622da34-51b6-4661-98ae-a57d40806008',
 '8e5adb43-efaf-4d79-9652-0b480bbc5c2c',
 '934dd7a4-fbdc-459c-8830-04fe9033bc28',
 'b182b754-3c3e-4942-8144-6ee790926b58',
 'b39752db-abdb-47ab-ae78-e8608bbf50ed',
 'b658bc7d-07cd-4203-8a25-7b16b549851b',
 'bd456d8f-d36e-434a-8051-ff3997253802',
 'c7bd79c9-c47e-4ea5-aea3-74dda991b48e',
 'ee5c418c-e7fa-431d-8796-b2033e000b75',
 'f25642c6-27a5-4a97-9ea0-06652db79fbd',
 'f3ce3197-d534-4618-bf81-b687555d1883']

**Comment by mschart** [comment]
You need to update your ibllib parameter file:
"HTTP_DATA_SERVER": "http://ibl.flatironinstitute.org",
"HTTP_DATA_SERVER": "https://ibl.flatironinstitute.org",
Remember, your parameter file is in:
• Linux ~/.one_params
• Windows C:\Users\CurrentUser\AppData\Roaming\.one_params
• Mac /Users/CurrentUser/.one_params
Alternatively you can also just pull the latest ibllib 1.5.30 (master or develop).

**Comment by njmiska** [comment]
I am doing some analysis using another branch of ibllib and am still getting this error.  My one_params file correctly lists "HTTP_DATA_SERVER": "http://ibl.flatironinstitute.org".  Do you know what was changed in ibllib to fix this on the master/develop branches? The params.py file in ibllib/oneibl of the branch I am working with also lists "HTTP_DATA_SERVER": "http://ibl.flatironinstitute.org", so I'm not sure where this is being incorrectly read from...

**Comment by nbonacchi** [comment]
needs to be https

**Comment by njmiska** [comment]
ah, I see.  Sorry, the error was confusing me, I thought it should be http.  That fixed it, thanks
