### ISSUE TITLE
[Usage question] - How to get the params.py file for Phy

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#157]
**Describe the question you have**
I am trying to launch Phy on two datasets but am getting this error:
`Error: Invalid value for 'PARAMS_PATH': Path 'params.py' does not exist.`

I downloaded solely the alf collection using:

```
from oneibl.one import ONE
eids = ['8908c164-8609-49b3-93cb-f3e891a628dc', '89f0d6ff-69f4-45bc-b89e-72868abb042a']
one = ONE()
dsets = one.alyx.rest('datasets', 'list', django=f'session__in,{eids}', collection='alf')
one.download_datasets(dsets)
```
Should the params.py be found on FI ?
Using this:
ds = one.alyx.rest('datasets', 'list', session='89f0d6ff-69f4-45bc-b89e-72868abb042a', django='name__icontains,param')
I get an empty return.

Where is this file stored / what's the nomenclature? (or is this error unrelated to this file?)

**Comment by rossant** [comment]
I would say the "right" way is to use https://github.com/int-brain-lab/iblapps/tree/master/launch_phy
Does that help?

**Comment by GaelleChapuis** [comment]
Yes this helps! I am launching like so:
```
(iblenv) macbook-pro-de-gaelle:alf gaelle$ pwd
/Users/gaelle/Downloads/FlatIron/churchlandlab/Subjects/CSHL047/2020-01-20/001/alf
(iblenv) macbook-pro-de-gaelle:alf gaelle$ python /Users/gaelle/Documents/Git/int-brain-lab/iblapps/launch_phy/phy_launcher.py -e 89f0d6ff-69f4-45bc-b89e-72868abb042a -p probe00
```
I've got a connection error but this does not have something to do with this, closing. Thanks!
