### ISSUE TITLE
[Bug report] - Misaligned trials.stimOn_times and trials.probabilityLeft

### ISSUE THREAD

**Issue by SebastianBruijns** [int-brain-lab/iblenv#158]
Hi, came across this bug after running code again that worked before christmas:

```
one = ONE()
eid = 'b03fbc44-3d8e-4a6c-8a50-5ea3498568e0'
times = one.load(eid, dataset_types=['trials.stimOn_times'])[0]
block_prob = one.load(eid, dataset_types=['trials.probabilityLeft'])
event_times_left = times[block_prob[0] == 0.8]
```

Last line doesn't work because the two arrays have different dimensions (400 vs 402 trials).
Any idea what's going on?

**Comment by mayofaulkner** [comment]
Looks like the data was patched yesterday but not all the new files were uploaded to FlatIron. I've rerun the task and will watch over to make sure the correct files get uploaded.

**Comment by mayofaulkner** [comment]
Data has been patched and the code snippet runs without error now. 
`times.shape == block_prob[0].shape`

I will close this issue for now but feel free to reopen if you run into other problems
