### ISSUE TITLE
[Feature request] - Add neural responses to events on GUI to align histology/ephys

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#16]
**Is your feature request related to a problem? Please describe.**
Add RF mapping / plotting auditory response in the GUI for aligning ephys-histology.

**Describe the solution you'd like**
Receptive fields for single units (or multi-unit per depth, TBD) ; auditory responses per unit (raster+Psth; separately for GoCue and NoiseCue)

**Describe alternatives you've considered**
Datajoint view, but not as practical to use during the alignment process.

**Additional context**
Recycle code from certification for RF.
https://github.com/int-brain-lab/iblapps/tree/develop/atlaselectrophysiology

**Comment by nsteinme** [comment]
For RF maps suggest to bin spikes by depth to get multi-unit of all neurons in a certain depth bin (e.g. use 80 µm). Then plot map and response, like in this image. The way you do this is count spikes for the unit at each time offset (e.g. use 10 ms bin size in the window -0.05 to 0.2) around each stimulus flash, then average across all trials separately for each stimulus position. This gives you a matrix of average counts that is size nPositions x nTimeBins. Take the SVD of this matrix. Reshape the first spatial component to make a 2d matrix and plot it as an image (the map). Plot the first temporal component as the response over time. 
![image](https://user-images.githubusercontent.com/7590975/91231406-08089900-e6e2-11ea-80d5-48e14a4bf924.png)

**Comment by nsteinme** [comment]
For auditory responses, just bin the spikes as before and plot the mean PSTH following auditory stimulus onset (I would consider goCue, noiseCue, and rewardValve - and use the passive time window for this)

**Comment by nsteinme** [comment]
Worth thinking about how to make the GUI extensible. E.g. providing RF map data should be its own thing and the user should just be required to provide a three-column matrix with columns X position, Y position, and time of flash. But for event PSTHs you could have a generic mode where they provide any number of vectors containing event times, e.g. with filenames like "event_gocue.npy" and it can plot them with a label of whatever's after "event_".

**Comment by GaelleChapuis** [comment]
Plots are now integrated in the GUI for sessions with PassiveCW data extracted.
