### ISSUE TITLE
Subject session not updated and new subject cannot be loaded

### ISSUE THREAD

**Issue by Petrina-Lau** [int-brain-lab/iblenv#160]
I have been training 4 animals, 2 of them (i.e. PL001 and PL004) share the same rig (i.e. _iblrig_hausserlab_behavior_1). While the session on PL001 is updated every day as I train, PL004 has no update on its session even though I am trying them as others since 7th Dec 2020. 

I only realise it now, when I had trouble adding new subject on Alyx and loading new subject on, i.e. After I registered the new subject in Alyx, I tried to run the protocol with the new subject but error message shows up (will upload that error message here tomorrow), so I am not able to train the new animals. please advise! cheers!

**Comment by mayofaulkner** [comment]
Do you have an example of the error message you are getting when adding the new subject.

**Comment by Petrina-Lau** [comment]
It worked somehow after adding the subject there, then closing and re-opening bpod. It didn't work before for sometime but I don't know what I did differently that made it worked now...
