### ISSUE TITLE
[Bug report] - cannot load trial data by ONE 

### ISSUE THREAD

**Issue by yanliangshi** [int-brain-lab/iblenv#161]
**Describe the bug**

This week, after Christmas break, I cannot load trial data for multiple sessions.

For example, 

eid=‘f9860a11-24d3-452e-ab95-39e199f20a93’ 
stim_on= one.load(eid, dataset_types =‘trials.stimOn_times’)

WARNING  [one.py:180] dataset trials.stimOn_times not found for session: f9860a11-24d3-452e-ab95-39e199f20a93

trials.stimOn_times has been downloaded locally before Christmas break, but ONE cannot identify it or re-download it now.

For multiple sessions (for example, 'd33baf74-263c-4b37-a0d0-b79dcb80a764'), there is also the problem of load Clusters (channel locations, etc )data via ONE.

**Comment by rossant** [comment]
Don't know if that's the issue, but the server URL has changed to https. Make sure the following URL is found in your parameter file:

` "HTTP_DATA_SERVER": "https://ibl.flatironinstitute.org",` 

Your parameter file is in:
Linux ~/.one_params
Windows C:\Users\CurrentUser\AppData\Roaming\.one_params
Mac /Users/CurrentUser/.one_params

**Comment by yanliangshi** [comment]
Yeah, I have changed 
HTTP_DATA_SERVER to ''https'' using the commands:
from oneibl.one import OneAlyx
OneAlyx.setup()

but I find these issues after this change. For some session eid, the ONE code works, but not for the other sessions.

**Comment by mayofaulkner** [comment]
For the first error it looks like the data was patched yesterday which may have led to the problem. If you run the same code again do you still get the error?

For the second issue could you specify a few more details. What code you are using to read in the clusters and what is the error message that is given. Thank you!

**Comment by yanliangshi** [comment]
Thank you, Mayo! Yes, the first error disappears today.

For the second issue, 'load_channel_locations' in brainbox report error
Example, 
eid='49e0ab27-827a-4c91-bcaa-97eea27a1b8d'

spikes, clusters, channels = bbone.load_spike_sorting_with_channel(eid, one=one)

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-39-12e09103c503> in <module>
----> 1 spikes, clusters, channels = bbone.load_spike_sorting_with_channel(eid, one=one)

~/Works/int-brain-lab/ibllib/brainbox/io/one.py in load_spike_sorting_with_channel(eid, one, probe, dataset_types, aligned, force)
    352                                                  dataset_types=dataset_types, force=force)
    353     # -- Get brain regions and assign to clusters
--> 354     channels = load_channel_locations(eid, one=one, probe=probe, aligned=aligned)
    355 
    356     dic_clus = merge_clusters_channels(dic_clus, channels, keys_to_add_extra=None)

~/Works/int-brain-lab/ibllib/brainbox/io/one.py in load_channel_locations(eid, one, probe, aligned)
     95                 chans = one.load_object(eid, 'channels', collection=f'alf/{label}')
     96                 channels[label] = Bunch({
---> 97                     'atlas_id': chans['brainLocationIds_ccf_2017'],
     98                     'acronym': r.get(chans['brainLocationIds_ccf_2017'])['acronym'],
     99                     'x': chans['mlapdv'][:, 0] / 1e6,

KeyError: 'brainLocationIds_ccf_2017'

**Comment by mayofaulkner** [comment]
So it looks like the error is occurring because it was not loading the clusters.metrics file in correctly due to duplicate versions of this file (clusters.metrics.csv and clusters.metrics.pqt) . I have updated the code so it now deletes the older .csv type if it finds it on your local computer. See commit c8c89de2a5e567987cf1b35bd40860adcb968c57.

Could you pull the latest changed from ibllib develop and try running the code again.

Thanks

**Comment by yanliangshi** [comment]
Hi Mayo, I have pulled the changes, but it still reports the same error.

2021-01-06 10:48:53.113 INFO     [one.py:250] Did not find local files for spikes and clusters for /Users/yanliangshi/Document/Project/IBL/FlatIron/zadorlab/Subjects/CSH_ZAD_019/2020-08-18/001 and probe00. Downloading....
Downloading: /Users/yanliangshi/Document/Project/IBL/FlatIron/zadorlab/Subjects/CSH_ZAD_019/2020-08-18/001/alf/probe01/clusters.metrics.2f3e21ec-cdfd-414a-91ef-7766d7e5ae34.pqt Bytes: 61375
Downloading: /Users/yanliangshi/Document/Project/IBL/FlatIron/zadorlab/Subjects/CSH_ZAD_019/2020-08-18/001/alf/probe00/clusters.metrics.2cd00375-f385-4dff-ba83-4ff9efa654a9.pqt Bytes: 52329
2021-01-06 10:48:56.354 INFO     [one.py:267] Local files for spikes and clusters for /Users/yanliangshi/Document/Project/IBL/FlatIron/zadorlab/Subjects/CSH_ZAD_019/2020-08-18/001 and probe01 found. To re-download set force=True
 |████████████████████████████████████████████████████████████████████████████████████████████████████| 100.0% 
2021-01-06 10:48:56.731 INFO     [one.py:92] Channel locations for probe00 have been resolved. Channel and cluster locations obtained from ephys aligned histology track.
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-7-12e09103c503> in <module>
----> 1 spikes, clusters, channels = bbone.load_spike_sorting_with_channel(eid, one=one)

~/Works/int-brain-lab/ibllib/brainbox/io/one.py in load_spike_sorting_with_channel(eid, one, probe, dataset_types, aligned, force)
    361                                                  dataset_types=dataset_types, force=force)
    362     # -- Get brain regions and assign to clusters
--> 363     channels = load_channel_locations(eid, one=one, probe=probe, aligned=aligned)
    364 
    365     dic_clus = merge_clusters_channels(dic_clus, channels, keys_to_add_extra=None)

~/Works/int-brain-lab/ibllib/brainbox/io/one.py in load_channel_locations(eid, one, probe, aligned)
     96                 chans = one.load_object(eid, 'channels', collection=f'alf/{label}')
     97                 channels[label] = Bunch({
---> 98                     'atlas_id': chans['brainLocationIds_ccf_2017'],
     99                     'acronym': r.get(chans['brainLocationIds_ccf_2017'])['acronym'],
    100                     'x': chans['mlapdv'][:, 0] / 1e6,

KeyError: 'brainLocationIds_ccf_2017'

**Comment by mayofaulkner** [comment]
Hi, okay so the error came because the alignment had been resolved and the data was still in the process of being uploaded to the flatiron. 

The code should work now for this eid as the data has now been uploaded. I'll adapt the code to catch for these cases so it doesn't happen again in the future.

I'll close this issue for now but feel free to reopen if you run into further issues!

**Comment by yanliangshi** [comment]
Thank you very much!
