### ISSUE TITLE
VideoStreamer no longer works

### ISSUE THREAD

**Issue by k1o0** [int-brain-lab/iblenv#162]
It seems the VideoStreamer doesn't work since we migrated to the new server.  Perhaps it's an issue with the TLS?

```
from oneibl.stream import VideoStreamer
url = 'https://ibl.flatironinstitute.org/angelakilab/Subjects/NYU-32/2020-12-23/001/raw_video_data/_iblrig_leftCamera.raw.403de9f5-e2c9-4bda-ad10-e92076c0ea2c.mp4'
cap = VideoStreamer(video_path).cap
assert cap.isOpened(), f'Failed to open video file {video_path}'
```

**Comment by k1o0** [comment]
I see it's an easy fix: just changing the protocol in ONE.  Will patch now.

**Comment by k1o0** [comment]
Changing the URL prop getter doesn't solve the issue https://github.com/int-brain-lab/ibllib/commit/6d1bf5b782bfa7b85e0160015c54b8dd59c0d3a7

**Comment by k1o0** [comment]
It doesn't seem to be related to TLS:
```
url = 'https://www.sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4'
cap = cv2.VideoCapture(url)
assert cap.isOpened(), f'Failed to open video file {url}'
```

**Comment by k1o0** [comment]
Some of these failures are intermittent, for example Gaelle and I have had issues with this video, however it does work some of the time:
```
eid = '917dae01-b697-4fd4-a444-70bfa0cb241d'
dataset = '_iblrig_leftCamera.raw.mp4'
```

**Comment by GaelleChapuis** [comment]
It has worked for me over the last week so I will close this for now, feel free to re-open.
