### ISSUE TITLE
[Bug report] - No data available on alignment GUI whilst ephys data on database

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#164]
**Describe the bug**
Fei had an issue loading in the alignment GUI the data for insertion `f26a6ab1-7e37-4f8d-bb50-295c056e1062` (but it seems like both the raw ephys and KS2 data are on the database).
Could someone check why this occurs?

**Comment by mayofaulkner** [comment]
There was a dimension mismatch error between `spikes.times` and other `spikes` alf objects. I have removed the faulty `spikes.times` dataset and rerun the extraction. Will check tomorrow to make sure the correct data has been uploaded to flatiron

**Comment by mayofaulkner** [comment]
Data has all been patched and I am able to load in data as expected into the alignment GUI. I will close but feel free to reopen if you have problems.
