### ISSUE TITLE
[Bug report] - Qt platform fails to init

### ISSUE THREAD

**Issue by k1o0** [int-brain-lab/iblenv#166]
**Describe the bug**
I get a python error (an error dialog) saying 'This application failed to start because no Qt platform plugin could be initialized.  Reinstalling the application may fix this problem.'

**To Reproduce**
Importing any module causes this issue, e.g. `import alf.io`.  I reinstalled Anaconda from scratch and reinstalled iblenv.  Here are the Qt modules:
```
PyQt5==5.12.3
PyQt5-sip==4.19.18
PyQtChart==5.12
pyqtgraph @ file:///tmp/build/80754af9/pyqtgraph_1594064840332/work
PyQtWebEngine==5.12.1
[...]
qtconsole @ file:///tmp/build/80754af9/qtconsole_1600870028330/work
QtPy==1.9.0
```

**Comment by nbonacchi** [comment]
Don't know if this helps, everything seems to match with my env:

```
PyQt5==5.12.3
PyQt5-sip==4.19.18
PyQtChart==5.12
pyqtgraph @ file:///tmp/build/80754af9/pyqtgraph_1594064840332/work
PyQtWebEngine==5.12.1
[...]
QtAwesome @ file:///tmp/build/80754af9/qtawesome_1602272867890/work
qtconsole @ file:///tmp/build/80754af9/qtconsole_1600870028330/work
QtPy==1.9.0
```
Maybe it's not a python thing but a windows thing?

**Comment by k1o0** [comment]
I figured out the issue.  The error I got is the following:
```
qt.qpa.plugin: Could not load the Qt platform plugin "windows" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: direct2d, minimal, offscreen, windows, webgl.
```
Contrary to what Olivier says, Qt is necessary in order to use ibllib.  It's not clear to me what uses it, but importing anything from oneibl or alf triggers a switch to Qt5Agg.

The dependencies are all fulfilled:
```
pyqt                      5.12.3           py38haa244fe_7    conda-forge
pyqt-impl                 5.12.3           py38h885f38d_7    conda-forge
pyqt5-sip                 4.19.18          py38h885f38d_7    conda-forge
pyqtchart                 5.12             py38h885f38d_7    conda-forge
pyqtgraph                 0.11.0                     py_0
pyqtwebengine             5.12.1           py38h885f38d_7    conda-forge
[...]
qt                        5.12.9               h5909a2a_3    conda-forge
qtconsole                 4.7.7                      py_0
qtpy                      1.9.0                      py_0
```

The plugin is not found in iblenv, but is available in the base environment:
```
(iblenv) C:\Users\Miles\Documents\GitHub\ibl>where Qt5Core.dll
INFO: Could not find files for the given pattern(s).

(iblenv) C:\Users\Miles\Documents\GitHub\ibl>conda deactivate

(base) C:\Users\Miles\Documents\GitHub\ibl>where Qt5Core.dll
C:\Users\Miles\anaconda3\Library\bin\Qt5Core.dll
```

I had a look at my system variables and `QT_PLUGIN_PATH` that's set to `C:\Users\Miles\Anaconda3\Library\plugins`.  I changed this to `C:\Users\Miles\anaconda3\Library\bin\Qt5Core.dll` and restarted the computer.  Fix'd!
