### ISSUE TITLE
[Bug report] - Cannot stream video file, but video QC has run previously

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#169]
**Describe the bug**
I cannot stream the video file for a given session using the streamer - however, the QC has run on the video (cf Alyx https://alyx.internationalbrainlab.org/admin/actions/ephyssession/917dae01-b697-4fd4-a444-70bfa0cb241d/change/ ), so the data should be available ?

**To Reproduce**
```
eid = '917dae01-b697-4fd4-a444-70bfa0cb241d'
dataset = '_iblrig_leftCamera.raw.mp4'
dset = one.alyx.rest('datasets', 'list', session=eid, name=dataset,
                                 django='file_records__exists,True')
vs = VideoStreamer(dset[0])
```

error:
```
OpenCV: Couldn't read video stream from file "https://ibl.flatironinstitute.org/angelakilab/Subjects/NYU-32/2020-12-23/001/raw_video_data/_iblrig_leftCamera.raw.403de9f5-e2c9-4bda-ad10-e92076c0ea2c.mp4"
```

**Comment by GaelleChapuis** [comment]
Is this potentially due to changing FI to https:// ?

**Comment by k1o0** [comment]
https://github.com/int-brain-lab/iblenv/issues/162
