### ISSUE TITLE
[Usage question] - How to return value of a specific field in JSON from Django query

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#170]
**Describe the question you have**
I would like to know the value of one of the filter I used in a query, for a particular test case. 
For example: I would like to get the value of `session__extended_qc__behavior`, given a specific `insertion eid`.
I tried `ins = one.alyx.rest('insertions', 'read', id=eid)` but this is not specific enough.

What is the correct nomenclature?

**Comment by rossant** [comment]
I don't think that's possible without implementing it server-side. We should think about what information we should add to some of the endpoints
