### ISSUE TITLE
[Bug report] - Wheel overshoots threshold

### ISSUE THREAD

**Issue by k1o0** [int-brain-lab/iblenv#172]
**Describe the bug**
Someone from the Latham lab found that the wheel overshoots on some trials.  In the below figure each line is wheel position in degrees between `trials.stimOn_times` and `trials.feedback_times`.  Clearly on three trials the wheel moves more than twice over the threshold.  Will update with the eid when I get it.
![Screenshot 2021-01-24 22230](https://user-images.githubusercontent.com/25670666/105642539-0c083500-5e93-11eb-8f95-69cc79259ebf.png)

**Comment by nbonacchi** [comment]
This plot seems to imply that  ~15 wheel degrees correspond to 35 visual degrees, does this look correct?

**Comment by k1o0** [comment]
The majority of the lines are what we expect: ~0.3 radians to threshold.  This is from `2019-03-20_1_KS003`.  The wheel gain had already halved by then.  Those three long lines shouldn't have been possible.  For some reason the feedback looks extremely delayed.  I looked at the session but it's difficult to find the offending trials because lots of the trials have missing data.  I'll ask for more sessions and specific trial ids.

**Comment by nbonacchi** [comment]
Good idea, the rig code version also. We should try to find this in newer sessions to see if this issue still exists.

**Comment by k1o0** [comment]
Never got a response from her and it's an old session so I'm closing this
