### ISSUE TITLE
[Bug report] - Camera view is off during biasedCW session in ephys rig

### ISSUE THREAD

**Issue by guidomeijer** [int-brain-lab/iblenv#173]
When running a biasedChoiceWorld session in the ephys rig and using the command prepare_video_session.py --training, the Bonsai workflow that records the single camera does not show the visualizer of that camera. It can be turned on manually but because it's now a nested workflow that's not super intuitive.

**Comment by nbonacchi** [comment]
Should be fixed, please pull latest master of iblscripts...
Closing this, let me know if it's OK
