### ISSUE TITLE
[Bug report] - Empty extended QC field for ephys session (Cortex lab)

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#176]
**Describe the bug**
I am unsure whether this is normal, but this session
https://alyx.internationalbrainlab.org/admin/actions/ephyssession/572a95d1-39ca-42e1-8424-5c9ffcb2df87/change/?_changelist_filters=q%3Dks020
has an empty extended QC field.
I would have expected it to be filled at least by behavior and the task QC.

**Comment by GaelleChapuis** [comment]
Similar issue for this session https://alyx.internationalbrainlab.org/admin/actions/ephyssession/aad23144-0e52-4eac-80c5-c4ee2decb198/change/?_changelist_filters=q%3Dks023

**Comment by GaelleChapuis** [comment]
`sess_empty = one.alyx.rest('sessions', 'list', lab='cortexlab', project='ibl_neuropixel_brainwide_01', task_protocol='ephys', django='extended_qc__task__isnull,True,extended_qc__behavior__isnull,True')`
There are 44 sessions with the behavior/task extended QC fields empty (out of 64 when removing the Django query)

**Comment by oliche** [comment]
It seems most of them were not computed properly:

```
In [27]: ses = Session.objects.filter(extended_qc__isnull=True, project__name='ibl_neuropixel_brainwide_01', ta
    ...: sk_protocol__icontains='ephys')

In [28]: ses.count()
Out[28]: 118


angelakilab 33
churchlandlab 3
cortexlab 19
danlab 9
hoferlab 12
mainenlab 8
mrsicflogellab 9
wittenlab 23
zadorlab 2

```

**Comment by GaelleChapuis** [comment]
TODO: Look at EphysTrials extraction.
