### ISSUE TITLE
[Bug report] - Filter out tiny TTL pulses

### ISSUE THREAD

**Issue by alejandropan** [int-brain-lab/iblenv#177]
**Describe the bug**
F2TTL generates tiny pulses that confuse extractors. These pulses are not real they are shorter than real F2TLL events and hopefully could be filtered out.
This affects **many** of my recordings... (potentially catastrophic)
Example session" 73918ae1-e4fd-4c18-b132-00cb555b1ad2"
See below the noisy pulses (first image) vs the real pulses(second image). This problem generates a mislabelling of the noise pulse as the actual stim_on time (pink). 
![image](https://user-images.githubusercontent.com/26568907/106014393-72f03e80-608b-11eb-99c7-f108c541c0a1.png)
![image](https://user-images.githubusercontent.com/26568907/106014670-b0ed6280-608b-11eb-9e23-1e14ef776776.png)

**Comment by alejandropan** [comment]
What is the minimum pulse time for the F2TTL? I'd would be happy to amend the extractor to fix this if that would help

**Comment by alejandropan** [comment]
@nbonacchi @oliche The noise pulses appear to be 2ms. Am I correct to think that no F2TTL pulse can be that small?

**Comment by oliche** [comment]
Alex, what is the detection threshold of digital pulses on the probe ? Do you have any reason to think that the voltage from the frame2TTL is flirting with this value ?

Once we've fixed this thing, do you have a way to select the sessions affected looking at a specific QC value ?
This will also allow us to check that things were fixed on the re-run.

**Comment by alejandropan** [comment]
1) 3A detection threshold should be fine (5V). I think is a problem of calibration of the photodiode. My current hypothesis is that even within the same day (I calibrate the diode every week) if the screen is turned off the brightness might change enough to bring the old thresholds near the limit. From now on I'll calibrate before every single recording and see if this goes away. 
2) Yes, my sessions failing QC due to stimOn_trigger delays have this problem.

**Comment by oliche** [comment]
So I can fetch the sessions that fail `stimOn_trigger` and make sure they pass after our bit of magic right ?
And the idea is to disregard pulses less than 60Hz with a margin (let's say 10ms).

**Comment by alejandropan** [comment]
yep a good test would be the sessions from ibl_witten_27, where I know this problem is present.

**Comment by GaelleChapuis** [comment]
Implemented by @oliche ; removed only pulses of short latency with downward deflections. May need to run detection algorithm to check whether other sessions are affected and re-run extraction.
