### ISSUE TITLE
Spikesorting_KS2_Matlab task has uuid as software version

### ISSUE THREAD

**Issue by nbonacchi** [int-brain-lab/iblenv#182]
Session: d0ea3148-948d-4817-94f8-dcaf2342bbbe ZFM-01936/2021-01-19/001
 Tasks for this session --> [link](https://alyx.internationalbrainlab.org/admin/jobs/task/?q=d0ea3148-948d-4817-94f8-dcaf2342bbbe)
![image](https://user-images.githubusercontent.com/7206665/106602980-a0d6f680-6555-11eb-9c80-58ea54658ec7.png)

**Comment by oliche** [comment]
Yup, they don't have versioning  so I put the commit UUID
