### ISSUE TITLE
[Usage question] - How to open two instances of ONE() in Python

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#186]
**Describe the question you have**
I would like to connect to 2 databases (IBL Alyx and Cortexlab Alyx) within the same Python script.

Setting the credentials as per the guidelines https://int-brain-lab.github.io/iblenv/one_docs/one_credentials.html is a little cumbersome as it requires me to manually input the parameters.

Rather, I would like to have two one_params files `~/.one_params1 , ~/.one_params2` , and open two one instances within the same script, e.g. :
```
one=ONE(somevar=one_params) 
one2=ONE(somevar=one_params2)
```

Is this possible? What would be the correct nomenclature for instantiating ONE ?

**Is your question related to a specific product?**
ONE, Alyx

**Additional context**
Need to hit the cortexlab Alyx database as some metadata are not present on the IBL Alyx.

**Comment by mayofaulkner** [comment]
You would do like this
```
one1= ONE(username='test_user', password='testpassword',
          base_url='https://test.alyx.internationalbrainlab.org')
one2= ONE(username='mayo', password='mapassword',
          base_url='https://alyx.internationalbrainlab.org')
```

**Comment by rossant** [comment]
@mayofaulkner just curious, is there a way to do it via param files, to avoid putting clear text passwords in Python scripts?

**Comment by mayofaulkner** [comment]
Hmmm, doesn't look like this is supported at the moment based on this code (https://github.com/int-brain-lab/ibllib/blob/master/oneibl/one.py#L132). I guess we would need to add a params file argument here or something?

**Comment by rossant** [comment]
Okay I see. For now @GaelleChapuis  use Mayo's proposition but please make sure you don't commit your scripts with your password!
We'll see with @oliche and @nbonacchi what they think about adding a params file argument.

**Comment by GaelleChapuis** [comment]
Yes I won't commit !
But if my username and PW are the same across the 2 databases, I might be able to get away with just inputting the base_url, will try that (and in this case I can commit).

**Comment by rossant** [comment]
It's silly there's a simple solution actually :facepalm: just put your password in a text file and load it from Python..
```python
with open("~/.one_pwd", "r") as f:
     pwd = f.read()
```

**Comment by nbonacchi** [comment]
Sorry I'm late to this, the AlyxClient will use the default .one_params values for user passw and base_url if either is different it will create a new connection and use the "default" values from the param file if not provided so:
```python
one = ONE()
``` 
will use username passw and base_url from one_params but
```python
one = ONE(base_url='https://test.alyx.internationalbrainlab.org')
```
will use the one_params username and password but change the base_url)

**Comment by GaelleChapuis** [comment]
Thanks everyone, I should be able to get going - closing the issue !
