### ISSUE TITLE
[Usage question] - Value of insertion['json]['qc'] field when querying - str or int ?

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#187]
**Describe the question you have**
When doing queries, are the values in insertion > json > qc the same as for the session > qc field, i.e. :
```
    QC_CHOICES = [
        (50, 'CRITICAL',),
        (40, 'FAIL',),
        (30, 'WARNING',),
        (0, 'NOT_SET',),
        (10, 'PASS',),
    ]
```
?

In other terms, if I want to query insertions that are not marked as CRITICAL, should I use the django query
`~probe_insertion__json__qc__name__icontains,CRITICAL` or  `probe_insertion__json__qc__lt,50`

I could not find a QC description in experiments > models > ProbeInsertion

**Is your question related to a specific product?**
Alyx, ONE

**Comment by k1o0** [comment]
It appears to be stored as a string, not  an int: https://github.com/int-brain-lab/ibllib/blob/a6b597592a73a3ce8ddaf84d6daffdee21cf737a/ibllib/qc/alignment_qc.py#L344-L348

Re-open if needed.
