### ISSUE TITLE
[Usage question] -how to extract data on local computer with other protocol than original ibltasks_CH

### ISSUE THREAD

**Issue by karolinasocha** [int-brain-lab/iblenv#19]
**Describe the question you have**
Some of us will modify protocols for individual projects. How should I run on the local computer the extractor for behavioral data that creates alf files? This data does not have to be uploaded to FlatIron, 

For example, I created a new protocol that it is called: ibltasks_myprojectChoiceWorld; That protocol was a little bit modified from biasedChoiceWorld. 

After the training I would like to generate alf files for that protocol, and for that I would like to modify extractor to get variables that are important. I wish to modify extractor for my individual needs and run on local computer.

**Comment by nbonacchi** [comment]
The extent of the changed from biasedCW will determine if the extraction will run or not... if you just added some variables, maybe an output or input you should be able to run the extractors and add an extra extractor for your particular data. 

All the extractors can be found on ibllib.io.extractors and are all session_path based so it should be more or less straightforward to run them locally, that's what the local servers are doing and what the QC is doing on the rigs also :)
