### ISSUE TITLE
[Feature request] - Add identifier into WARNING message (trial data download)

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#193]
**Is your feature request related to a problem? Please describe.**
When downloading trial data, I received this warning:

```
2021-02-11 14:27:34.564 WARNING  [io.py:303] Inconsistent dimensions for object:trials
(573, 2),    intervals_bpod
(573,),    firstMovement_times
(573,),    contrastLeft
(573,),    probabilityLeft
(573,),    stimOn_times
(573,),    choice
(573,),    stimOff_times
(573,),    rewardVolume
(561,),    itiDuration
(573, 2),    intervals
(573,),    goCue_times
(573,),    feedbackType
(573,),    response_times
(573,),    feedback_times
(573,),    goCueTrigger_times
(573,),    contrastRight
```
I do this download for multiple sessions in a loop.
Based on what I print, I reckon this error comes from session ID `6527e2f1-8b2b-4b9b-a9dd-2a0206603ad8`.
However, it would be best not to depend on the user printing such information, but to have it directly into the warning message.

**Describe the solution you'd like**
My feature request is: would it be possible to put the session ID (or any other kind of identifiers, e.g. dataset ID) into the Warning message ? This would ease to identify problems when running analysis recursively.

**Comment by k1o0** [comment]
If you're looping over a session it's a good idea in general to identify the session at the top of the loop.  This makes the log a lot cleaner.  Otherwise we'd have to add the eid to all log entries.  Note that some functions don't have access to the session eid.  I agree that if in a function itself it uses multiple sessions then that function should id the session.

**Comment by k1o0** [comment]
I'm closing this for now but if you want you can re-open as a more general discussion about handling logs in general.
