### ISSUE TITLE
[Bug report] - Unable to use alf.io.load_object

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#196]
**Describe the bug**
This code snippet bugs on my machine:
```
import alf.io
from oneibl.one import ONE
one = ONE()
video_type='left'
eid='28741f91-c837-4147-939e-918d38d849f2'
alf_path = one.path_from_eid(eid) / 'alf'
cam0 = alf.io.load_object(
        alf_path,
        object='%sCamera' % video_type,
        namespace='ibl')
```

Error:
```
ibllib.exceptions.ALFObjectNotFound: No object "leftCamera"  found in /Users/gaelle/Downloads/FlatIron/churchlandlab/Subjects/CSHL058/2020-07-11/003/alf 
 The ALF object was not found.  This may occur if the object or namespace or incorrectly formatted e.g. the object "_ibl_trials.intervals.npy" would be found with the filters `object="trials", namespace="ibl"` 
```
ibllib is on the latest develop branch; running on Mac OS. 
The data is on Flatiron (manually checked).

This code works for @mschart ; shall I be updating something else than the ibllib repository?

**Comment by rossant** [comment]
What do you see in `/Users/gaelle/Downloads/FlatIron/churchlandlab/Subjects/CSHL058/2020-07-11/003/alf ` ?

**Comment by GaelleChapuis** [comment]
I see no folder `CSHL058` ! [which may make sense since the load does not execute?]
<img width="612" alt="Capture d’écran 2021-02-15 à 13 37 46" src="https://user-images.githubusercontent.com/43007596/107947698-08983300-6f93-11eb-860c-b21c44cecb12.png">

**Comment by GaelleChapuis** [comment]
I guess I am using the alf function wrongly then - assuming it would download the data from FI if it is not locally present. Should I use one.load or so to download the data first ?

**Comment by rossant** [comment]
> Should I use one.load or so to download the data first ?

Yes try that to see if it fails too

**Comment by GaelleChapuis** [comment]
`one.load_object(eid, obj='%sCamera' % video_type, collection='alf')` worked, then this
```
cam0 = alf.io.load_object(
        alf_path,
        object='%sCamera' % video_type,
        namespace='ibl')
```
also worked.
It might be worth adding a call within` alf.io.load_object` to the `one.load_object` function in case the data is not locally present ?
Closing the issue.

**Comment by rossant** [comment]
> It might be worth adding a call within alf.io.load_object to the one.load_object 

Makes sense to me, what do others think? @nbonacchi @k1o0 @oliche

**Comment by mschart** [comment]
`one.load(eid, dataset_types = ['camera.dlc', 'camera.times'])` before it does work. Alternatively, something like `cam = one.load_object(eid, 'camera')` as it works already for 'wheel' would be useful.
