### ISSUE TITLE
[Bug report] - Failure to download trials object

### ISSUE THREAD

**Issue by cmlangdon** [int-brain-lab/iblenv#199]
**Describe the bug**
I receive 'AssertionError: failed to download object' when trying to load trials for some eids.

**To Reproduce**
1. eid="bb6a5aae-2431-401d-8f6a-9fdd6de655a9"
2. trials = one.load_object(eid, obj='trials')

**Comment by k1o0** [comment]
The problem comes from this: 
`2021-02-23 12:53:10.819 WARNING  [one.py:745] alf\_ibl_trials.intervals_bpod.npy exist flag or url not found in Alyx`

We just need to add an `exists=True` to the filter in `one.load_object`.

**Comment by k1o0** [comment]
https://github.com/int-brain-lab/ibllib/commit/c0053cf698ee2d06026af62b109ea1c7bbb8fd09

I need to change the test database before I can open a PR and merge
