### ISSUE TITLE
[Bug report] - camera.timestamps inconsistent

### ISSUE THREAD

**Issue by k1o0** [int-brain-lab/iblenv#204]
**Describe the bug**
For some sessions the `_iblrig_leftCamera.timestamps.ssv` file contains frame timestamp integers in the first column, while the second column contains Bonsai system timestamps.  In other sessions the order of the columns is reversed.

**To Reproduce**
For example the session `b28556ce-4ef5-4157-9c00-68a1f74ae530` (zadorlab, ephys) the first three lines are:
```
2021-01-17T10:54:59.8866432-05:00 1698305077 
2021-01-17T10:54:59.9029120-05:00 1698850503 
2021-01-17T10:54:59.9195648-05:00 1699395840 
```

For the session `7082d576-4eb4-41dc-a16e-8a742829a83a` (angelakilab, training) the first three lines are:
```
28527295 2021-02-25T15:19:30.3394048-05:00 
30517920 2021-02-25T15:19:30.3475200-05:00 
31513241 2021-02-25T15:19:30.3484032-05:00 
```

**Expected behavior**
It seems to be a difference between training and ephys sessions.  If so, let's make sure all future training sessions follow the ephys format of (Bonsai, camera).

**Comment by nbonacchi** [comment]
closing in favor of int-brain-lab/iblrig#344
