### ISSUE TITLE
Ephys behavior file not transferring correctly to the server

### ISSUE THREAD

**Issue by noamroth** [int-brain-lab/iblenv#206]
I'm having trouble transferring behavior and ephys data from an experiment to the server. 
The behavior data, on my ephys rig's behavior computer,  is in Subjects\NR_0005\2021-03-02\002, but the transfer script is only transferring a previous session from that day (001, see below.) If I try again I just get that there is no data to transfer. 
```
(iblenv) C:\iblrig>python C:\iblrig\scripts\transfer_rig_data.py C:\iblrig_data\Subjects Y:\Subjects
2021-03-03 14:33:14.606 INFO     [transfer_rig_data.py:45] Copying C:\iblrig_data\Subjects\NR_0005\2021-03-02\001...
2021-03-03 14:36:40.854 INFO     [transfer_rig_data.py:52] Copied to Y:\Subjects: Session C:\iblrig_data\Subjects\NR_0005\2021-03-02\001

(iblenv) C:\iblrig>python C:\iblrig\scripts\transfer_rig_data.py C:\iblrig_data\Subjects Y:\Subjects
2021-03-03 15:09:59.363 INFO     [transfer_rig_data.py:25] Nothing to transfer, exiting...

```

Based on some responses to a similar problem a while ago I found on slack, I added a transfer_me.flag file (even though the instructions say to do this on the ephys computer but not the behavior computer?). When I do that, I get the following error:  

```
(iblenv) C:\iblrig>python C:\iblrig\scripts\transfer_rig_data.py C:\iblrig_data\Subjects Y:\Subjects
2021-03-03 15:13:36.597 INFO     [transfer_rig_data.py:45] Copying C:\iblrig_data\Subjects\NR_0005\2021-03-02\002...
2021-03-03 15:13:36.820 WARNING  [raw_data_loaders.py:569] C:\iblrig_data\Subjects\NR_0005\2021-03-02\002 No extractors were found for None ChoiceWorld
2021-03-03 15:13:36.823 INFO     [transfer_rig_data.py:52] Copied to Y:\Subjects: Session C:\iblrig_data\Subjects\NR_0005\2021-03-02\002

```

The behavior I ran was ephysChoiceWorld_testing, so I'm also not sure why it is labeling it as "None ChoiceWorld".

**Comment by GaelleChapuis** [comment]
@nbonacchi is there something special about the protocol `ephysChoiceWorld_testing` that prevent its transfer?

**Comment by nbonacchi** [comment]
For what I understand **session 001** is the behavior part of an ephys session and the **session 002** is the passive part. The transfer script looks for extractors but passiveCW has no extractor associated to it as a stand alone. 

The **raw_behavior_data** folder in a passive session has to be **renamed** to **raw_passive_data** and **moved** to its corresponding ephys session folder, in thei case **session 001**. 

Usually the rig has a `move_passive.py` script that is called at the end of the passive protocol that renames and moves the folder to it's correct location. It looks like it did not run? Did it crash?

On the Behavior computer there are several tasks that have to run after the session finishes:
- a cleanup command (not important)
- a poop command, asking for poop count
- a stop command to Bonsai for the stimulus
- a stop command to Bonsai for the mic recording
- a Bpod command to turn the LED indicators back ON
- a move passive command that finds the passive_data_for_ephys.flag file and moves and renames the folder for you 

All of this is prior to the transfer command.

(@GaelleChapuis you can use this as the description of what to do to move the files manually if you want) 

Now that you've already transferred to the **server** you can run the **scan_fix_passive_files.py** script in **iblscripts/deploy/serverpc/utils** 
```shell
conda activate iblenv
python scan_fix_passive_files.py /mns/s0/Data --dry
```
this will tell you how many sessions it finds to be moved and their paths, if everything looks OK you can run:
`python scan_fix_passive_files.py /mnt/s0/Data`
