### ISSUE TITLE
[Usage question] - Service Unavailable

### ISSUE THREAD

**Issue by csmfindling** [int-brain-lab/iblenv#209]
Hello,

I am getting this error this morning when making a call to the API. Is the problem on my side? the code seemed to work well yesterday.

Thanks

![Screenshot 2021-03-08 at 10 42 46](https://user-images.githubusercontent.com/2727497/110303790-1b82ae00-7ffb-11eb-81a1-cad4e7b40112.png)

**Comment by rossant** [comment]
I also have random HTTP errors at the moment on the alyx admin, I'll investigate, but in the meantime try again after a few minutes

**Comment by csmfindling** [comment]
Great thanks! thanks for your prompt reply. 
I'll go get a coffee then, I'll try later. Just in case it could be of need, I put here the logs of the HTTP error I get.

![Uploading Screenshot 2021-03-08 at 10.52.35.png…]()

**Comment by csmfindling** [comment]
I see the issue here is still open. 
For information, the calls pass on my side!
Thanks!!
