### ISSUE TITLE
[Usage question] - How to get the brain regions after Ephys-histology alignment is done

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#21]
**Describe the question you have**
Once the alignment between the histology and ephys data is made (using the GUI referenced below), how can one access the newly assigned brain regions to clusters and channels? Can this be retrieved via ONE?
In case when multiple alignments are done on a given ephys session, how does the query handle the return of the brain regions? (e.g. does it return only the brain regions of the latest alignment done?)

**Is your question related to a specific product?**
https://github.com/int-brain-lab/iblapps/tree/develop/atlaselectrophysiology

**Additional context**
None

**Comment by mayofaulkner** [comment]
The channels can be accessed in the following way,

```
eid = '2d5f6d81-38c4-4bdc-ac3c-302ea4d5f46e'
probe_label = 'probe00'
trajectory = one.alyx.rest('trajectories', 'list', provenance='Ephys aligned histology track',
                            session=eid, probe=probe_label)

probe_id = trajectory[0]['probe_insertion']
channels = one.alyx.rest('channels', 'list', probe_insertion=probe_id)
```
In the case where multiple alignments are done on a given session, the channels obtained in this way via ONE are from the latest alignment performed.

Channels from previous alignments can be recomputed using the reference line info stored in the json field of the trajectory object. Examples code is [here](https://int-brain-lab.github.io/iblenv/notebooks_external/docs_find_previous_alignments.html)

**Comment by SebastianBruijns** [comment]
Hm, after executing the code snippet the channels variable is an <oneibl.webclient._PaginatedResponse object at 0x7f6b30dfd410>, which I can't really work with. Is this as intended?

**Comment by mayofaulkner** [comment]
The channels object returned is a list with each item in the list corresponding to one channel. It shows as a paginated-response as the list is too big to load in as one. 

You can extract the relevant info like this
```
from ibllib.atlas import regions_from_allen_csv
chans = {'atlas_id': np.array([ch['brain_region'] for ch in channels]),
         'x': np.array([ch['x'] for ch in channels]) / 1e6,
         'y': np.array([ch['y'] for ch in channels]) / 1e6,
         'z': np.array([ch['z'] for ch in channels]) / 1e6,
         'axial_um': np.array([ch['axial'] for ch in channels]),
         'lateral_um': np.array([ch['lateral'] for ch in channels])}

# To get acronym and description about each brain id
r = regions_from_allen_csv()
brain_regions = r.get(ids=chans['atlas_id'])
```

**Comment by SebastianBruijns** [comment]
That works, thanks so much Mayo
