### ISSUE TITLE
[Bug report] - Change extractor when sound TTL does not behave properly, so as to populate only trigger times?

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#210]
**Describe the bug**
The sound TTL did not come back down faster enough after the goCue tone ; as result the extractor is assigning the errorCue_times as the goCue_times.

I might be worth changing the extractor so the _triggertimes solely gets populated (_times is Nan) if this occurs?

session ID: 1538493d-226a-46f7-b428-59ce5f43f0f9

**To Reproduce**
Use task_qc viewer and look at example trials 238 or 123
<img width="963" alt="Capture d’écran 2021-03-12 à 14 49 28" src="https://user-images.githubusercontent.com/43007596/110949509-f9629600-8342-11eb-9ec1-2310d8c3aba1.png">
<img width="990" alt="Capture d’écran 2021-03-12 à 14 51 54" src="https://user-images.githubusercontent.com/43007596/110949520-fb2c5980-8342-11eb-916c-f13ee2227075.png">

**Comment by juhuntenburg** [comment]
@GaelleChapuis I lost track a bit of the status of this. Has it been looked at in the course of any of our task qc sessions?

**Comment by k1o0** [comment]
No response in ~1 month.  Closing for now.
