### ISSUE TITLE
Add raw_data_loader for _iblrig_RFMapStim.raw.bin file

### ISSUE THREAD

**Issue by nbonacchi** [int-brain-lab/iblenv#211]
Integrate [this](https://github.com/int-brain-lab/ibldevtools/blob/master/niccolo/2021-02-08_load_RFMapStim.raw.py) and write test!!

**Comment by mayofaulkner** [comment]
Added this as a brainbox.io.one function [here](https://github.com/int-brain-lab/ibllib/blob/develop/brainbox/io/one.py#L390)
