### ISSUE TITLE
rerun / set tasks to waiting using REST

### ISSUE THREAD

**Issue by oliche** [int-brain-lab/iblenv#215]
How to query for a given tasks and rerun them on the local server from REST
```
from oneibl.one import ONE
one = ONE()
tasks = one.alyx.rest('tasks', 'list', name='EphysDLC',
                      django="log__icontains,TimeoutError: [Errno 110]")
print(len(tasks))
for t in tasks:
    one.alyx.rest('tasks', 'partial_update', id=t['id'], data={'log': "", 'status': 'Waiting'})
```

**Comment by GaelleChapuis** [comment]
Example query to get the spike sorting job of a specific session:

tasks = one.alyx.rest('tasks', 'list', name='SpikeSorting_KS2_Matlab',
                      session='7af49c00-63dd-4fed-b2e0-1b3bd945b20b')
