### ISSUE TITLE
[Bug report] - Brain region labels not being displayed in ephys-alignment gui

### ISSUE THREAD

**Issue by jshaker6** [int-brain-lab/iblenv#217]
**Describe the bug**
I am attempting to get the ephys-histology alignment GUI working using the sample data from [here](https://docs.google.com/document/d/1SxHeAekGs70WWX9abtDR-92-7-DiINbZDxOzTluxt-c/edit). Once I open the data folder in the GUI and get data, everything seems to look fine except that there are no brain region labels in the histology figure (figure 2). Interestingly, if I hover over a region and press Shift+I, it will show the correct highlighted brain region in the structure tree. So, I think the problem has something to do with display.

**Screenshots**
![ephys_alignmentgui_problem](https://user-images.githubusercontent.com/62961019/114253241-4ba4d000-995e-11eb-8a6b-c0a3e86e99c5.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10 version 20H2
 - Browser: Chrome

**Comment by mayofaulkner** [comment]
Hi, please could you try the following in a conda terminal
```
conda activate iblenv
pip uninstall pyqtgraph
pip install pyqtgraph==0.11.0
```

**Comment by jshaker6** [comment]
This worked - thank you!
