### ISSUE TITLE
[Usage question] - How to list all possible dataset types / names using one

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#218]
**Describe the question you have**
I would like to use ONE to list all of the pyBpod datasets types and names (rather than having to look at the sheet). Obviously, doing `one.alyx.rest('datasets', 'list') > unique` is not the right approach.
I am sure there is an `one.list()` command for this (I probably already asked 0:), but cannot find it back in the documentation).
Could someone write it here?

Thanks!

**Comment by rossant** [comment]
`one.list()` ?

**Comment by GaelleChapuis** [comment]
Right! 🤦 
one.list() returns dataset types. Is there a similar command that would return the unique dataset names? 
e.g. `_ibl_bodyCamera.times` and not just `camera.times` ?

**Comment by rossant** [comment]
For that I don't know of another method except doing the "unique" thing, but perhaps @k1o0 or someone else knows better?

**Comment by k1o0** [comment]
one.list will return the dataset names for a given experiment or a list of dataset types if no input is given.  There is no straightforward way to list all unique dataset names because there are very many.  You should do your search based on dataset types in this case.
