### ISSUE TITLE
[Usage question] - How to retrieve session with particular dataset name (not type)

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#219]
**Describe the question you have**
I would like to retrieve sessions that have a particular dataset *name* (not type). For example, I would like to query sessions that have the specific datasets `['_ibl_bodyCamera.times', '_ibl_rightCamera.times']`

As example: this query on the dataset types works, but is not precise enough for my use case (as there is e.g. 3 camera files englobed into 1 dataset type)
```
# Check on dataset types (not precise enough for this case)
dsets = ['camera.times']
sess = one.alyx.rest('sessions', 'list',
                     django=f'data_dataset_session_related__dataset_type__name__in,{dsets}')
```

I was hoping to use a query using the filter `session__dataset__name__in`, but it does not seem to work from ONE:
```
# Check on specific dataset
dsets = ['_ibl_bodyCamera.times']
sess = one.alyx.rest('sessions', 'list',
                     django=f'data_dataset_session_related__dataset__name__in,{dsets}')
```
error : `"Related Field got invalid lookup: dataset"`

Could anyone point me to the correct filter to use?
Thanks a million !

**Is your question related to a specific product?**
ONE

**Comment by rossant** [comment]
does this work? `data_dataset_session_related__name__in`

**Comment by GaelleChapuis** [comment]
The query returns an empty field:
```
dsets = ['_ibl_wheelMoved.intervals.npy']
sess = one.alyx.rest('sessions', 'list', django=f'data_dataset_session_related__name__in,{dsets}')
```
`sess=[]`
but there are clearly sessions with this dataset name, e.g.:
`datasets = one.alyx.rest('datasets', 'list', session='46794e05-3f6a-4d35-afb3-9165091a5a74')`
