### ISSUE TITLE
[Bug report] - Right camera times missing for trainingChoiceWorldWidefield6.4.2

### ISSUE THREAD

**Issue by k1o0** [int-brain-lab/iblenv#222]
**Describe the bug**
Camera timestamp extraction is failing because the `_iblrig_rightCamera.timestamps.ssv` dataset does not exist.  The right camera is there and the other datasets are present.  

**To Reproduce**
See registered datasets for [this session](https://alyx.internationalbrainlab.org/admin/actions/session/41ba7c62-2112-44d1-8227-308e70c54c66/change/) and the [corresponding extraction task](https://alyx.internationalbrainlab.org/admin/jobs/task/8d9af449-b1ff-4398-a01b-d8f88a03c304/change/)

Perhaps the dataset is not saved because you're using a slightly different Bonsai configuration, or maybe that dataset wasn't copied over from the video PC?

**Comment by cskrasniak** [comment]
I'm confused, that file appears to be present for the session linked above, I'm now rerunning the video compression as maybe the video data was not transferred quickly enough. When running many sessions a day sometimes it can be hard to get all of the video data transferred in a timely manner.

**Comment by k1o0** [comment]
OK the rerun worked. It's strange because the timestamps file is small so it should be transferred quicker than the video.  We'll see if it happens again

**Comment by cskrasniak** [comment]
It happens periodically that the transfer crashes with the error that the source files != the destination files.  When this happens I need to delete the `raw_video_data` folder  on the server PC and redo the transfer, so maybe the reason they were not the same is that this file was not transferred. My suspicion is that this happened here.
