### ISSUE TITLE
updating iblenv did not install numba

### ISSUE THREAD

**Issue by cskrasniak** [int-brain-lab/iblenv#228]
When running `conda env update --file iblenv.yaml --prune`  numba was not installed. upon trying to install with pip, there was a DLL install error. Uninstalling with pip then reinstalling with conda solved the problem

**Comment by k1o0** [comment]
What OS are you using?  I don't suppose you have the log output?

**Comment by mayofaulkner** [comment]
Looks like the following worked.
```
pip uninstall numba
conda install numba
```

Will close this now but feel free to reopen if you have more problems
