### ISSUE TITLE
GPIO data fails to load

### ISSUE THREAD

**Issue by k1o0** [int-brain-lab/iblenv#233]
For session `c7832bca-5cfb-4676-a1ec-f87cd7640ae5` the leftCamera.GPIO.bin file contains some suspect numbers.  There are 2315 unique numbers in the file but the code asserts there should be maximum 16:

https://github.com/int-brain-lab/ibllib/blob/9066c00a8e9a65a1d209144a2ac54d0b87bec0b3/ibllib/io/raw_data_loaders.py#L207-L208

I'm inclined to believe the assertion is wrong...

**Comment by nbonacchi** [comment]
That particular check should probably be done after the bitshift operations as there are multiple numbers that after being >> ## & 0x1 will yield a 1 or a 0.

**Comment by k1o0** [comment]
I've looked again at the code and I think the assertion is indeed valid.  I've only seen one session fail this assertion so far so I'm leaving it be.
