### ISSUE TITLE
[Feature request] - Accomodate recordings with less than 385 channels in the atlaseletrophysiology tool

### ISSUE THREAD

**Issue by LiuDaveLiu** [int-brain-lab/iblenv#24]
**Is your feature request related to a problem? Please describe.**
The current data extraction and plots in the GUI only accomodates recordings with 385 channels. This should be made flexible depending on the number of channels used in the recording.

**Describe the solution you'd like**
Example raw ephys and meta data for a recording with 302 channels is provide [here](https://www.dropbox.com/sh/4wcvjatz7fr9db7/AABkWHOS2nfuM-IOj88pJw7Ta?dl=0) to test the implementation. nSavedChans=302 in the .meta file.

**Describe alternatives you've considered**
N/A

**Additional context**
Current error when extracting from raw recordings with less than 385 channels

----> 1 extract_data(ks_path, ephys_path, out_path)
 
~/Desktop/int-brain-lab/iblapps/atlaselectrophysiology/extract_files.py in extract_data(ks_path, ephys_path, out_path)
    110             ks2_to_alf(ks_path, ephys_path, out_path, bin_file=efile.ap,
    111                        ampfactor=_sample2v(efile.ap), label=None, force=True)
--> 112             extract_rmsmap(efile.ap, out_folder=out_path, spectra=False)
    113         if efile.get('lf') and efile.lf.exists():
    114             extract_rmsmap(efile.lf, out_folder=out_path)
 
~/Desktop/int-brain-lab/iblapps/atlaselectrophysiology/extract_files.py in extract_rmsmap(fbin, out_folder, spectra)
     82 
     83     # crunch numbers
---> 84     rms = rmsmap(fbin, spectra=spectra)
     85     # output ALF files, single precision with the optional label as suffix before extension
     86     if not out_folder.exists():
 
~/Desktop/int-brain-lab/iblapps/atlaselectrophysiology/extract_files.py in rmsmap(fbin, spectra)
     40     # loop through the whole session
     41     for first, last in wingen.firstlast:
---> 42         D = sglx.read_samples(first_sample=first, last_sample=last)[0].transpose()
     43         # remove low frequency noise below 1 Hz
     44         D = dsp.hp(D, 1 / sglx.fs, [0, 1])
 
~/Desktop/int-brain-lab/ibllib-repo/ibllib/io/spikeglx.py in read_samples(self, first_sample, last_sample, channels)
    128         if channels is None:
    129             channels = slice(None)
--> 130         return self.read(slice(first_sample, last_sample), channels)
    131 
    132     def read_sync_digital(self, _slice=slice(0, 10000)):
 
~/Desktop/int-brain-lab/ibllib-repo/ibllib/io/spikeglx.py in read(self, nsel, csel, sync)
    109         """
    110         darray = np.float32(self._raw[nsel, csel])
--> 111         darray *= self.channel_conversion_sample2v[self.type][csel]
    112         if sync:
    113             return darray, self.read_sync(nsel)
 
ValueError: operands could not be broadcast together with shapes (131072,302) (385,) (131072,302)

**Comment by mayofaulkner** [comment]
Currently fixed if you use the `sglx_fix` branch of ibllib (https://github.com/int-brain-lab/ibllib/tree/sglx_fix)
