### ISSUE TITLE
AssertionError: Dataset _spikeglx_sync.channels not found

### ISSUE THREAD

**Issue by mschart** [int-brain-lab/iblenv#240]
```
from ibllib.qc.camera import run_all_qc
eid = '5386aba9-9b97-4557-abcd-abc2da66b863'
qcs = run_all_qc(eid, update=True)
```
`AssertionError: Dataset _spikeglx_sync.channels not found`

**Comment by juhuntenburg** [comment]
Cannot reproduce this locally, maybe data has been added in the meantime? Closing, please let me know if issue persists.
