### ISSUE TITLE
[Bug report] - Histology session coming up empty for Cortex lab mice

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#246]
**Describe the bug**
I cannot find the histology session from the cortex lab on the IBL Alyx via ONE.
Example:

```
subj = 'KS023'

histology = one.alyx.rest('sessions', 'list', subject=subj,
                              task_protocol='SWC_Histology_Serial2P_v0.0.1')
histology_exists = len(histology) == 1
```

`histology_exists` is `False`

But this mouse was imaged and there are even insertions that are aligned, e.g. KS023 2019-12-10 probe01:

```
subj = 'KS023'
date='2019-12-10'
probe='probe01'

align_trajectory = one.alyx.rest('trajectories', 'list', subject=subj, date=date, probe=probe,
                                 provenance='Ephys aligned histology track')
align_exists = len(align_trajectory) == 1
```

`align_exists` is `True`

**Expected behavior**
The query for histology should not come up empty.

**Comment by oliche** [comment]
Do we need to have histology sessions in Alyx @k1o0 ?

**Comment by oliche** [comment]
Fixed on alyx import.

To check on Alyx that it's all done 
```
from actions.models import Session
Session.objects.filter(task_protocol__startswith='SWC_Histology_Serial2P', lab__name='cortexlab').count()
```
