### ISSUE TITLE
Question about Dynamic Library of Flycap

### ISSUE THREAD

**Issue by srhaiken** [int-brain-lab/iblenv#247]
All of a sudden, the rig has stopped working;
Every time I go to run the experiment, the screen turns grey but there is no stimulus, and Bonsai reports one of two errors: 

(1) = "a procedure imported by "FlyCapture2Managed_v100.dll" could not be loaded"     OR
(2) = "Could not load file or assembly "FlyCapture2Managed_v100.dll"or one of its dependencies is not a valid Win32 application, (Exception from HRESULT:Ox300700C1). 

Do you have any thoughts on why this is happening and what I should do to fix it? 
Thank you so much

**Comment by nbonacchi** [comment]
Hi @srhaiken did you update your PC in any way?

**Comment by srhaiken** [comment]
> Hi @srhaiken did you update your PC in any way?

No I did not

**Comment by nbonacchi** [comment]
If you have not updated the rig code, Bonsai, or your PC in any way, I'm not sure I can help. 
On my side, we did not change anything. Is this still a problem?

From the 2 errors it looks like there is something wonky with the drivers maybe:
Have you tried reinstalling the FlyCap drivers (are they the correct version)? 
Are you using the Bonsai executable from the iblrig/Bonsai? Are all Bonsai packages installed properly?
Have you tried reinstalling Bonsai?

**Comment by k1o0** [comment]
No response in a month.  Closing for now.
