### ISSUE TITLE
[Bug report] - Transfer of ephys data cannot be run a second time if the first transfer failed

### ISSUE THREAD

**Issue by guidomeijer** [int-brain-lab/iblenv#250]
**Describe the bug**
When running the ephys transfer a number of files and folders are renamed and restructured and then the transfer starts. However, sometimes the transfer fails for whatever reason. Then when running the transfer again it throws an error because it expects the original file structure to be there but instead the restructuring was already done by the first transfer.

**To Reproduce**
1. Run transfer_ephys_session
2. Cancel it
3. Delete anything on the server that was transferred
4. Run it again

**Comment by nbonacchi** [comment]
Can you share the error message? So I can see at which point in the procedure the transfer complains?

Notes to self: 
- write a new test for rename_ephys _files input is an already renamed folder

**Comment by guidomeijer** [comment]
(iblenv) PS C:\iblscripts\deploy\ephyspc> python .\transfer_ephys_session.py
LOCAL: D:\iblrig_data\Subjects
REMOTE: \\iblserver.champalimaud.pt\ibldata\Subjects

Found session: D:\iblrig_data\Subjects\ZFM-02183\2021-07-21\001
Traceback (most recent call last):
  File ".\transfer_ephys_session.py", line 26, in <module>
    iblscripts_folder=iblscripts_folder)
  File "C:\Users\Admin\Anaconda3\envs\iblenv\lib\site-packages\ibllib\pipes\misc.py", line 254, in confirm_ephys_remote_folder
    rename_ephys_files(str(session_path))
  File "C:\Users\Admin\Anaconda3\envs\iblenv\lib\site-packages\ibllib\pipes\misc.py", line 421, in rename_ephys_files
    new_filename = get_new_filename(nidqf.name)
  File "C:\Users\Admin\Anaconda3\envs\iblenv\lib\site-packages\ibllib\pipes\misc.py", line 455, in get_new_filename
    return ".".join([root + gt, "nidq", ext])
UnboundLocalError: local variable 'ext' referenced before assignment

**Comment by mayofaulkner** [comment]
Is there a wiring.json file in the session path on your ephys computer. Can you try deleting that and launching the script again?

**Comment by guidomeijer** [comment]
Yes then it works!

**Comment by k1o0** [comment]
Issue seems resolved, so I'll go ahead and close
