### ISSUE TITLE
[Bug report] - Data Exploration GUI problem

### ISSUE THREAD

**Issue by Marsataheri** [int-brain-lab/iblenv#252]
I'm having trouble getting the new Data Exploration GUI to work. I followed the [instructions on Slack](https://int-brain-lab.slack.com/archives/C2FK1PTDE/p1626424030110800) (thanks @mayofaulkner for the very thorough and clear instructions!). However, none of the repeated site eids/pids I use work for me. For some I get the following error:

> `(iblenv) mt@Marsas-MacBook-Pro data_exploration_gui % python data_explore_gui.py -pid dab512bd-a02d-4c1f-8dbc-9155a163efc0
> (iblenv) mt@Marsas-MacBook-Pro data_exploration_gui % python data_explore_gui.py -pid e31b4e39-e350-47a9-aca4-72496d99ff2a
> Dimension mismatch between dlc points and timestamps
> Dimension mismatch between dlc points and timestamps
> Traceback (most recent call last):
>   File "/Users/mt/int-brain-lab/iblapps/data_exploration_gui/data_explore_gui.py", line 304, in <module>
>     mainapp = MainWindow(eid, probe, one=one, spike_collection=args.collection)
>   File "/Users/mt/int-brain-lab/iblapps/data_exploration_gui/data_explore_gui.py", line 91, in __init__
>     self.initialise_gui()
>   File "/Users/mt/int-brain-lab/iblapps/data_exploration_gui/data_explore_gui.py", line 121, in initialise_gui
>     self.cluster.populate(self.clust_data.ids, self.clust_data.colours_ks,
>   File "/Users/mt/int-brain-lab/iblapps/data_exploration_gui/cluster.py", line 75, in populate
>     icon = utils.get_icon(self.clust_colour_ibl[idx], self.clust_colour_ks[idx], 20)
>   File "/Users/mt/int-brain-lab/iblapps/data_exploration_gui/utils.py", line 251, in get_icon
>     p.fillRect(int(pix_size / 4), int(pix_size / 4), int(pix_size / 2),
> TypeError: arguments did not match any overloaded call:
>   fillRect(self, QRectF, Union[QBrush, QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'int'
>   fillRect(self, QRect, Union[QBrush, QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'int'
>   fillRect(self, int, int, int, int, Union[QBrush, QColor, Qt.GlobalColor, QGradient]): argument 5 has unexpected type 'NoneType'
>   fillRect(self, QRectF, Union[QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'int'
>   fillRect(self, QRect, Union[QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'int'
>   fillRect(self, int, int, int, int, Union[QColor, Qt.GlobalColor, QGradient]): argument 5 has unexpected type 'NoneType'
>   fillRect(self, int, int, int, int, Qt.GlobalColor): argument 5 has unexpected type 'NoneType'
>   fillRect(self, QRect, Qt.GlobalColor): argument 1 has unexpected type 'int'
>   fillRect(self, QRectF, Qt.GlobalColor): argument 1 has unexpected type 'int'
>   fillRect(self, int, int, int, int, Qt.BrushStyle): argument 5 has unexpected type 'NoneType'
>   fillRect(self, QRect, Qt.BrushStyle): argument 1 has unexpected type 'int'
>   fillRect(self, QRectF, Qt.BrushStyle): argument 1 has unexpected type 'int'
>   fillRect(self, int, int, int, int, QGradient.Preset): argument 5 has unexpected type 'NoneType'
>   fillRect(self, QRect, QGradient.Preset): argument 1 has unexpected type 'int'
>   fillRect(self, QRectF, QGradient.Preset): argument 1 has unexpected type 'int'`

For others, I just get the first two lines and then it seems to get frozen, e.g.,:

> `(iblenv) mt@Marsas-MacBook-Pro data_exploration_gui % python data_explore_gui.py -eid f312aaec-3b6f-44b3-86b4-3a0c119c0438 -name probe00
> Dimension mismatch between dlc points and timestamps
> Dimension mismatch between dlc points and timestamps`

And for some others, it just gets frozen from the start:

> `(iblenv) mt@Marsas-MacBook-Pro data_exploration_gui % python data_explore_gui.py -eid d23a44ef-1402-4ed7-97f5-47e9a7a504d9 -name probe00`

I'm using a MacbookPro, Big Sur version 11.4.

**Comment by mayofaulkner** [comment]
Please could you try running the following in your command line before launching to see if the gui appears 
`export QT_MAC_WANTS_LAYER=1`
