### ISSUE TITLE
for a session, one doesn't list dlc data although it's on flatiron; it does list motion energy

### ISSUE THREAD

**Issue by mschart** [int-brain-lab/iblenv#255]
For this session:

https://ibl.flatironinstitute.org/cortexlab/Subjects/KS005/2019-08-30/001/alf/
eid = '6756a3b4-5564-4005-93b5-f74b91f3e494'

when doing

`dsets = one.list_datasets(eid)`
`[x for x in dsets if 'pqt' in x]` is empty. Although there's motion energy - which required DLC to be computed. And there's DLC data on flatiron. Also for other sessions, this works:

Say eid = '15f742e1-1043-45c9-9504-f1e8a53c1744',
```
dsets = one.list_datasets(eid)
[x for x in dsets if 'pqt' in x] =
['alf/_ibl_bodyCamera.dlc.pqt',
 'alf/_ibl_leftCamera.dlc.pqt',
 'alf/_ibl_rightCamera.dlc.pqt',
 'alf/probe00/clusters.metrics.pqt',
 'alf/probe01/clusters.metrics.pqt']
```
So that's odd.

**Comment by k1o0** [comment]
The cache is now updated every 6 hours but by default the cache will only be downloaded once per day.  See [this guide](https://int-brain-lab.github.io/ONE/notebooks/one_modes.html#Refreshing-the-cache) on how to update your cache manually or more frequently.
