### ISSUE TITLE
Issue with loading ephys and histology aligned data onto the IBL ENV GUI

### ISSUE THREAD

**Issue by antaramaj16** [int-brain-lab/iblenv#257]
Hi,

I was trying to load my ephys and histology data into the ephys_alignment_GUI and I keep running into these same error messages:

![image](https://user-images.githubusercontent.com/74184866/133071439-4a30ce4e-94c0-4fcc-8c27-6867a5eccea2.png)

I double checked that all of the correct files are in the folder that I am trying to Get Data from:

![image](https://user-images.githubusercontent.com/74184866/133071566-4f1c6081-9fd7-4f93-876b-7d50b2a11538.png)

Would you be able to tell me if there is a certain file that is not being read correctly? Thank you!

Sincerely,
Antara

**Comment by mayofaulkner** [comment]
Hey, it looks as if the coordinates in your xyz_picks.json file may be outside of the atlas which is causing this issue. Could you let me know what process you used to get these values?

Many thanks!

**Comment by antaramaj16** [comment]
Hi, we are using the Allen CCF scripts to generate the xyz coordinate numbers and then we are converting these numbers to a useable format by using this script which we wrote:

![image](https://user-images.githubusercontent.com/74184866/133244180-cbdb4280-d770-4d01-bd1b-c7367e1be05e.png)

Normally this approach would work and the probe would show up in the brain atlas image cause I have done alignment for another session. But maybe we are not doing something correctly?

**Comment by mayofaulkner** [comment]
Hey, no that looks correct. Perhaps it is something to do with these particular coordinates. Is there any chance you could share the content of the xyz_picks.json and I can check what is going on locally. 

Thanks!

**Comment by antaramaj16** [comment]
Hi, yes here are the contents of this particular xyz_picks.json file for this session:
{"xyz_picks":[[-1270,2550,-4850],[-1280,2430,-4960],[-1320,2340,-5060],[-1230,2250,-5280],[-1280,2130,-5400],[-1230,2070,-6020]]}

**Comment by mayofaulkner** [comment]
Hello, I had a look and the problem was indeed that at some points the extended track that the GUI uses was going outside of the atlas which was causing problems. I have fixed the code so it accounts for these cases. You can find the fixed code in the latest develop branch of ibllib-repo and get it using the following (if you haven't updated iblapps recently you will probably need to pull the latest changes from this repo too)
```
conda activate iblenv
cd int-brain-lab\ibllib-repo
git checkout develop
git pull```

This is the location I got in the brain for your track. Just want to check that it looks correct to confirm the transformation from CCF to bregma went as expected
![location_of_xyz_picks](https://user-images.githubusercontent.com/11440465/133420461-4d8b23ef-890f-49a6-bc66-6ba81aca4a58.png)

**Comment by antaramaj16** [comment]
Hi, I did the updates for both and now when I try to load in the ephys_atlas-gui.py -o True it gives me these errors:
![image](https://user-images.githubusercontent.com/74184866/133491941-78abb0ce-5c0c-4d29-9b44-7af448eced1b.png)

How do I fix this? Thank you for helping with this issue though!

**Comment by antaramaj16** [comment]
So I did that and now these errors are showing up:

![image](https://user-images.githubusercontent.com/74184866/133585539-e5f3bc7f-70c8-4cc9-bcb4-8659768a7598.png)

**Comment by antaramaj16** [comment]
Thank you so much!! I was able to open the GUI and now the histology and ephys data are showing up on it as well:

![image](https://user-images.githubusercontent.com/74184866/133588631-2bcd8259-4cd9-4db7-b240-e65b33414c87.png)

I appreciate all your help!

**Comment by mayofaulkner** [comment]
Perfect! :) I'll close this issue now but don't hesitate to reach out again if you have other problems!
