### ISSUE TITLE
Issue with loading ephys and histology aligned data onto the IBL ENV GUI

### ISSUE THREAD

**Issue by antaramaj16** [int-brain-lab/iblenv#259]
Hi, Earlier this week I had the issue with the coordinates and it seems that I have run into a problem again:

![image](https://user-images.githubusercontent.com/74184866/133813918-1a29f93d-038c-4f7a-b5ed-0afc9a3cdc3d.png)

Here are the contents of the xyz_picks.json file : 
{"xyz_picks":[[930,2910,-2710],[910,2910,-2860],[930,2790,-2820],[890,2790,-3040],[950,2670,-3110],[830,2670,-3710],[1080,2550,-3290],[1000,2550,-3770],[1020,2430,-3840],[950,2430,-4190],[1100,2310,-4020],[1080,2310,-4270],[1230,2220,-4250],[1200,2220,-4640],[1300,2100,-4670],[1360,1980,-5070],[1550,1860,-5650],[2190,1740,-7070],[2070,1620,-7430],[1710,1500,-6610],[1920,1410,-7540],[1510,1320,-7470],[1940,1200,-7940]]}

and we noticed that the probe was sticking out of the brain after aligning on the Allen CCF 3d brain view. However, our probe didn't come out of the bottom of the brain during the recording - I just think that there may have been a scaling issue with the Allen CCF script resulting in this weird output.

**Comment by mayofaulkner** [comment]
Could you try using these [functions](https://github.com/int-brain-lab/iblapps/wiki/4.-Preparing-data-for-ephys-GUI) (xyz2ccf and ccf2xyz) to confirm that the conversion you are doing in your matlab file from CCF to the bregma space is correct.

**Comment by mayofaulkner** [comment]
Also I have noticed that you tracing is very jagged, was this intended?
![insertion_location](https://user-images.githubusercontent.com/11440465/133974241-10371850-191e-4de1-a98d-31af45bde7a8.png)

**Comment by k1o0** [comment]
No response in almost a month, closing for now.
