### ISSUE TITLE
Is the highest channel index for the ephysData.raw.lf deepest in the brain or the other way around? 

### ISSUE THREAD

**Issue by mschart** [int-brain-lab/iblenv#26]
Is the highest channel index for the ephysData.raw.lf deepest in the brain or the other way around? I.e. there are indices 0 to 384, how was counted?

**Comment by nsteinme** [comment]
Standard for neuropixels in general is 0=deepest, i.e. counting starting at
the tip. I'm not 100% sure about this dataset specifically but I'd be
surprised if it were reversed from that.

**Comment by mayofaulkner** [comment]
You can find the exact location of each channel on the probe from the `channels.localCoordinates` dataset type. The first dimension (x in um) is the position on the width of the shank and the second dimension (y) is the depth along the shank where 20 um corresponds to the deepest site.

You will first need to index ephysData.raw.lf by the channel map stored in `channels.rawInd` as ~10 or so channels out of the 384 are not recording channels. For example,

```
chn_coords = one.load(eid, dataset_types=['channels.localCoordinates'])[0]
chn_map = one.load(eid, dataset_types=['channels.rawInd'])[0]
lf = ephysData.raw.lf[chn_map, :]

assert(chn_coords.shape[0] == lf.shape[0])
```
