### ISSUE TITLE
Unable to open IBL ENV GUI

### ISSUE THREAD

**Issue by anitamrominto** [int-brain-lab/iblenv#262]
Hi,
I was trying to open the ephys_alignment_GUI but I keep running in this error
![image (22)](https://user-images.githubusercontent.com/87716692/134900788-144f0507-82fb-4765-94e7-857eef366fa6.png)

Would you be able to help me fix it?

**Comment by mayofaulkner** [comment]
Hello, please could you try the following

```
conda activate iblenv
pip uninstall globus-sdk
pip install globus-sdk==2.0.1
```

**Comment by anitamrominto** [comment]
It worked! Thank you so much!
