### ISSUE TITLE
OSError: NotImplemented: Support for codec 'snappy' not built

### ISSUE THREAD

**Issue by oluwafemi2016** [int-brain-lab/iblenv#264]
I am having issues reading the parquet file into Jupyter notebook. I have tried to sort out the problem but don't know what to do. I followed the suggestion of uninstalling and re-installing pyarrows but the issue persists. Below is the error message I received. Any suggestion. Thanks

OSError Traceback (most recent call last)
in
----> 1 raw_data = pd.read_parquet(DATAFILE_PATH, engine='auto')

~\anaconda3\lib\site-packages\pandas\io\parquet.py in read_parquet(path, engine, columns, use_nullable_dtypes, **kwargs)
457 """
458 impl = get_engine(engine)
--> 459 return impl.read(
460 path, columns=columns, use_nullable_dtypes=use_nullable_dtypes, **kwargs
461 )

~\anaconda3\lib\site-packages\pandas\io\parquet.py in read(self, path, columns, use_nullable_dtypes, storage_options, **kwargs)
219 )
220 try:
--> 221 return self.api.parquet.read_table(
222 path_or_handle, columns=columns, **kwargs
223 ).to_pandas(**to_pandas_kwargs)

~\anaconda3\lib\site-packages\pyarrow\parquet.py in read_table(source, columns, use_threads, metadata, use_pandas_metadata, memory_map, read_dictionary, filesystem, filters, buffer_size, partitioning, use_legacy_dataset, ignore_prefixes)
1729 memory_map=memory_map, buffer_size=buffer_size)
1730
-> 1731 return dataset.read(columns=columns, use_threads=use_threads,
1732 use_pandas_metadata=use_pandas_metadata)
1733

~\anaconda3\lib\site-packages\pyarrow\parquet.py in read(self, columns, use_threads, use_pandas_metadata)
1606 use_threads = False
1607
-> 1608 table = self._dataset.to_table(
1609 columns=columns, filter=self._filter_expression,
1610 use_threads=use_threads

~\anaconda3\lib\site-packages\pyarrow_dataset.pyx in pyarrow._dataset.Dataset.to_table()

~\anaconda3\lib\site-packages\pyarrow_dataset.pyx in pyarrow._dataset.Scanner.to_table()

~\anaconda3\lib\site-packages\pyarrow\error.pxi in pyarrow.lib.pyarrow_internal_check_status()

~\anaconda3\lib\site-packages\pyarrow\error.pxi in pyarrow.lib.check_status()

OSError: NotImplemented: Support for codec 'snappy' not built

**Comment by k1o0** [comment]
Hi I re-opened issue https://github.com/int-brain-lab/iblenv/issues/212.  Could you please reply to my message there?
