### ISSUE TITLE
Bonsai Crash

### ISSUE THREAD

**Issue by sanworks** [int-brain-lab/iblenv#27]
On running trainingChoiceWorld, I get an unhandled exception:

`
Unhandled Exception: System.Collections.Generic.KeyNotFoundException: The specified property 'REPortName' was not found in the workflow.
   at Bonsai.Expressions.ExpressionBuilderGraphExtensions.SetWorkflowProperty(ExpressionBuilderGraph source, String name, Object value)
   at Bonsai.Launcher.LaunchWorkflowPlayer(String fileName, Dictionary`2 propertyAssignments)
   at Bonsai.Program.Main(String[] args)
   at Bonsai64.Program.Main(String[] args)`

The software displays the error, but continues to run the task.
The ipad screen does not display the stimulus, and continues to show the desktop background.
I am able to manually run multiple trials, with sound and camera sync OK - but no output to the screen.

I'm not sure what REPortName is. The rotary encoder is on port COM5, and it is recognized by Pybpod (as shown in the following console output immediately after the Bonsai crash message):

`2020-09-02 14:58:58.920 INFO     [params.py:135] Writing {'NAME': 'SELECT_BOARD_NAME_(e.g.[_iblrig_mainenlab_behavior_0])', 'IBLRIG_VERSION': '6.4.2', 'COM_BPOD': 'COM4', 'COM_ROTARY_ENCODER': 'COM5', 'COM_F2TTL': 'COM6', 'F2TTL_DARK_THRESH': 70.0, 'F2TTL_LIGHT_THRESH': 30.0, 'F2TTL_CALIBRATION_DATE': '2020-09-02', 'SCREEN_FREQ_TARGET': 60, 'SCREEN_FREQ_TEST_STATUS': None, 'SCREEN_FREQ_TEST_DATE': None, 'WATER_CALIBRATION_RANGE': None, 'WATER_CALIBRATION_OPEN_TIMES': None, 'WATER_CALIBRATION_WEIGHT_PERDROP': None, 'WATER_CALIBRATION_DATE': None, 'BPOD_TTL_TEST_STATUS': None, 'BPOD_TTL_TEST_DATE': None} to C:\iblrig_params\.iblrig_params.json
`

It wasn't immediately clear to me how the Bonsai work flow inherits the REPortName parameter, and why it isn't getting 'COM5'.
Any suggestions are welcome.

**Comment by nbonacchi** [comment]
Bonsai is userd as a type of service. The task calls the Bonsia visual stim and one of the exposed variables that are required to launch it is REPortName asthe stream of positions from the RE is what is used to paint the stim in the correct locations when the subject moves the wheel.
All these values have default parameters that only by sheer luck would work on rigs that are not our dev rig, the error should be device not found not variable not found.
Can you point me at the specific workflow you're trying to run?

**Comment by sanworks** [comment]
I'm not sure what you mean by 'specific workflow'.
I select open pyBpod, select 'iblrig_test_user', then 'iblrig_test_mouse' and from the 'setup' drop menu, I select 'iblrig_tasks > TrainingChoiceWorld'. I don't actually have this setup active anymore - I tried wiping + reinstalling and ran into other issues (I'll post those next).
