### ISSUE TITLE
[Bug report] - README doesn't include ONE, iblrplate

### ISSUE THREAD

**Issue by eejd** [int-brain-lab/iblenv#271]
The current README installation instructions appear to be missing the ONE and iblrplate (iblutil) dependencies (if you want them as develop):

I assume the update would be the following (unless is a different, preferred way to install):

```
git clone git@github.com:int-brain-lab/ONE.git 
git clone git@github.com:int-brain-lab/iblrplate.git
conda develop ONE
conda develop iblrplate
```

Is there a reason to only use the pip version?

**Comment by k1o0** [comment]
Closing for now.  Reopen if you have any other questions.  If you do want to use a different branch of those repos either uninstall from pip and run conda develop or run pip install via git with the branch you want.
