### ISSUE TITLE
[Bug report] - Video transfer fails for behavior sessions in the ephys rig

### ISSUE THREAD

**Issue by guidomeijer** [int-brain-lab/iblenv#272]
**Describe the bug**
When running a behavioral session in the ephys rig and transferring the data, there is a problem with the video transfer. The behavior transfer already creates folder 'raw_video_data' with just one file in it. When running the video transfer, it fails because it tries to create a folder that already exists (the raw_video_data folder). After deleting the raw_video_data folder from the server, the video transfer script runs normally.

**Comment by k1o0** [comment]
Hi Guido, can you please confirm the rig version and session_params.py?

**Comment by nbonacchi** [comment]
This should be now fixed for both Training and Habituation since iblrig v6.5.1

**Comment by guidomeijer** [comment]
I updated to v6.5.1 but now I'm getting the following error when running the transfer of the behavior data after running trainingChoiceWorld on the ephys rig:

2021-11-02 15:21:01.137 INFO     [transfer_rig_data.py:46] Copying C:\iblrig_data\Subjects\ZFM-02601\2021-11-02\001...
Traceback (most recent call last):
  File "C:\iblrig\scripts\transfer_rig_data.py", line 23, in <module>
    main(args.local_folder, args.remote_folder)
  File "C:\Users\IBLUSER\Anaconda3\envs\iblenv\lib\site-packages\ibllib\pipes\transfer_rig_data.py", line 47, in main
    shutil.copytree(src, dst, ignore=ig(str(src_flag_file.name)))
  File "C:\Users\IBLUSER\Anaconda3\envs\iblenv\lib\shutil.py", line 368, in copytree
    raise Error(errors)
shutil.Error: [('C:\\iblrig_data\\Subjects\\ZFM-02601\\2021-11-02\\001\\raw_video_data', 'Y:\\Subjects\\ZFM-02601\\2021-11-02\\001\\raw_video_data', "[WinError 183] Cannot create a file when that file already exists: 'Y:\\\\Subjects\\\\ZFM-02601\\\\2021-11-02\\\\001\\\\raw_video_data'")]

**Comment by nbonacchi** [comment]
Closing for now, to be reopened if problem persists
