### ISSUE TITLE
[Bug report] - iblenv install fails on opencv-python

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblenv#275]
On Mac OS, the `iblenv` install fails on `opencv-python`:
```  ERROR: Failed building wheel for opencv-python```
Related to this issue: https://github.com/opencv/opencv-python/pull/577. Looks like it may be fixed in their next release. 

But for now, I fixed with commenting out that line from the `.yaml` file, and then `pip install opencv-python==4.5.3.56` in the `iblenv`. 

Closing this, but putting the hack here in case others may benefit.

**Comment by berkgercek** [comment]
So, broadly, I've found a solution for building iblenv that just generally makes life so much easier: use miniforge exclusively, i.e. cut out all of the continuum.io default channel and rely purely on the community-supported conda-forge channel.

I used to have a ton of issues with broken dependencies surrounding several packages every time I tried to install e.g. iblenv and then pytorch, but cutting out the default channel solved everything.

Also as a bonus miniforge optionally comes prepackaged with mamba which is much, much faster than conda.

**Comment by anne-urai** [comment]
@berkgercek do you have step-by-step instructions for that to put on the `README`? Sounds like it could save a lot of headache.

**Comment by berkgercek** [comment]
@anne-urai I can write up a set without a problem, but the broader issue is that the miniconda or mambaforge options are fairly specific to new installs. People with an existing conda installation who just want an IBL environment will not really get much mileage out of it.

@oliche @nbonacchi I can write up an "optional" install section on the README.md using the mambaforge option, with the suggestion that those who don't already have anaconda use this instead for simplicity and speed?
