### ISSUE TITLE
[Usage question] - Problem with ONE quickstart 

### ISSUE THREAD

**Issue by PatrickUdeh** [int-brain-lab/iblenv#276]
I have followed the instructions on installing the full IBL environment and have installed everything now I have moved on to the ONE quickstart and after inputting the first command I got the error from: can’t read /var/mail/one.api. What should I do to fix this?

**Comment by k1o0** [comment]
Hello, what was the first command?  `one.api` is not a folder used by ONE and `/var/mail` is not the correct place for ONE related data.  Can you paste in the full error stack? Also did you install ONE manually?  Perhaps during the ONE setup routine you entered `/var/mail/one.api` as the cache directory?

**Comment by PatrickUdeh** [comment]
Thank you for getting back to me I had made a simple mistake but figured it out
