### ISSUE TITLE
JSONDecodeError in response to the rotary encoder not working

### ISSUE THREAD

**Issue by srhaiken** [int-brain-lab/iblenv#277]
After I ran one mouse and put a second mouse on the rig, the stimulus appeared on the screen, but the wheel would not move anything. When I was in "tools --> Rotary encoder," I noticed that it was not working. No trouble shooting worked, so I switched the rotary encoder from one of our other rigs. I subsequently changed the JSON file to represent the proper port. Now, again in "tools --> rotary encoder," the wheel was moving and tracking and so I know the encoder is working. However, when I am unable to run a task because of the following errors you see attached. What do you suggest I do? Thank you!

![Image from iOS (2)](https://user-images.githubusercontent.com/86740288/144887055-ab957e5e-e954-47d1-adff-2d3571dd9b60.jpg)
![Image from iOS (1)](https://user-images.githubusercontent.com/86740288/144887059-6932cdbf-6adb-4317-b700-f05d09c49234.jpg)
![Image from iOS](https://user-images.githubusercontent.com/86740288/144887061-7b3cba89-daf1-4dca-97bf-256ae00f4f3a.jpg)
!

**Comment by nbonacchi** [comment]
Bpod needs resetting probably. Restarting Pybpod by closing the command prompt and relaunching has been found to be more stable.
You also have a bunch of registration errors.
Didn't we chat about this issue in an email string already @srhaiken ?
I remember explaining that the RE messages are built and sent to Bpod to be triggered during the execution of the task ... etc
