### ISSUE TITLE
[Bug report] -Seemingly not accurate atlas_acronym filter of Alyx rest queries. 

### ISSUE THREAD

**Issue by charlinetess** [int-brain-lab/iblenv#279]
**Describe the bug**
I use this function `def sessions_with_region_histology(acronym): 
    from one.api import ONE
    one = ONE()
    sessions= one.alyx.rest('sessions', 'list', atlas_acronym=acronym, task_protocol='ephys', project='ibl_neuropixel_brainwide', django='probe_insertion__trajectory_estimate__provenance__gte,70')
    return sessions `

To query sessions that target a particular region, in my example CA1. I extract their eid using the `one.to_eid` function. 
When loading the spikes data using `spikes, clusters, channels = bbone.load_spike_sorting_with_channel(eid, one=one, probe=currentprobe, brain_atlas=ba)`

for some sessions, the region of interest isn't in the 'clusters['probe00'].acronym' list. 

**To Reproduce**
1. Execute the query function for CA1 : `CA1_sessions=sessions_with_region_histology("CA1");
`
2. Translate to eid:` CA1_eids=one.to_eid(CA1_sessions);`
3. Extract a seemingly defectuous one, e.g. the first one `eid_CA1=CA1_eids[0];`
4. load data `spikes, clusters, channels = bbone.load_spike_sorting_with_channel(eid_CA1, one=one, probe='probe00', brain_atlas=ba)`
5. See error by checking `clusters['probe00'].acronym`

**Expected behavior**
I expected to get CA1 in the list of acronyms.

**Comment by GaelleChapuis** [comment]
Follow up question :
Does the atlas_acronym in the alyx.rest query have to be a leaf node ?

**Comment by GaelleChapuis** [comment]
@charlinetess do you have the same issue if you return a list of **insertions** rather (to be sure you are loading the recordings targeting a specific region, rather than a session that can contain up to 2 insertions, one of which may not have the desired brain region hit)?

**Comment by charlinetess** [comment]
@GaelleChapuis what is the query for insertions? I checked both probes when there are two. The first session seems to contain only one probe.

**Comment by GaelleChapuis** [comment]
Actually it might not be possible to do it at the insertion level, I cannot find the same `atlas_acronym` filter on the API https://alyx.internationalbrainlab.org/docs/#insertions-list

**Comment by oliche** [comment]
Cross referencing the commit here https://github.com/cortex-lab/alyx/pull/713:

When this is online on Alyx, the insertions endpoint supports the brain regions

``` 
from one.api import ONE
acronym = 'CA1'

one = ONE(base_url='http://localhost:8000')
sessions = one.alyx.rest('sessions', 'list', task_protocol='ephys',
                         atlas_acronym=acronym,
                         project='ibl_neuropixel_brainwide')


insertions = one.alyx.rest('insertions', 'list', task_protocol='ephys',
                           atlas_acronym=acronym,
                           project='ibl_neuropixel_brainwide')
```
