### ISSUE TITLE
KeyError: eid

### ISSUE THREAD

**Issue by naureeng** [int-brain-lab/iblenv#283]
My code that was working earlier today has stopped. I receive a message saying KeyError: eid. Attached a screenshot for the full details. This is after updating conda. There seems to be an issue with pandas. What pandas version is compatible with the newest ONE?

Thanks

![Screenshot from 2022-02-14 19-04-28](https://user-images.githubusercontent.com/32179063/153929388-2dd01896-9130-4fff-97c5-9a5a1da7c623.png)

**Comment by naureeng** [comment]
downgrading pandas and re-installing conda from the yaml file worked. strange .... sorry for listing this as a bug as i have since resolved the issue.

**Comment by k1o0** [comment]
FYI I think you were just unlucky in that you happened to download the cache during the two-hour window when it was generated with the wrong index.  Sorry for the confusion, this shouldn't happen again.
