### ISSUE TITLE
[Bug report] - AssertionError: Duplicate eids in sessions table

### ISSUE THREAD

**Issue by julienboussard** [int-brain-lab/iblenv#285]
**Describe the bug**
When running 

from one.api import ONE
from brainbox.io.one import SpikeSortingLoader
one = ONE()
pid = 'ce397420-3cd2-4a55-8fd1-5e28321981f4'

ssl = SpikeSortingLoader(pid=pid, one=one)
spikes, clusters, channels = ssl.load_spike_sorting()

I got the error AssertionError: Duplicate eids in sessions table

Running pip install -U ONE-api solved the issue 

**To Reproduce**

from one.api import ONE
from brainbox.io.one import SpikeSortingLoader
one = ONE()
pid = 'ce397420-3cd2-4a55-8fd1-5e28321981f4'

ssl = SpikeSortingLoader(pid=pid, one=one)
spikes, clusters, channels = ssl.load_spike_sorting()

**Expected behavior**

I expected to load the spike times, clusters and depths for the corresponding dataset

 - OS: BigSur 11.6
 - Browser : Safari 
 - Version : 15.0

**Comment by oliche** [comment]
`pip install -U ONE-api` solved the issue.
