### ISSUE TITLE
[Postmortem report] Weekend Alyx Downtime

### ISSUE THREAD

**Issue by micheleangelofabbri** [int-brain-lab/iblenv#294]
**Status:** Draft
**Owners:** Michele Fabbri

## Summary
Description: Alyx production server became unavailable via SSH and HTTP, potentially a out of memory error
Component: Alyx production availability
Date/time: 2022-03-19 12:05 & 2022-03-20 07:25
Duration: 4 hours on Saturday & 3 hours on Sunday
User impact: All users of Alyx

### 2022-03-19

12:05 - Server stopped responding to SSH and HTTP requests, all network traffic dropped **&lt;START OF OUTAGE&gt;**
12:46 - Alerts were emailed out (these alerts are still in the testing phase)
13:33 - Data was gathered about the outage and reported to Slack channel `software-staff`
15:45 - Further investigation of the data was performed and an aws console server reboot was issued
15:58 - All alarms cleared **&lt;END OF OUTAGE&gt;**
17:22 - Additional aws cloudwatch logging and alerting implemented

### 2022-03-20

07:25 - Server stopped responding to SSH and HTTP requests, all network traffic dropped **&lt;START OF OUTAGE&gt;**
07:52 - Alerts were emailed out (these alerts are still in the testing phase)
10:15 - Data was gathered about the outage and reported to Slack channel `software-staff` and an aws console server reboot was issued
10:25 - All alarms cleared **&lt;END OF OUTAGE&gt;**
14:20 - Additional analysis of logs reported to `software-staff`

### Impact and root cause

It is looking likely that there is a memory leak issue or a db query that needs to be restructured when the `01c_generate_cache.sh` cron job calls `one_cache.py` through django. This script is chewing through most all available memory on the server causing the OS kernel to kill the process. When the kernel kills the process, several other services attempt to restart and fail. This looks to be causing the system instability we are being presented with.

### What worked

The additional logging and alerting that was added on 2022-03-20 helped to narrow in on what processes are getting killed and what services were failing just before the outage.

### Where we got lucky

Low server usage due to it being the weekend and there being an ongoing conference

### What didn't work

Finding a direct causation of the outage. The additional logging and alerting have been helpful in determining likely links based on the time of events.

## Action items for the future

* Thorough evaluation of the `one_cache.py` functionality and performance.
* Building out a separate dev environment to better test these kinds of issues

### Prevention

Evaluating memory consumption in dev environments that more closely resemble the production environment would let us get ahead of these issues before they become issues.

### Process

Inclusion of the on-call personnel for these network down alerts.

## Other

Screenshots for the downtime events:

![i-0d190fc95390b3a79](https://user-images.githubusercontent.com/95646303/159254691-95347934-c0ad-46f3-96fa-e9a9ad6e9091.jpg)
![image](https://user-images.githubusercontent.com/95646303/159254693-3accc5ea-8546-4809-94be-0ec85ffc5207.png)
![image (1)](https://user-images.githubusercontent.com/95646303/159254696-2d0c4f43-94ff-40c9-934f-75463cc8e069.png)
![image (2)](https://user-images.githubusercontent.com/95646303/159254702-f17cd596-9e5d-4031-bc49-2fa7505de428.png)
![image (1)](https://user-images.githubusercontent.com/95646303/159255122-19149eed-9959-49fd-9325-19b95028f0b4.png)
![image (2)](https://user-images.githubusercontent.com/95646303/159255127-72d724aa-7b31-4062-a585-b1694c4b7d2d.png)
![i-0d190fc95390b3a79](https://user-images.githubusercontent.com/95646303/159255113-d3394089-2cc6-48ff-881e-a803d1354196.jpg)
![image](https://user-images.githubusercontent.com/95646303/159255119-332974c7-8aff-4a10-850d-5d0630e14cac.png)

**Comment by nbonacchi** [comment]
I'm archiving this for now
