### ISSUE TITLE
[Usage question] - How to check if a session has or not a dataset type associated with it

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#30]
**Describe the question you have**
Is there a better way to check if a session has a particular dataset associated to it (e.g. DLC : dataset_types = ['camera.dlc']) than using `one.load` and checking whether the output is None ?

Example of query :
```
ds = one.load(dataset_types=dataset_types, eid=eid)
if ds[0] is None:
   print('no DS found')
```

**Is your question related to a specific product?**
ONE usage

**Comment by mschart** [comment]
That seems good, no?

I did it very similarly:

```
    one = ONE()
    dataset_types = ['camera.times',
                     'wheel.position',
                     'wheel.timestamps',
                     'trials.intervals',
                     'camera.dlc']

    a = one.list(eid, 'dataset-types')

    assert all([i in a for i in dataset_types]
               ), 'For this eid, not all data available'
```

**Comment by GaelleChapuis** [comment]
Probably using `list` is best, thanks !

**Comment by kdharris101** [comment]
Doesn’t one.search do this?

**Comment by GaelleChapuis** [comment]
I thought `one.seach()` is used to search for eids of sessions which have a specific dataset type associated, for example:
`eids = one.search(dataset_types='camera.dlc')`

I was asking the inverse question here - Given a session eid,  how to check if the session has a given dataset type associated to it. I do not think `one.search` can be used for this, but I may be wrong ?

**Comment by kdharris101** [comment]
Oh, I see. Yes, one.list is what you want for that.
