### ISSUE TITLE
[Bug report] - cannot load trials

### ISSUE THREAD

**Issue by naureeng** [int-brain-lab/iblenv#302]
I cannot load the trials data in any code that previously worked -- attached screenshot of error
![Screenshot from 2022-04-14 17-56-24](https://user-images.githubusercontent.com/32179063/163437412-b5b87a67-368a-4cf6-9cfe-beeb857b5257.png)

**Comment by mayofaulkner** [comment]
Can you follow the instructions show in the terminal and upgrade ONE
````
pip install ONE-api --upgrade

**Comment by naureeng** [comment]
okay, I just tried it. It seems to not find the path that I know exists for the file downloads
![Screenshot from 2022-04-14 18-06-04](https://user-images.githubusercontent.com/32179063/163438725-b384e620-21f9-49ea-a2e6-06e2a9395cbc.png)

**Comment by naureeng** [comment]
I was able to fix it through a lot of playing around ... :(
The two main take-home messages:
1) Installing on the HPC first and then locally works for iblenv, but not the other way around given how the SWC and Gatsby maps our home drive
2) Use `pip install conda-build` rather than `conda install conda-build` to be able to use `conda develop`
