### ISSUE TITLE
Kilosort2/error: out of memory

### ISSUE THREAD

**Issue by ibldan** [int-brain-lab/iblenv#31]
run_batch_ks2_ibl.m , got this error: **Out of memory. Type "help memory" for your options.
Error in learnAndSolve8b (line 244)
           fWpc(:,:,2*size(st3,1)) = 0;
Error in run_ks2_ibl (line 73)
rez = learnAndSolve8b(rez);
Error in run_batch_ks2_ibl (line 40)
        run_ks2_ibl(rootZ, rootH);**      There is enough space in the server and  I didn't run any other things on the server.  

restart the matlab and computer, but got the same error. It seems that it always stopped at the step **4054.71 sec, 10101 / 11414 batches, 465 units, nspks: 4594.8495, mu: 13.3936, nst0: 8707, merges: 154.5829, 0.1216**,  then error appeared.   

see slack link: https://int-brain-lab.slack.com/archives/C9L8DKZ9T/p1579015818018700
![image](https://user-images.githubusercontent.com/47702608/72656703-0dcf1c80-3952-11ea-81a3-f89178013193.png)

**Comment by rossant** [comment]
The Kilosort team is currently continuing work on the Python version. It is still a bit unclear whether it will be worth rerunning the current KS2 algorithm (Python or MATLAB) on existing sessions or whether we should wait for an improvement of the algorithm itself

**Comment by oliche** [comment]
Closing it for now, seems related to KS2 and general spike sorting architecture beyond the scope of a github issue.
