### ISSUE TITLE
[Bug report] - Cannot load trials. variables in some sessions.  HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by yanliangshi** [int-brain-lab/iblenv#314]
Cannot load trials. variables in some sessions. 

When load trials variable, 

            collections = one.list_collections(eid, filename='_ibl_trials*')
            trials = one.load_object(eid, collection=collections[0],obj='trials')

            stim_on=trials.stimOn_times
            response=trials.response_times
            contrast_R=trials.contrastRight
            contrast_L=trials.contrastLeft
            choice=trials.choice
            block=trials.probabilityLeft

In multiple sessions, return "local md5 or size mismatch on the dataset", but fail to download.

local md5 or size mismatch on dataset: cortexlab/Subjects/KS023/2019-12-07/001alf/_ibl_trials.response_times.npy
HTTP Error 404: Not Found https://ibl.flatironinstitute.org/cortexlab/Subjects/KS023/2019-12-07/001/alf/_ibl_trials.response_times.b8331543-e0c1-4d13-864b-75bfbef74899.npy
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
/var/folders/dj/j81q4jt50tg47_26s7_lqk900000gn/T/ipykernel_4705/3887698895.py in <module>
     17 
     18             collections = one.list_collections(eid, filename='_ibl_trials*')
---> 19             trials = one.load_object(eid, collection=collections[0],obj='trials')
     20 
     21             stim_on=trials.stimOn_times

/opt/anaconda3/envs/iblenv/lib/python3.9/site-packages/one/util.py in wrapper(self, *args, **kwargs)
    165             mode = self.mode
    166         self.refresh_cache(mode=mode)
--> 167         return method(self, *args, **kwargs)
    168 
    169     return wrapper

/opt/anaconda3/envs/iblenv/lib/python3.9/site-packages/one/util.py in wrapper(self, id, *args, **kwargs)
    149         if eid is None:
    150             raise ValueError(f'Cannot parse session ID "{id}" (session may not exist)')
--> 151         return method(self, eid, *args, **kwargs)
    152 
    153     return wrapper

/opt/anaconda3/envs/iblenv/lib/python3.9/site-packages/one/api.py in load_object(self, eid, obj, collection, revision, query_type, download_only, **kwargs)
    793         # For those that don't exist, download them
    794         offline = None if query_type == 'auto' else self.mode == 'local'
--> 795         files = self._check_filesystem(datasets, offline=offline)
    796         files = [x for x in files if x]
    797         if not files:

/opt/anaconda3/envs/iblenv/lib/python3.9/site-packages/one/api.py in _check_filesystem(self, datasets, offline, update_exists)
    411             dsets_to_download = datasets.loc[indices_to_download]
    412             # Returns list of local file paths and set to variable
--> 413             new_files = self._download_datasets(dsets_to_download, update_cache=update_exists)
    414             # Add each downloaded file to the output list of files
    415             for i, file in zip(indices_to_download, new_files):

/opt/anaconda3/envs/iblenv/lib/python3.9/site-packages/one/api.py in _download_datasets(self, dsets, **kwargs)
   1533         except Exception as ex:
   1534             _logger.debug(ex)
-> 1535         return self._download_dataset(dsets, **kwargs)
   1536 
   1537     def _download_aws(self, dsets, **kwargs) -> List[Path]:

/opt/anaconda3/envs/iblenv/lib/python3.9/site-packages/one/api.py in _download_dataset(self, dset, cache_dir, update_cache, **kwargs)
   1671             return [None] * len(url)
   1672         target_dir = [str(Path(cache_dir, get_alf_path(x)).parent) for x in valid_urls]
-> 1673         files = self._download_file(valid_urls, target_dir, **kwargs)
   1674         # Return list of file paths or None if we failed to extract URL from dataset
   1675         return [None if not x else files.pop(0) for x in url]

/opt/anaconda3/envs/iblenv/lib/python3.9/site-packages/one/api.py in _download_file(self, url, target_dir, keep_uuid, file_size, hash)
   1722 
   1723         # download file(s) from url(s), returns file path(s) with UUID
-> 1724         local_path, md5 = self.alyx.download_file(url, target_dir=target_dir, return_md5=True)
   1725 
   1726         # check if url, hash, and file_size are lists

/opt/anaconda3/envs/iblenv/lib/python3.9/site-packages/one/webclient.py in download_file(self, url, **kwargs)
    726                 ex.msg += (' - please check your HTTP_DATA_SERVER_LOGIN and '
    727                            'HTTP_DATA_SERVER_PWD ONE params, or username/password kwargs')
--> 728             raise ex
    729         return files
    730 

/opt/anaconda3/envs/iblenv/lib/python3.9/site-packages/one/webclient.py in download_file(self, url, **kwargs)
    721         )
    722         try:
--> 723             files = download_fcn(url, **pars)
    724         except HTTPError as ex:
    725             if ex.code == 401:

/opt/anaconda3/envs/iblenv/lib/python3.9/site-packages/one/webclient.py in http_download_file_list(links_to_file_list, **kwargs)
    306         # build return list
    307         for future in futures:
--> 308             outputs.append(future.result())
    309     # if returning md5, separate list of tuples into two lists: (files, md5)
    310     return list(zip(*outputs)) if kwargs.get('return_md5', False) else outputs

/opt/anaconda3/envs/iblenv/lib/python3.9/concurrent/futures/_base.py in result(self, timeout)
    436                     raise CancelledError()
    437                 elif self._state == FINISHED:
--> 438                     return self.__get_result()
    439 
    440                 self._condition.wait(timeout)

/opt/anaconda3/envs/iblenv/lib/python3.9/concurrent/futures/_base.py in __get_result(self)
    388         if self._exception:
    389             try:
--> 390                 raise self._exception
    391             finally:
    392                 # Break a reference cycle with the exception in self._exception

/opt/anaconda3/envs/iblenv/lib/python3.9/concurrent/futures/thread.py in run(self)
     50 
     51         try:
---> 52             result = self.fn(*self.args, **self.kwargs)
     53         except BaseException as exc:
     54             self.future.set_exception(exc)

/opt/anaconda3/envs/iblenv/lib/python3.9/site-packages/one/webclient.py in http_download_file(full_link_to_file, chunks, clobber, silent, username, password, target_dir, return_md5, headers)
    391     except HTTPError as e:
    392         _logger.error(f'{str(e)} {full_link_to_file}')
--> 393         raise e
    394 
    395     file_size = int(u.getheader('Content-length'))

/opt/anaconda3/envs/iblenv/lib/python3.9/site-packages/one/webclient.py in http_download_file(full_link_to_file, chunks, clobber, silent, username, password, target_dir, return_md5, headers)
    388     # Open the url and get the length
    389     try:
--> 390         u = urllib.request.urlopen(req)
    391     except HTTPError as e:
    392         _logger.error(f'{str(e)} {full_link_to_file}')

/opt/anaconda3/envs/iblenv/lib/python3.9/urllib/request.py in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    212     else:
    213         opener = _opener
--> 214     return opener.open(url, data, timeout)
    215 
    216 def install_opener(opener):

/opt/anaconda3/envs/iblenv/lib/python3.9/urllib/request.py in open(self, fullurl, data, timeout)
    521         for processor in self.process_response.get(protocol, []):
    522             meth = getattr(processor, meth_name)
--> 523             response = meth(req, response)
    524 
    525         return response

/opt/anaconda3/envs/iblenv/lib/python3.9/urllib/request.py in http_response(self, request, response)
    630         # request was successfully received, understood, and accepted.
    631         if not (200 <= code < 300):
--> 632             response = self.parent.error(
    633                 'http', request, response, code, msg, hdrs)
    634 

/opt/anaconda3/envs/iblenv/lib/python3.9/urllib/request.py in error(self, proto, *args)
    553             http_err = 0
    554         args = (dict, proto, meth_name) + args
--> 555         result = self._call_chain(*args)
    556         if result:
    557             return result

/opt/anaconda3/envs/iblenv/lib/python3.9/urllib/request.py in _call_chain(self, chain, kind, meth_name, *args)
    492         for handler in handlers:
    493             func = getattr(handler, meth_name)
--> 494             result = func(*args)
    495             if result is not None:
    496                 return result

/opt/anaconda3/envs/iblenv/lib/python3.9/urllib/request.py in http_error_401(self, req, fp, code, msg, headers)
   1052     def http_error_401(self, req, fp, code, msg, headers):
   1053         url = req.full_url
-> 1054         response = self.http_error_auth_reqed('www-authenticate',
   1055                                           url, req, headers)
   1056         return response

/opt/anaconda3/envs/iblenv/lib/python3.9/urllib/request.py in http_error_auth_reqed(self, authreq, host, req, headers)
   1001                     # Ignore following challenges even if they use the Basic
   1002                     # scheme.
-> 1003                     return self.retry_http_basic_auth(host, req, realm)
   1004 
   1005         if unsupported is not None:

/opt/anaconda3/envs/iblenv/lib/python3.9/urllib/request.py in retry_http_basic_auth(self, host, req, realm)
   1016                 return None
   1017             req.add_unredirected_header(self.auth_header, auth)
-> 1018             return self.parent.open(req, timeout=req.timeout)
   1019         else:
   1020             return None

/opt/anaconda3/envs/iblenv/lib/python3.9/urllib/request.py in open(self, fullurl, data, timeout)
    521         for processor in self.process_response.get(protocol, []):
    522             meth = getattr(processor, meth_name)
--> 523             response = meth(req, response)
    524 
    525         return response

/opt/anaconda3/envs/iblenv/lib/python3.9/urllib/request.py in http_response(self, request, response)
    630         # request was successfully received, understood, and accepted.
    631         if not (200 <= code < 300):
--> 632             response = self.parent.error(
    633                 'http', request, response, code, msg, hdrs)
    634 

/opt/anaconda3/envs/iblenv/lib/python3.9/urllib/request.py in error(self, proto, *args)
    559         if http_err:
    560             args = (dict, 'default', 'http_error_default') + orig_args
--> 561             return self._call_chain(*args)
    562 
    563 # XXX probably also want an abstract factory that knows when it makes

/opt/anaconda3/envs/iblenv/lib/python3.9/urllib/request.py in _call_chain(self, chain, kind, meth_name, *args)
    492         for handler in handlers:
    493             func = getattr(handler, meth_name)
--> 494             result = func(*args)
    495             if result is not None:
    496                 return result

/opt/anaconda3/envs/iblenv/lib/python3.9/urllib/request.py in http_error_default(self, req, fp, code, msg, hdrs)
    639 class HTTPDefaultErrorHandler(BaseHandler):
    640     def http_error_default(self, req, fp, code, msg, hdrs):
--> 641         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    642 
    643 class HTTPRedirectHandler(BaseHandler):

HTTPError: HTTP Error 404: Not Found

**Comment by mayofaulkner** [comment]
can you make sure ONE-api is up to date
``` 
pip install ONE-api --upgrade```

**Comment by k1o0** [comment]
Hello I can't reproduce the problem here.  I have a feeling your cache is out of date.  Could you please run the following and paste the output?

```
one.refresh_cache('refresh')
print(one._cache._meta)
```

If no cache is downloaded and the created_date is old, please make sure you update your ONE by running `pip install -U ONE-api`.  You can verify the version by running the following from within your Python environment:
```
import one
print(one.__version__)
```

**Comment by k1o0** [comment]
Those two datasets are genuinely missing.  @mayofaulkner's looking into it.  For now maybe skip that session.

**Comment by yanliangshi** [comment]
Ok, thanks!

**Comment by k1o0** [comment]
This should be fixed now, could you please check?

**Comment by yanliangshi** [comment]
Yes, it is fixed now. Thanks a lot for your efforts!
