### ISSUE TITLE
[Bug report] -list index out of range, 824cf03d-4012-4ab1-b499-c83a92c5589e', 'probe00'

### ISSUE THREAD

**Issue by yanliangshi** [int-brain-lab/iblenv#315]
eid='824cf03d-4012-4ab1-b499-c83a92c5589e'
probe='probe00'

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/var/folders/dj/j81q4jt50tg47_26s7_lqk900000gn/T/ipykernel_4705/32584755.py in <module>
     24     channels={}
     25 
---> 26     spikes, clusters, channels = bbone.load_spike_sorting_with_channel(eid, one=one)
     27 
     28     if bool(clusters)==1 and bool(spikes)==1:

~/Works/int-brain-lab/ibllib-repo/brainbox/io/one.py in load_spike_sorting_with_channel(eid, one, probe, aligned, dataset_types, spike_sorter, brain_atlas, nested, return_collection)
    520         eid, one=one, probe=probe, dataset_types=dataset_types, spike_sorter=spike_sorter, return_collection=True)
    521     # -- Get brain regions and assign to clusters
--> 522     channels = load_channel_locations(eid, one=one, probe=probe, aligned=aligned,
    523                                       brain_atlas=brain_atlas)
    524     clusters = merge_clusters_channels(clusters, channels, keys_to_add_extra=None)

~/Works/int-brain-lab/ibllib-repo/brainbox/io/one.py in load_channel_locations(eid, probe, one, aligned, brain_atlas, return_source)
    389     incomplete_probes = [k for k in channels if 'x' not in channels[k]]
    390     for iprobe in incomplete_probes:
--> 391         channels_, source = _load_channel_locations_traj(eid, probe=iprobe, one=one, aligned=aligned,
    392                                                          brain_atlas=brain_atlas, return_source=True)
    393         if channels_ is not None:

~/Works/int-brain-lab/ibllib-repo/brainbox/io/one.py in _load_channel_locations_traj(eid, probe, one, revision, aligned, brain_atlas, return_source)
    277     brain_atlas = brain_atlas or AllenAtlas
    278     # need to find the collection bruh
--> 279     insertion = one.alyx.rest('insertions', 'list', session=eid, name=probe)[0]
    280     collection = _collection_filter_from_args(probe=probe)
    281     collections = one.list_collections(eid, filename='channels*', collection=collection,

IndexError: list index out of range

**Comment by yanliangshi** [comment]
I updated ONE,

import one
print(one.__version__)
1.12.2

I still have problems

**Comment by k1o0** [comment]
This function is a little old.  Can you try loading with the SpikeSortingLoader instead?

```
from brainbox.io.one import SpikeSortingLoader
from one.api import ONE

one = ONE()
eid = '824cf03d-4012-4ab1-b499-c83a92c5589e'
probe = 'probe00'

sl = SpikeSortingLoader(eid=eid, pname=probe, one=one)
spikes, clusters, channels = sl.load_spike_sorting()
clusters = sl.merge_clusters(spikes, clusters, channels)
```

More info here: https://int-brain-lab.github.io/iblenv/notebooks_external/loading_spikesorting_data.html

**Comment by yanliangshi** [comment]
Thanks, SpikeSortingLoader works for this insertions.
