### ISSUE TITLE
[Bug report] - Stop Iteration error when instantiation AllenAtlas

### ISSUE THREAD

**Issue by oliche** [int-brain-lab/iblenv#319]
On Windows

![image](https://user-images.githubusercontent.com/15081095/183666033-aae92223-d498-4be2-9b93-1172a8971fff.png)

**Comment by oliche** [comment]
This is most likely a file corruption when downlading the atlas files.
This code will give the location of the cached atlas files, please delete everything that is in the directory (especially `,nrrd` files)

```
from pathlib import Path
import one.params
par = one.params.get(silent=True)
FLAT_IRON_ATLAS_REL_PATH = Path('histology', 'ATLAS', 'Needles', 'Allen')

path_atlas = Path(par.CACHE_DIR).joinpath(FLAT_IRON_ATLAS_REL_PATH)
print(path_atlas)
```

Once this is done, try instantiating again:
```
from ibllib.atlas import AllenAtlas
ba = AllenAtlas()
```

**Comment by Aexolowski** [comment]
Yes, it worked, thanks a lot!
