### ISSUE TITLE
[Usage question] - Input not recognized in iblevn

### ISSUE THREAD

**Issue by Petrina-Lau** [int-brain-lab/iblenv#32]
When trying to operate python, git and start pybpod, input was not recognized by conda. Error message shows as:  '..." (that particular input, e.g. "start-pybpod" when I was trying to open bpod) is not recognized as an internal or external command, operable program or batch file.  

Similar error message showed up when I tried to "git pull" and "python ..." 

I have opened bpoy in this computer following the same process this morning and it worked.  

![image](https://user-images.githubusercontent.com/61651331/92629577-6cbd1980-f2c6-11ea-87c4-fa063f01cc47.png)

**Describe the question you have**
A clear and concise description of the question you have. Ex. How can I do [...] ?

**Is your question related to a specific product?**
Add links to relevant repositories or documents if so.

**Additional context**
Add any other context or screenshots about the usage question here.

**Comment by nbonacchi** [comment]
Fixed by reinstalling everything!
