### ISSUE TITLE
Crossreferencing NP data and AllenSDK connectivity matrices

### ISSUE THREAD

**Issue by MariaKCodes** [int-brain-lab/iblenv#324]
Hello:)

Thank you so much for your work! I am exploring Allen resources and I thought it would be cool if you could connect NP data with the whole brain connectivity map https://mouse-connectivity-models.readthedocs.io/ The module combines the massive mesoscale viral tracing experiments from the Mouse Connectivity Atlas into a single connectivity matrix using regression to predict connectivity profiles where data is lacking. Each cell in the connectivity matrix has a CCF reference brain coordinate. I was wondering, does your data permit assigning spikes to a brain voxel or coordinate in the CCF atlas. I read the documentation and thought channels.mlapdv.npy might be what I need (if I understand correctly it stores the brain coordinates of the NP channel, from the docs: Description: 3d location of the channels relative to bregma following ephys alignment - mediolateral; anterior-posterior; dorsoventral coordinates (um)), but I must be misunderstanding something, because the CCF coordinates of voxels in connectivity matrix when masked by brain region in channes.brainLocationIds_ccf_2017 don't match up. Maybe Allen coordinates and mlapdv are in different formats (the stuff about bergma)? Any help would be appreciated! Here's what I tried to do https://github.com/MariaKCodes/OpenMScThesisInNeuroPixelProbeDataAnalysis/blob/main/ConnectionAllenIBL.ipynb

Maria

**Comment by oliche** [comment]
Hello, I'm not sure this is relevant, but I'll put this here for future reference

```
from ibllib.atlas import BrainAtlas
ba = AllenAtlas()
ccf = ba.xyz2ccf(xyz)
```
Where xyz are the mlapdv coordinates in SI relative to Bregma.
![coordinates](https://user-images.githubusercontent.com/15081095/208183995-f1c3e2c3-37b2-4eca-a78a-5e379232735a.png)

The full documentation is here: https://int-brain-lab.github.io/iblenv/_autosummary/ibllib.atlas.atlas.html#ibllib.atlas.atlas.AllenAtlas.xyz2ccf

**Comment by oliche** [comment]
Closed for inactivity, feel free to re-open !
