### ISSUE TITLE
[Bug report] - iblenv (and other IBL libraries) should use either Anaconda or PIP but not both [QT fails arm64]

### ISSUE THREAD

**Issue by eejd** [int-brain-lab/iblenv#327]
Unfortunately, while some PIP and Anaconda packages play nice, not all do. Specifically, packages that depend heavily on other packages via dependencies and that are binary bound to a platform. I encountered this problem a few times in the past, but currently it is a blocker on running iblenv on M1 Macs using the arm64 binaries (specifically QT, but a few others had to have version bumps). I think the old instructions for using yaml conda environment definitions seems to make a lot of sense—as we are assuming user are running Anaconda. Then for IBL packages, the PIP versions should have parallel condaforge versions for deployment in the field. This [anaconda QT bug](https://github.com/ContinuumIO/anaconda-issues/issues/1554) has the Anaconda developers specifically suggesting to **not** mix PIP and Anaconda dependencies for managing environments.

The bug (for QT) is:
`conda install pyqt` works for arm64 to install pyqt5 (and can be version pinned)
`pip install pyqt5` does not, due to broken dependencies on arm64 even though you can install directly from source, brew, Anaconda, etc.

This suggests that the move from the conda yaml to PIP requirements is not probably the best approach for managing dependencies for the IBL, if we assume Anaconda as a primary dependency and package management solution. Ideally, adding any required libraries to condaforge would solve the problem.

**Comment by k1o0** [comment]
Agreed. We now recommend using pip inclusively. There is also an interaction between opencv and pyqt5 that can be resolved with the following:
```
pip uninstall opencv-python
pip uninstall opencv-python-headless
pip install opencv-python-headless
```
