### ISSUE TITLE
Datajoint retirement - round-up AWS instances

### ISSUE THREAD

**Issue by oliche** [int-brain-lab/iblenv#328]
Internal instance is gone.

Should we retire external instance ? Cost estimate for one year

https://int-brain-lab.slack.com/archives/CH4KYHLUS/p1677065579597529

- [x] estimate cost: 400 USD month incurring costs (breakdown above)
- [ ] find out about internal and external usage
- [ ] scale the instances according to reported usage and cost  

Instances for DJ may be paid on-the-go rather than reserved ($$) ; check how this will affect NMA
Check Ohio (Viz)
How to make a decision on how to retire - Outreach + Data WG ?

Review at next DAWG 18th May

**Comment by oliche** [comment]
Scaled down the elastic storage on London and Ohio and reserved instances according to usage.

**Comment by k1o0** [comment]
New tasks after decision to turn off DJ instances:

- [ ] Turn off all DJ instances
- [ ] Remove mention of DJ in behaviour paper repo
- [ ] Remove link to DJ behaviour site on IBL website but keep reference to it for readers of the DAWG paper.
