### ISSUE TITLE
[Usage question] - extract wheel gain and/or rotary encoder resolution in iblrig

### ISSUE THREAD

**Issue by noamroth** [int-brain-lab/iblenv#33]
How can I find what the wheel gain is in a rig (and in a behavioral experiment)? Additionally, If I suspect the gain seems off from what it should be, can I find out if Bonsai knows the correct resolution of the rotary encoder?

This is for a couple of behavioral rigs. I am running version 6.4.2.

**Comment by noamroth** [comment]
Great, thank you for all this information. Is there a way to check what the gain is set at for a session, i.e. by looking at what is sent on a trial by the iblrig.bonsai module?

**Comment by k1o0** [comment]
Hi Noam, you can check the stimulus gain in the following way:
```
### If the data aren't local
from oneibl.one import ONE
eid = "fb70ebf7-8175-42b0-9b7a-7c6e8612226e"
settings, = one.load(eid, "_iblrig_taskSettings.raw")
print(f"The stimulus gain is {settings['STIM_GAIN']:.0f}°/mm")

### For local data
from ibllib.io.raw_data_loaders import load_settings
session_path = r"E:/FlatIron/churchlandlab/Subjects/CSHL058/2020-07-08/001"
settings = load_settings(session_path)
print(f"The stimulus gain is {settings['STIM_GAIN']:.0f}°/mm")
```

Feel free to re-open if you have any other questions :)
