### ISSUE TITLE
Atlas example on Remapping - how to get the Beryl area volume

### ISSUE THREAD

**Issue by oliche** [int-brain-lab/iblenv#333]
Slack thread
https://int-brain-lab.slack.com/archives/CEM70EXTN/p1681377756561099

**Comment by GaelleChapuis** [comment]
Changed `ba.compute_regions_volume()` so it does not compute the cumulative sum across the levels of the hierarchy by default, but rather computes the volume for the voxels _remaining_ in a given region (difference of the sets).
