### ISSUE TITLE
[Bug report] - `PyQt5` pip version-finding issue in `iblenv` requirements installation

### ISSUE THREAD

**Issue by chris-langfield** [int-brain-lab/iblenv#336]
**Describe the bug**
When installing from the `requirements.txt` file in `iblenv`, `pip` cannot find a compatible `PyQt5` version.
**To Reproduce**
Following steps in https://github.com/int-brain-lab/iblenv#install-from-scratch for clean install. After using the workaround in #335 to get past the `PyQt5` hanging problem, the following line causes this error:

`pip install --requirement requirements.txt`

The message:

```
Collecting pyopengl
  Using cached PyOpenGL-3.1.6-py3-none-any.whl (2.4 MB)
ERROR: Ignored the following versions that require a different python version: 0.7 Requires-Python >=3.6, <3.7; 0.8 Requires-Python >=3.6, <3.7
ERROR: Could not find a version that satisfies the requirement PyQt5==5.12.3 (from versions: 5.14.0, 5.14.1, 5.14.2, 5.15.0, 5.15.1, 5.15.2, 5.15.3, 5.15.4, 5.15.5, 5.15.6, 5.15.7, 5.15.8, 5.15.9)
ERROR: No matching distribution found for PyQt5==5.12.3
```

**Comment by chris-langfield** [comment]
Related to #327?

**Comment by chris-langfield** [comment]
Duplicate of #335

**Comment by chris-langfield** [comment]
Removing the version lock for non-Windows systems as suggested in this version of the README seems to work, but is that lock still important/needed?

https://github.com/int-brain-lab/iblenv/commit/61718126e34541a874d8ec2514b661b5a8c56fc4

**Comment by bimac** [comment]
without having tested this myself - locking PyQt5 to a specific version doesn't sound like a great idea to me

**Comment by bimac** [comment]
[#327](https://github.com/int-brain-lab/iblenv/issues/327)
