### ISSUE TITLE
[Bug report] - cronjob on serverPC is aborted

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblenv#34]
**Describe the bug**
Since 09-07, no alf data have been extracted for my behavior (other data like video is uploaded up flatiron). 242 tasks are ‘Waiting’, which I've never seen for just behavioral extraction.

**To Reproduce**

My globus server is running. However, I get
```(base) ibladmin@iblserver:/mnt/cshl_grid/ibl$ ps -ef | grep jobs.py
ibladmin 15312 15247  0 Sep07 pts/2    00:02:21 python jobs.py run /mnt/s0/Data/Subjects
ibladmin 15579 15478  0 Sep09 ?        00:00:48 python jobs.py create /mnt/s0/Data/Subjects
ibladmin 15580 15478  0 Sep09 ?        00:00:01 python jobs.py kill run
ibladmin 20446 20289  0 Sep07 ?        00:00:01 python jobs.py kill run
ibladmin 20783  2084  0 06:53 pts/6    00:00:00 grep --color=auto jobs.py
ibladmin 32466 32368  0 Sep08 ?        00:00:01 python jobs.py kill run```

and

```
(base) ibladmin@iblserver:/mnt/cshl_grid/ibl$ cat /var/log/oneibl.log
Fetching origin
From https://github.com/int-brain-lab/iblscripts
   2ae1a98..ad38ae1  master      -> origin/master
   e443fbf..3193087  TaskQC_test -> origin/TaskQC_test
   fd967f0..5bad264  develop     -> origin/develop
Already on 'master'
Your branch is behind 'origin/master' by 8 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
HEAD is now at 2ae1a98 atlas: ccf 2 xyz conversions. volumes in mlapdv contiguous c-ordering. top and bottom surfaces.
Updating 2ae1a98..ad38ae1
Fast-forward
 ...data_releases.py => behaviour_data_releases.py} |   3 +-
 tests/test_ephys_pipeline.py                       |   6 +
 tests/test_task_qc_extractors.py                   | 159 +++++++++++++++++++++
 tests/test_training_audio.py                       |   2 +-
 tests/test_training_pipeline.py                    |   6 +
 5 files changed, 173 insertions(+), 3 deletions(-)
 rename tests/{test_data_releases.py => behaviour_data_releases.py} (94%)
 create mode 100644 tests/test_task_qc_extractors.py
Uninstalling ibllib-1.5.9:
  Successfully uninstalled ibllib-1.5.9
Uninstalling phylib-2.3a0:
  Successfully uninstalled phylib-2.3a0
Collecting git+https://github.com/cortex-lab/phylib.git@ibl_tests
  Cloning https://github.com/cortex-lab/phylib.git (to revision ibl_tests) to /tmp/pip-req-build-rz138ywd
  Running command git clone -q https://github.com/cortex-lab/phylib.git /tmp/pip-req-build-rz138ywd
  Running command git checkout -b ibl_tests --track origin/ibl_tests
  Switched to a new branch 'ibl_tests'
  Branch 'ibl_tests' set up to track remote branch 'ibl_tests' from 'origin'.
Requirement already satisfied: numpy in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from phylib==2.3a0) (1.16.4)
Requirement already satisfied: scipy in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from phylib==2.3a0) (1.3.0)
Requirement already satisfied: dask in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from phylib==2.3a0) (2.9.1)
Requirement already satisfied: requests in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from phylib==2.3a0) (2.22.0)
Requirement already satisfied: tqdm in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from phylib==2.3a0) (4.36.1)
Requirement already satisfied: toolz in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from phylib==2.3a0) (0.10.0)
Requirement already satisfied: joblib in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from phylib==2.3a0) (0.14.0)
Requirement already satisfied: mtscomp in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from phylib==2.3a0) (1.0.1)
Requirement already satisfied: certifi>=2017.4.17 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from requests->phylib==2.3a0) (2019.3.9)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from requests->phylib==2.3a0) (1.25.3)
Requirement already satisfied: idna<2.9,>=2.5 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from requests->phylib==2.3a0) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from requests->phylib==2.3a0) (3.0.4)
Building wheels for collected packages: phylib
  Building wheel for phylib (setup.py): started
  Building wheel for phylib (setup.py): finished with status 'done'
  Stored in directory: /tmp/pip-ephem-wheel-cache-wbntpgc8/wheels/18/f9/78/8492f045f770f5d4ec34b31db6bc89967856ae20dfc3fad26f
Successfully built phylib
Installing collected packages: phylib
Successfully installed phylib-2.3a0
WARNING: You are using pip version 19.1.1, however version 20.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting git+https://github.com/int-brain-lab/ibllib.git@master
  Cloning https://github.com/int-brain-lab/ibllib.git (to revision master) to /tmp/pip-req-build-x4v1qw9x
  Running command git clone -q https://github.com/int-brain-lab/ibllib.git /tmp/pip-req-build-x4v1qw9x
Requirement already satisfied: click>=7.0.0 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from ibllib==1.5.9) (7.0)
Requirement already satisfied: colorlog>=4.0.2 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from ibllib==1.5.9) (4.0.2)
Requirement already satisfied: flake8>=3.7.8 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from ibllib==1.5.9) (3.7.8)
Requirement already satisfied: globus-sdk>=1.7.1 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from ibllib==1.5.9) (1.7.1)
Requirement already satisfied: graphviz in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from ibllib==1.5.9) (0.14)
Requirement already satisfied: jupyter>=1.0 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from ibllib==1.5.9) (1.0.0)
Requirement already satisfied: jupyterlab>=1.0 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from ibllib==1.5.9) (1.2.6)
Requirement already satisfied: matplotlib>=3.0.3 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from ibllib==1.5.9) (3.1.0)
Requirement already satisfied: mtscomp>=1.0.1 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from ibllib==1.5.9) (1.0.1)
Requirement already satisfied: numba in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from ibllib==1.5.9) (0.50.1)
Requirement already satisfied: numpy>=1.16.4 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from ibllib==1.5.9) (1.16.4)
Requirement already satisfied: opencv-python in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from ibllib==1.5.9) (4.1.1.26)
Requirement already satisfied: pandas>=0.24.2 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from ibllib==1.5.9) (0.24.2)
Requirement already satisfied: phylib>=2.2 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from ibllib==1.5.9) (2.3a0)
Requirement already satisfied: pyarrow in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from ibllib==1.5.9) (1.0.0)
Requirement already satisfied: pynrrd>=0.4.0 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from ibllib==1.5.9) (0.4.0)
Requirement already satisfied: requests>=2.22.0 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from ibllib==1.5.9) (2.22.0)
Requirement already satisfied: scikit-learn>=0.22.1 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from ibllib==1.5.9) (0.22.1)
Requirement already satisfied: scipy>=1.3.0 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from ibllib==1.5.9) (1.3.0)
Requirement already satisfied: seaborn>=0.9.0 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from ibllib==1.5.9) (0.9.0)
Requirement already satisfied: tqdm>=4.32.1 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from ibllib==1.5.9) (4.36.1)
Requirement already satisfied: pyflakes<2.2.0,>=2.1.0 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from flake8>=3.7.8->ibllib==1.5.9) (2.1.1)
Requirement already satisfied: mccabe<0.7.0,>=0.6.0 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from flake8>=3.7.8->ibllib==1.5.9) (0.6.1)
Requirement already satisfied: entrypoints<0.4.0,>=0.3.0 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from flake8>=3.7.8->ibllib==1.5.9) (0.3)
Requirement already satisfied: pycodestyle<2.6.0,>=2.5.0 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from flake8>=3.7.8->ibllib==1.5.9) (2.5.0)
Requirement already satisfied: six<2.0.0,>=1.10.0 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from globus-sdk>=1.7.1->ibllib==1.5.9) (1.12.0)
Requirement already satisfied: pyjwt[crypto]<2.0.0,>=1.5.3 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from globus-sdk>=1.7.1->ibllib==1.5.9) (1.7.1)
Requirement already satisfied: jupyter-console in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from jupyter>=1.0->ibllib==1.5.9) (6.1.0)
Requirement already satisfied: notebook in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from jupyter>=1.0->ibllib==1.5.9) (6.0.3)
Requirement already satisfied: ipywidgets in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from jupyter>=1.0->ibllib==1.5.9) (7.5.1)
Requirement already satisfied: qtconsole in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from jupyter>=1.0->ibllib==1.5.9) (4.6.0)
Requirement already satisfied: ipykernel in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from jupyter>=1.0->ibllib==1.5.9) (5.1.4)
Requirement already satisfied: nbconvert in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from jupyter>=1.0->ibllib==1.5.9) (5.6.1)
Requirement already satisfied: jupyterlab-server~=1.0.0 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from jupyterlab>=1.0->ibllib==1.5.9) (1.0.6)
Requirement already satisfied: jinja2>=2.10 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from jupyterlab>=1.0->ibllib==1.5.9) (2.11.1)
Requirement already satisfied: tornado!=6.0.0,!=6.0.1,!=6.0.2 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from jupyterlab>=1.0->ibllib==1.5.9) (6.0.3)
Requirement already satisfied: cycler>=0.10 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from matplotlib>=3.0.3->ibllib==1.5.9) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from matplotlib>=3.0.3->ibllib==1.5.9) (2.4.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from matplotlib>=3.0.3->ibllib==1.5.9) (1.1.0)
Requirement already satisfied: python-dateutil>=2.1 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from matplotlib>=3.0.3->ibllib==1.5.9) (2.8.0)
Requirement already satisfied: setuptools in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from numba->ibllib==1.5.9) (41.0.1)
Requirement already satisfied: llvmlite<0.34,>=0.33.0.dev0 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from numba->ibllib==1.5.9) (0.33.0)
Requirement already satisfied: pytz>=2011k in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from pandas>=0.24.2->ibllib==1.5.9) (2019.1)
Requirement already satisfied: toolz in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from phylib>=2.2->ibllib==1.5.9) (0.10.0)
Requirement already satisfied: joblib in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from phylib>=2.2->ibllib==1.5.9) (0.14.0)
Requirement already satisfied: dask in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from phylib>=2.2->ibllib==1.5.9) (2.9.1)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from requests>=2.22.0->ibllib==1.5.9) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from requests>=2.22.0->ibllib==1.5.9) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from requests>=2.22.0->ibllib==1.5.9) (2019.3.9)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from requests>=2.22.0->ibllib==1.5.9) (1.25.3)
Requirement already satisfied: cryptography>=1.4; extra == "crypto" in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from pyjwt[crypto]<2.0.0,>=1.5.3->globus-sdk>=1.7.1->ibllib==1.5.9) (2.6.1)
Requirement already satisfied: ipython in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from jupyter-console->jupyter>=1.0->ibllib==1.5.9) (7.5.0)
Requirement already satisfied: jupyter-client in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from jupyter-console->jupyter>=1.0->ibllib==1.5.9) (5.3.4)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from jupyter-console->jupyter>=1.0->ibllib==1.5.9) (2.0.9)
Requirement already satisfied: pygments in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from jupyter-console->jupyter>=1.0->ibllib==1.5.9) (2.4.2)
Requirement already satisfied: Send2Trash in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from notebook->jupyter>=1.0->ibllib==1.5.9) (1.5.0)
Requirement already satisfied: traitlets>=4.2.1 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from notebook->jupyter>=1.0->ibllib==1.5.9) (4.3.2)
Requirement already satisfied: jupyter-core>=4.6.1 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from notebook->jupyter>=1.0->ibllib==1.5.9) (4.6.1)
Requirement already satisfied: nbformat in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from notebook->jupyter>=1.0->ibllib==1.5.9) (5.0.4)
Requirement already satisfied: terminado>=0.8.1 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from notebook->jupyter>=1.0->ibllib==1.5.9) (0.8.3)
Requirement already satisfied: prometheus-client in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from notebook->jupyter>=1.0->ibllib==1.5.9) (0.7.1)
Requirement already satisfied: pyzmq>=17 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from notebook->jupyter>=1.0->ibllib==1.5.9) (18.1.1)
Requirement already satisfied: ipython-genutils in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from notebook->jupyter>=1.0->ibllib==1.5.9) (0.2.0)
Requirement already satisfied: widgetsnbextension~=3.5.0 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from ipywidgets->jupyter>=1.0->ibllib==1.5.9) (3.5.1)
Requirement already satisfied: bleach in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from nbconvert->jupyter>=1.0->ibllib==1.5.9) (3.1.0)
Requirement already satisfied: pandocfilters>=1.4.1 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from nbconvert->jupyter>=1.0->ibllib==1.5.9) (1.4.2)
Requirement already satisfied: testpath in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from nbconvert->jupyter>=1.0->ibllib==1.5.9) (0.4.4)
Requirement already satisfied: defusedxml in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from nbconvert->jupyter>=1.0->ibllib==1.5.9) (0.6.0)
Requirement already satisfied: mistune<2,>=0.8.1 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from nbconvert->jupyter>=1.0->ibllib==1.5.9) (0.8.4)
Requirement already satisfied: jsonschema>=3.0.1 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from jupyterlab-server~=1.0.0->jupyterlab>=1.0->ibllib==1.5.9) (3.2.0)
Requirement already satisfied: json5 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from jupyterlab-server~=1.0.0->jupyterlab>=1.0->ibllib==1.5.9) (0.9.1)
Requirement already satisfied: MarkupSafe>=0.23 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from jinja2>=2.10->jupyterlab>=1.0->ibllib==1.5.9) (1.1.1)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from cryptography>=1.4; extra == "crypto"->pyjwt[crypto]<2.0.0,>=1.5.3->globus-sdk>=1.7.1->ibllib==1.5.9) (1.12.3)
Requirement already satisfied: asn1crypto>=0.21.0 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from cryptography>=1.4; extra == "crypto"->pyjwt[crypto]<2.0.0,>=1.5.3->globus-sdk>=1.7.1->ibllib==1.5.9) (0.24.0)
Requirement already satisfied: pexpect; sys_platform != "win32" in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from ipython->jupyter-console->jupyter>=1.0->ibllib==1.5.9) (4.7.0)
Requirement already satisfied: decorator in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from ipython->jupyter-console->jupyter>=1.0->ibllib==1.5.9) (4.4.0)
Requirement already satisfied: backcall in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from ipython->jupyter-console->jupyter>=1.0->ibllib==1.5.9) (0.1.0)
Requirement already satisfied: pickleshare in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from ipython->jupyter-console->jupyter>=1.0->ibllib==1.5.9) (0.7.5)
Requirement already satisfied: jedi>=0.10 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from ipython->jupyter-console->jupyter>=1.0->ibllib==1.5.9) (0.13.3)
Requirement already satisfied: wcwidth in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->jupyter-console->jupyter>=1.0->ibllib==1.5.9) (0.1.7)
Requirement already satisfied: ptyprocess; os_name != "nt" in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from terminado>=0.8.1->notebook->jupyter>=1.0->ibllib==1.5.9) (0.6.0)
Requirement already satisfied: webencodings in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from bleach->nbconvert->jupyter>=1.0->ibllib==1.5.9) (0.5.1)
Requirement already satisfied: attrs>=17.4.0 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from jsonschema>=3.0.1->jupyterlab-server~=1.0.0->jupyterlab>=1.0->ibllib==1.5.9) (19.3.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from jsonschema>=3.0.1->jupyterlab-server~=1.0.0->jupyterlab>=1.0->ibllib==1.5.9) (0.15.7)
Requirement already satisfied: importlib-metadata; python_version < "3.8" in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from jsonschema>=3.0.1->jupyterlab-server~=1.0.0->jupyterlab>=1.0->ibllib==1.5.9) (1.5.0)
Requirement already satisfied: pycparser in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from cffi!=1.11.3,>=1.8->cryptography>=1.4; extra == "crypto"->pyjwt[crypto]<2.0.0,>=1.5.3->globus-sdk>=1.7.1->ibllib==1.5.9) (2.19)
Requirement already satisfied: parso>=0.3.0 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from jedi>=0.10->ipython->jupyter-console->jupyter>=1.0->ibllib==1.5.9) (0.4.0)
Requirement already satisfied: zipp>=0.5 in /home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages (from importlib-metadata; python_version < "3.8"->jsonschema>=3.0.1->jupyterlab-server~=1.0.0->jupyterlab>=1.0->ibllib==1.5.9) (2.2.0)
Building wheels for collected packages: ibllib
  Building wheel for ibllib (setup.py): started
  Building wheel for ibllib (setup.py): finished with status 'done'
  Stored in directory: /tmp/pip-ephem-wheel-cache-xb4262aj/wheels/16/26/c4/9fe3563f3a12839a93e2cad59f3132c2a278dd25a657971670
Successfully built ibllib
Installing collected packages: ibllib
Successfully installed ibllib-1.5.9
WARNING: You are using pip version 19.1.1, however version 20.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Namespace(action='kill', dry=False, folder='create', restart=False)
status/kill request sent, waiting for job response
b'ACK STOP'
Job terminated successfully
Namespace(action='create', dry=False, folder='/mnt/s0/Data/Subjects', restart=False)
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
Connected to https://alyx.internationalbrainlab.org as anneu
ABORT !!
```

**Comment by oliche** [comment]
Ok the output here is quite bad, it shows several instances of `jobs.py kill`

```
(base) ibladmin@iblserver:/mnt/cshl_grid/ibl$ ps -ef | grep jobs.py
ibladmin 15312 15247  0 Sep07 pts/2    00:02:21 python jobs.py run /mnt/s0/Data/Subjects
ibladmin 15579 15478  0 Sep09 ?        00:00:48 python jobs.py create /mnt/s0/Data/Subjects
ibladmin 15580 15478  0 Sep09 ?        00:00:01 python jobs.py kill run
ibladmin 20446 20289  0 Sep07 ?        00:00:01 python jobs.py kill run
ibladmin 20783  2084  0 06:53 pts/6    00:00:00 grep --color=auto jobs.py
ibladmin 32466 32368  0 Sep08 ?        00:00:01 python jobs.py kill run
```

FYI, everyday, the service updates and restarts safely using this command. If this command stalls it means something holds the jobs.py run job at the OS level. In this case it's my fault, I used your server as a pilot for a release :face_with_head_bandage:. When I did so I stopped the run jobs in a tmux sending it to the background and did not clean up afterwards.
The automatic jobs will take over tonight, I've restarted the service manually in the meantime.
Indeed a restart would have fixed it. Here I'm responsible for this, sorry !

So  fixed.
