### ISSUE TITLE
Copy strategy GUI + acquisition description

### ISSUE THREAD

**Issue by k1o0** [int-brain-lab/iblenv#340]
Write specifications for the acquisition description file:

- describe format
- describe copy with multiple computers and aggregation of chunks
- describe synchronisation options
- [Copy workflow description](https://github.com/int-brain-lab/iblscripts/blob/mesoscope/deploy/transfer_data.py#L5-L50)

OW output the acquisition description file.

- [ ] from the task code
- [x] from ephys https://github.com/int-brain-lab/iblscripts/commit/c95ac4a2f4e77fcdacc0a5bf1ead95fdb1e5cb8f
- [x] from video https://github.com/int-brain-lab/iblscripts/commit/6a2ea635ca7724f58b6521a34ac609c98eee101c
- [ ] from photometry
- [ ] (how do you know you've collected all acquisition description stubs ?)

The description is live here: https://int-brain-lab.github.io/iblrig/description_file.html

**Comment by oliche** [comment]
![Image](https://github.com/int-brain-lab/iblenv/assets/15081095/19e311d7-7dab-4c78-ae28-06b138b7bf28)

Mockup from Gaelle for the GUI
