### ISSUE TITLE
[Feature request] - Add atlas_acronym to trajectory provenance in Alyx REST API

### ISSUE THREAD

**Issue by guidomeijer** [int-brain-lab/iblenv#35]
Currently it's only possible to query **sessions** that have a channel in a specified brain region. It would be handy if this query can be done at the level of a **trajectory** as well.

**Comment by oliche** [comment]
`trajs = one.alyx.rest('trajectories', 'list', django='channels__brain_region__name__icontains,Entorhinal area medial part dorsal zone layer 2')`

You can change name by id or acronym to refine the query.
Feel free to re-open if you get stumped !
