### ISSUE TITLE
Review Alyx report page, streamline QC check

### ISSUE THREAD

**Issue by juhuntenburg** [int-brain-lab/iblenv#350]

**Comment by GaelleChapuis** [comment]
It will be important to communicate to the researchers which page do not work any longer.

**Comment by GaelleChapuis** [comment]
On this page: https://alyx.internationalbrainlab.org/ibl_reports/gallery/sessions
- Have a filter for training / ephys sessions (and other modalities)
- Mark the recording modality / protocol used
- training sessions have no plots, but they could have the raw video plot + psychometric curves eventually

**Comment by GaelleChapuis** [comment]
No taskQC (whilst using standard protocol) and no Alyx Tasks for fiberphotometry sessions, example:
- https://alyx.internationalbrainlab.org/ibl_reports/gallery/8fdff393-f14f-4b70-a168-8851a1158e69, using standard `_iblrig_tasks_biasedChoiceWorld8.12.9`

**Comment by GaelleChapuis** [comment]
Review is done, new sprint item to fix some of the issues.
