### ISSUE TITLE
`churchland_learninglifespan` alignment errors

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblenv#351]
Missing MTSCOMP chunk file:
https://alyx.internationalbrainlab.org/admin/actions/session/8cfb0b3d-2877-4616-9e32-4139c4501691/change/
https://alyx.internationalbrainlab.org/admin/actions/session/107249ca-0d03-4e56-a7eb-6fe6210550ae/change/

EphysCellsQC not done:
```
 CSHL061 2020-07-29 probe00 2631e77a-d521-4939-b247-e7a0ea0a95c1
 CSHL063 2020-09-12 probe00 3685d60d-70f9-4a0e-918b-6bee333d1d1a
 CSHL067 2020-09-29 probe00 08c49305-d12c-4cc5-8f5c-b29f62f3a4a6
 CSHL068 2020-10-06 probe00 9341b8f3-fa57-4fbb-9d0b-7ca3613da0cc
 CSHL065 2020-10-04 probe00 85b98361-9706-4318-8923-6988d4e804e8
 CSHL073 2020-09-28 probe00 8f4213bd-49ab-4421-bf1b-a1f8e6e1f37f
 CSHL066 2020-09-28 probe00 e096bf1f-b2b7-471d-b07b-e4e6d65299ac
 CSHL068 2020-10-06 probe01 57edc590-a53d-403c-9aab-d58ee51b6a24
 CSHL066 2020-09-26 probe01 23e12f60-05fc-43ce-9536-f2feef8db037
 CSHL073 2020-09-26 probe01 b6787ce8-a641-4422-9ada-eaea3fa2b70d
 CSHL063 2020-09-12 probe01 178f92c5-38ad-4b0a-a235-606a8c271884
 CSHL067 2020-09-29 probe01 7246e8f8-f694-488f-8ce8-5214975ffe9a
 CSHL065 2020-10-04 probe01 ba40eda8-601d-41cb-a629-290d17e7a680
 CSHL075 2020-10-15 probe01 fc93dc34-3329-475b-b779-1167482c86b7
 CSHL_018 2020-03-16 probe01 0bc568eb-feed-4d5d-86e2-edfdf84ed707
```

**Comment by chris-langfield** [comment]
`EphysCellsQC` runs were completed by @mayofaulkner 

There are a few other issues:

Possible preprocessing weirdness for:

```
              session_path    probe    cond_no
0   CSHL068/2020-10-06/002  probe00   6.143485
1   CSHL065/2020-10-04/001  probe01   7.548049
2   CSHL073/2020-09-28/001  probe00   7.616887
3   CSHL066/2020-09-28/001  probe00  43.569138
4   CSHL068/2020-10-06/002  probe01  18.965136
5  CSHL_018/2020-03-16/002  probe01   3.495825
6   CSHL061/2020-07-29/001  probe00   5.935834
7   CSHL062/2020-07-11/001  probe00  15.020447
8   CSHL062/2020-07-11/001  probe01   5.381830
9   CSHL065/2020-10-04/001  probe00   6.225098
```
I have computed the whitening matrix condition number which appears to be stable. @oliche and I will discuss further troubleshooting steps here. 

----------------------------------------------------------------------------------------------------------------

The gui unable to handle probes with 276 channels:

```
CSHL063 2020-09-12 probe00 3685d60d-70f9-4a0e-918b-6bee333d1d1a -> short probe
CSHL067 2020-09-29 probe00 08c49305-d12c-4cc5-8f5c-b29f62f3a4a6 -> short probe
CSHL063 2020-09-12 probe01 178f92c5-38ad-4b0a-a235-606a8c271884 -> short probe
CSHL067 2020-09-29 probe01 7246e8f8-f694-488f-8ce8-5214975ffe9a -> short probe
```

With the error `ValueError: cannot reshape array of size 384 into shape (276,1)` in `voltage.destripe`. 

This error cropped up previously and was seemingly addressed by https://github.com/int-brain-lab/iblapps/commit/3d8499d4df0995c389bf6d373bc26116c0f5b1f6#diff-03d2bf14369fcba6c774ef92fb887fa4327c877e54b65ba6bbda9a83bf793445 [@mayofaulkner ]

**Comment by k1o0** [comment]
Fixed by correcting channel maps. Spikesorting quality may require rerun.
