### ISSUE TITLE
[Bug report] - cannot load wheel_dlc_viewer

### ISSUE THREAD

**Issue by naureeng** [int-brain-lab/iblenv#359]
**Describe the bug**
cannot load wheel_dlc_viewer due to opencv issue

**Screenshots**
![Screenshot from 2024-01-24 12-50-26](https://github.com/int-brain-lab/iblenv/assets/32179063/81aaad60-2f14-4127-b240-e2ece7199a8f)

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by k1o0** [comment]
Perhaps you can try the following within the env:
```
pip uninstall opencv-python
pip uninstall opencv-python-headless
pip install opencv-python-headless
```

Let me know if this fixes the issue!

**Comment by k1o0** [comment]
Closing due to lack of response. Feel free to reopen if the problem persists.
