### ISSUE TITLE
Change log page and emails for external users

### ISSUE THREAD

**Issue by juhuntenburg** [int-brain-lab/iblenv#360]
- [ ] add release note (what has been patched etc) to iblenv docs
- [ ] add email form to iblenv page https://forms.gle/9ex2vL1JwV4QXnf98
- [ ] email change log warning

(Added email to brain wide map release page on 3rd Jan 2024; but a new page with release notes should also contain it)

**Comment by juhuntenburg** [comment]
I'm taking myself out of the assignment as I sent you all the info on slack. Lmk if you need anything else

**Comment by GaelleChapuis** [comment]
Text: https://docs.google.com/document/d/1ylVy8bLjkfjnSHhxHudvH5x2VG9ziJssR9REq9FrOi4/edit?usp=sharing

**Comment by GaelleChapuis** [comment]
Added onto BW release page https://github.com/int-brain-lab/ibllib/pull/731
