### ISSUE TITLE
Screen position from wheel dynamics example

### ISSUE THREAD

**Issue by mayofaulkner** [int-brain-lab/iblenv#366]
Provide example code for how to infer stimlus position using wheel dynamics

From email 

> Subject: Request for Gabor Visual Stimuli Data from "A Brain-Wide Map of Neural Activity during Complex Behaviour"
Message: Dear IBL team,
I hope this message finds you well. I am writing to express my interest in reconstructing the Gabor visual stimuli described in your recent publication, "A Brain-Wide Map of Neural Activity during Complex Behaviour." I am keen to examine the correlation between these stimuli and the neural activity data available in the DANDI archive.
To facilitate a precise replication of the experiments, including aspects such as luminance and the dynamics of the Gabor stimuli, would it be possible for you to provide access to the relevant data files? Your assistance would be invaluable in enabling us to accurately reproduce and further investigate the findings detailed in your study.
Thank you for considering this request. I look forward to your favorable response.
Sincerely,
Masaru Kuwabara Ph. D. /Araya Inc.

- example code
- link to gabor shader

**Comment by GaelleChapuis** [comment]
Neurostars https://neurostars.org/t/request-for-gabor-visual-stimuli-data-from-a-brain-wide-map-of-neural-activity-during-complex-behaviour/29145
