### ISSUE TITLE
[Bug report] - Bonsai Installer Crash

### ISSUE THREAD

**Issue by sanworks** [int-brain-lab/iblenv#37]
Bonsai installer crashes with the following screenshot when it runs as part of install.py:

![BonsaiInstallError](https://user-images.githubusercontent.com/17090284/92952003-e10dcf00-f424-11ea-90e4-2af049e4def7.png)

To get this error, after deleting a previous installation's C:/iblrig, C:/iblrig_data and C:/iblrig_params folders, I cloned the iblrig repository, entered the cloned folder and ran 'python install.py'

If I then try to run a protocol that uses Bonsai (e.g. _iblrig_calibration > frame2TTL), I get another crash:

`Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Reactive.Core, Version=2.2.5.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
   at Bonsai.Launcher.LaunchWorkflowPlayer(String fileName, Dictionary2 propertyAssignments)
   at Bonsai.Program.Main(String[] args)
   at Bonsai64.Program.Main(String[] args)`

**Comment by nbonacchi** [comment]
Closing in favor of #39
