### ISSUE TITLE
Review ephys recording script and documentation

### ISSUE THREAD

**Issue by k1o0** [int-brain-lab/iblenv#379]
There is some confusion with the old and new ephys recording script and rig params. The script is in iblscripts/deploy/ephyspc. The old parameters are in APPDATA while the new ones are in the iblrig settings file. There is a function that migrates these but the old file is still used somehow.  Second, the documentation is probably out of date, and third, the old script should be removed entirely once all users have iblrigv8 in their env.

**Comment by mayofaulkner** [comment]
- Starting ephys without ephys recording (training on ephys rig)
- Nate problem not finding the correct parameters (using wrong parameters file)
- Update the protocol for ephys recording google documentation with new v8 instructions
- Deprecate iblscripts command, use instead iblrig version

**Comment by bimac** [comment]
https://github.com/int-brain-lab/iblrig/issues/718

**Comment by k1o0** [comment]
Running `start_ephys_session example 0` then copying with `transfer_data --tag ephys` now works fine for extracting behaviour-only ephys rig sessions.

@GaelleChapuis Are there any old Google Doc instructions we should update for running ephys sessions in general?
