### ISSUE TITLE
[EXTRACT]value error of path using load_spike.sorting 

### ISSUE THREAD

**Issue by hcao37** [int-brain-lab/iblenv#384]
eid = 'f56194bc-8215-4ae8-bc6a-89781ad8e050' and every other eid I have tried (here I was trying to extract spikes and clusters using 

ssl = SpikeSortingLoader(one=one, eid=eid)
spikes, clusters, channels = ssl.load_spike_sorting()
clusters = ssl.merge_clusters(spikes, clusters, channels)

it says that ValueError: '/root/Downloads/IBL_Cache/NR_0028/2023-03-15/003/alf/probe01/pykilosort/spikes.amps.npy' is not in the subpath of '/root/Downloads/IBL_Cache/steinmetzlab/Subjects/NR_0028/2023-03-15/003' OR one path is relative and the other is absolute.

I have this issue for multiple eid I use

**Background on the recording**
all the eids that sessions where both Sciw and Scdg regions were recorded and they always worked until a few days ago

**Comment by gergogomori** [comment]
hi k1o0,

I have the same issue. I believe it is not specific to a lab or a recording session. I’d like to add two pieces of information which might help:
- A week ago it was working, so a change within  this time period might be causing the issue
- Before the error, I also got the following warning:
/usr/local/lib/python3.10/dist-packages/one/util.py:543: ALFWarning: Multiple revisions: "", "2024-05-06"
warnings.warn(f'Multiple revisions: {rev_list}', alferr.ALFWarning)

Thank you so much for your support!

**Comment by k1o0** [comment]
Unfortunately I wasn't able to reproduce the error. Could you please paste the entire error traceback so that I can see from where the error arose? Also, please let me know the path of your ONE data cache directory. You can get this by running the following: `from one.api import ONE; print(ONE(mode='local').cache_dir)`

**Comment by hcao37** [comment]
Hi K1o0, according to the code you provided above,it shows
/root/Downloads/ONE/openalyx.internationalbrainlab.org

Downloading: /root/Downloads/ONE/openalyx.internationalbrainlab.org/histology/ATLAS/Needles/Allen/average_template_25.nrrd Bytes: 32998960
100%|██████████| 31.470260620117188/31.470260620117188 [00:03<00:00,  9.53it/s]
Downloading: /root/Downloads/ONE/openalyx.internationalbrainlab.org/histology/ATLAS/Needles/Allen/annotation_25.nrrd Bytes: 4035363
100%|██████████| 3.848422050476074/3.848422050476074 [00:01<00:00,  2.97it/s]
/root/Downloads/ONE/openalyx.internationalbrainlab.org/MFD_06/2023-08-22/001/alf/probe00/pykilosort/spikes.amps.npy: 100%|██████████| 82.7M/82.7M [00:02<00:00, 40.7MB/s]
/root/Downloads/ONE/openalyx.internationalbrainlab.org/MFD_06/2023-08-22/001/alf/probe00/pykilosort/spikes.clusters.npy: 100%|██████████| 82.7M/82.7M [00:00<00:00, 95.5MB/s]
/root/Downloads/ONE/openalyx.internationalbrainlab.org/MFD_06/2023-08-22/001/alf/probe00/pykilosort/spikes.depths.npy: 100%|██████████| 82.7M/82.7M [00:00<00:00, 149MB/s]
/root/Downloads/ONE/openalyx.internationalbrainlab.org/MFD_06/2023-08-22/001/alf/probe00/pykilosort/spikes.times.npy: 100%|██████████| 82.7M/82.7M [00:00<00:00, 158MB/s]
/root/Downloads/ONE/openalyx.internationalbrainlab.org/MFD_06/2023-08-22/001/alf/probe00/pykilosort/clusters.channels.npy: 100%|██████████| 4.63k/4.63k [00:00<00:00, 112kB/s]
/root/Downloads/ONE/openalyx.internationalbrainlab.org/MFD_06/2023-08-22/001/alf/probe00/pykilosort/clusters.depths.npy: 100%|██████████| 2.38k/2.38k [00:00<00:00, 20.1kB/s]
/root/Downloads/ONE/openalyx.internationalbrainlab.org/MFD_06/2023-08-22/001/alf/probe00/pykilosort/clusters.metrics.pqt: 100%|██████████| 77.3k/77.3k [00:00<00:00, 498kB/s]
/root/Downloads/ONE/openalyx.internationalbrainlab.org/MFD_06/2023-08-22/001/alf/probe00/pykilosort/clusters.uuids.csv: 100%|██████████| 20.8k/20.8k [00:00<00:00, 453kB/s]
/usr/local/lib/python3.10/dist-packages/one/util.py:543: ALFWarning: Multiple revisions: "", "2024-05-06"
  warnings.warn(f'Multiple revisions: {rev_list}', alferr.ALFWarning)
/root/Downloads/ONE/openalyx.internationalbrainlab.org/MFD_06/2023-08-22/001/alf/probe00/pykilosort/channels.brainLocationIds_ccf_2017.npy: 100%|██████████| 3.20k/3.20k [00:00<00:00, 51.4kB/s]
/root/Downloads/ONE/openalyx.internationalbrainlab.org/MFD_06/2023-08-22/001/alf/probe00/pykilosort/#2024-05-06#/channels.labels.npy: 100%|██████████| 512/512 [00:00<00:00, 10.4kB/s]
/root/Downloads/ONE/openalyx.internationalbrainlab.org/MFD_06/2023-08-22/001/alf/probe00/pykilosort/channels.localCoordinates.npy: 100%|██████████| 3.20k/3.20k [00:00<00:00, 49.7kB/s]
/root/Downloads/ONE/openalyx.internationalbrainlab.org/MFD_06/2023-08-22/001/alf/probe00/pykilosort/channels.mlapdv.npy: 100%|██████████| 4.74k/4.74k [00:00<00:00, 20.7kB/s]
/root/Downloads/ONE/openalyx.internationalbrainlab.org/MFD_06/2023-08-22/001/alf/probe00/pykilosort/channels.rawInd.npy: 100%|██████████| 3.20k/3.20k [00:00<00:00, 40.1kB/s]
/usr/local/lib/python3.10/dist-packages/one/util.py:543: ALFWarning: Multiple revisions: "", "2024-05-06"
  warnings.warn(f'Multiple revisions: {rev_list}', alferr.ALFWarning)
/root/Downloads/ONE/openalyx.internationalbrainlab.org/MFD_06/2023-08-22/001/alf/probe00/pykilosort/channels.brainLocationIds_ccf_2017.npy: 100%|██████████| 3.20k/3.20k [00:00<00:00, 76.3kB/s]
/root/Downloads/ONE/openalyx.internationalbrainlab.org/MFD_06/2023-08-22/001/alf/probe00/pykilosort/#2024-05-06#/channels.labels.npy: 100%|██████████| 512/512 [00:00<00:00, 12.6kB/s]
/root/Downloads/ONE/openalyx.internationalbrainlab.org/MFD_06/2023-08-22/001/alf/probe00/pykilosort/channels.localCoordinates.npy: 100%|██████████| 3.20k/3.20k [00:00<00:00, 81.3kB/s]
/root/Downloads/ONE/openalyx.internationalbrainlab.org/MFD_06/2023-08-22/001/alf/probe00/pykilosort/channels.mlapdv.npy: 100%|██████████| 4.74k/4.74k [00:00<00:00, 132kB/s]
/root/Downloads/ONE/openalyx.internationalbrainlab.org/MFD_06/2023-08-22/001/alf/probe00/pykilosort/channels.rawInd.npy: 100%|██████████| 3.20k/3.20k [00:00<00:00, 90.0kB/s]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-18-d550fd82c87d>](https://localhost:8080/#) in <cell line: 8>()
      6 
      7 ssl = SpikeSortingLoader(one=one, eid=eid)
----> 8 spikes, clusters, channels = ssl.load_spike_sorting()
      9 clusters = ssl.merge_clusters(spikes, clusters, channels)
     10 

2 frames
[/usr/lib/python3.10/pathlib.py](https://localhost:8080/#) in relative_to(self, *other)
    816         if (root or drv) if n == 0 else cf(abs_parts[:n]) != cf(to_abs_parts):
    817             formatted = self._format_parsed_parts(to_drv, to_root, to_parts)
--> 818             raise ValueError("{!r} is not in the subpath of {!r}"
    819                     " OR one path is relative and the other is absolute."
    820                              .format(str(self), str(formatted)))

ValueError: '/root/Downloads/ONE/openalyx.internationalbrainlab.org/MFD_06/2023-08-22/001/alf/probe00/pykilosort/spikes.amps.npy' is not in the subpath of '/root/Downloads/ONE/openalyx.internationalbrainlab.org/churchlandlab_ucla/Subjects/MFD_06/2023-08-22/001' OR one path is relative and the other is absolute.

**Comment by k1o0** [comment]
Thanks a lot for the extra information. I've pushed a fix to the ONE API. Please run `pip install -U ONE-api` from within your env and ensure you're on version 2.10.1. Feel free to reopen if you still experience issues.

**Comment by gergogomori** [comment]
It is working again for me, thank you very much k1o0 :)

**Comment by hcao37** [comment]
It is working at my end as well, thank you!!
