### ISSUE TITLE
[Bug report] process killed for `load_spike_sorting` in a loop

### ISSUE THREAD

**Issue by berberto** [int-brain-lab/iblenv#385]
I'm downloading spike-sorting data to use locally.

The following is a minimal script to do what I need:
```python
from one.api import ONE
from brainwidemap import bwm_query, bwm_loading
from brainbox.io.one import SpikeSortingLoader

UNIT_QC = 1.0
one_ON  = ONE(base_url='https://alyx.internationalbrainlab.org')

one = one_ON
bwm_df = bwm_query(freeze='2023_12_bwm_release', one=one, return_details=True)
for i, rec in bwm_df.iterrows():

    print(f"{i+1} -- {rec.subject}, {rec.date}, {rec.eid}, {rec.probe_name}")
    gspikes, gclusters = bwm_loading.load_good_units(pid=rec.pid, one=one, qc=UNIT_QC)
    sl = SpikeSortingLoader(one=one, pid=rec.pid)
    spikes, clusters, channels = sl.load_spike_sorting(revision='2024-05-06', good_units=True)
```
The process gets killed after a while -- after loading about 100 entries.
I suspect this is filling up the RAM, but unclear to me at what level.

System info:
- OS: Ubuntu 20.04
- Linux kernel: 5.15.0-124-generic
- Arch: x86_64
- Memory: 32 GB

**Comment by berberto** [comment]
I freed up some memory and I could run it till the end.
However, I've monitored memory usage, which increases steadily, up to ~14-15 GB, and then gets cleared.
Not sure if it's due to any caching in the SpikeSortingLoader code, or if it's just normal Python behavior in this case.

**Comment by oliche** [comment]
Hello, 
Usually we have issues when looping over many recordings and plotting but not just loading.
If you have suspected memory leaks, a good first try is to use garbage collection:

```
import gc

for gna in gnagnagna:
    some stuff...
    gc.collect()
```

Another way is to use a parallel processing framework (such as joblib), with n_jobs = 1. This way you could eventually scale your computation in the future.
