### ISSUE TITLE
SPIKESORTING_KS2_MATLAB   Error

### ISSUE THREAD

**Issue by ibldan** [int-brain-lab/iblenv#42]
**Describe the bug**
All my recent ephys sessions have this error for KS2 spike sorting below (in the Alyx  https://alyx.internationalbrainlab.org/admin-tasks/status/EphysExtractionPipeline):

**2020-09-16 00:12:17,786,786 INFO [tasks.py:68] Starting job <class 'ibllib.pipes.ephys_preprocessing.SpikeSorting_KS2_Matlab'>
2020-09-16 00:28:10,705,705 INFO [ephys_preprocessing.py:132] /home/ibladmin/Documents/PYTHON/iblscripts/deploy/serverpc/kilosort2/task_ks2_matlab.sh /mnt/s/ks2m/DY_016_2020-09-15_001_probe00
2020-09-16 00:47:46,297,297 ERROR [tasks.py:76] Traceback (most recent call last):
File "/home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages/ibllib/pipes/tasks.py", line 72, in run
self.outputs = self._run(**kwargs)
File "/home/ibladmin/Documents/PYTHON/envs/iblenv/lib/python3.7/site-packages/ibllib/pipes/ephys_preprocessing.py", line 140, in _run
raise RuntimeError('Matlab error ks2 log below:')
RuntimeError: Matlab error ks2 log below:

2020-09-16 00:47:46,298,298 INFO [tasks.py:77] Job <class 'ibllib.pipes.ephys_preprocessing.SpikeSorting_KS2_Matlab'> errored
2020-09-16 00:47:46,298,298 INFO [tasks.py:87] N outputs: 0
2020-09-16 00:47:46,298,298 INFO [tasks.py:88] --- 2128.511780977249 seconds run-time ---**

**Comment by ibldan** [comment]
I try to run KS2 locally, and below is my matlab code:
**addpath(genpath('~/Documents/MATLAB/Kilosort2')) % path to kilosort folder
addpath('~/Documents/MATLAB/npy-matlab/npy-matlab');
addpath(genpath('~/Documents/MATLAB/spikes'));
addpath(genpath('~/Documents/MATLAB/ibllib-matlab'));
addpath(genpath('~/Documents/PYTHON/iblscripts/deploy/serverpc/kilosort2'));
data_path = '/mnt/s0/Data/Subjects/DY_016/2020-09-11/001/raw_ephys_data/probe00';
channel_map_3a = "~/Documents/PYTHON/iblscripts/deploy/serverpc/kilosort2/ks2configFiles/neuropixPhase3A_kilosortChanMap.mat";
rootH = '/mnt/s';
run_ks2_ibl(data_path, rootH, '*.cbin', load(channel_map_3a));**


but got this error:
**Batch 1331 has fewer than Nfilt spikes.
Warning: data batch #1331 only had 0 spikes

> In clusterSingleBatches (line 121)
  In run_ks2_ibl (line 42)
  In run_ks2_ibl_local (line 11)
Batch 1332 has fewer than Nfilt spikes.
Warning: data batch #1332 only had 0 spikes

> In clusterSingleBatches (line 121)
  In run_ks2_ibl (line 42)
  In run_ks2_ibl_local (line 11)
Undefined function or variable 'W'.
Error in /home/ibladmin/Documents/MATLAB/Kilosort2/preProcess/clusterSingleBatches.m line : 133
Error in /home/ibladmin/Documents/PYTHON/iblscripts/deploy/serverpc/kilosort2/run_ks2_ibl.m line : 42
Error in /home/ibladmin/Documents/PYTHON/iblscripts/deploy/serverpc/kilosort2/run_ks2_ibl_local.m line : 11**

**Comment by oliche** [comment]
Ok for kilosort2 matlab bugs, in a terminal, go into the Kilosort2 folder then:
`git pull`

in Matlab :
`cd Kilosort2\CUDA`
`mexGPUall`

And then try to re-run and let us know.

**Comment by ibldan** [comment]
git pull
**ibladmin@iblserver:/mnt/s$ cd /home/ibladmin/Documents/PYTHON/iblscripts/deploy/serverpc/kilosort2
ibladmin@iblserver:~/Documents/PYTHON/iblscripts/deploy/serverpc/kilosort2$ git pull
Already up to date.
ibladmin@iblserver:~/Documents/PYTHON/iblscripts/deploy/serverpc/kilosort2$ cd /home/ibladmin/Documents/MATLAB/Kilosort2
ibladmin@iblserver:~/Documents/MATLAB/Kilosort2$ git pull
Already up to date.**

matlab
**mexGPUall
Building with 'nvcc'.
MEX completed successfully.
Building with 'nvcc'.
MEX completed successfully.
Building with 'nvcc-dp'.
MEX completed successfully.
Building with 'nvcc'.
MEX completed successfully.
Building with 'nvcc'.
MEX completed successfully.
Building with 'nvcc'.
MEX completed successfully.
Building with 'nvcc'.
MEX completed successfully.
Building with 'nvcc'.
MEX completed successfully.**


KS2 running still got same error:
**Warning: data batch #1460 only had 0 spikes
 
> In clusterSingleBatches (line 121)
  In run_ks2_ibl (line 42)
  In run_ks2_ibl_local (line 12) 
Undefined function or variable 'W'.
Error in /home/ibladmin/Documents/MATLAB/Kilosort2/preProcess/clusterSingleBatches.m line : 133
Error in /home/ibladmin/Documents/PYTHON/iblscripts/deploy/serverpc/kilosort2/run_ks2_ibl.m line : 42
Error in /home/ibladmin/Documents/PYTHON/iblscripts/deploy/serverpc/kilosort2/run_ks2_ibl_local.m line : 12

run_ks2_ibl.m failed**

**Comment by oliche** [comment]
@ibldan this is a KS2 specific error. It seems that during a time segment, no spike at all is detected. It may be a data consistency issue.
I can advise to do 2 things:

- look at the raw data QC and the spectrogram (dataset types to query in one below)
- if everything looks normal, create an issue directly on the KS2 github repository

```
 '_iblqc_ephysSpectralDensity.freqs',
 '_iblqc_ephysSpectralDensity.power',
 '_iblqc_ephysTimeRms.rms',
 '_iblqc_ephysTimeRms.timestamps',
```

I am going to close this for now.
