### ISSUE TITLE
[Usage question] - How to align trials to clusters properly?

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#43]
**Describe the question you have**
Clusters on the same probe in the same subject on the same date have a different number of trials.

To replicate:

Example clusters:
```
[{'subject_uuid': UUID('b55c97f2-1024-4b16-9774-2d9049942f98'),
  'session_start_time': datetime.datetime(2020, 1, 27, 16, 52, 31),
  'probe_idx': 0,
  'cluster_id': 241,
  'insertion_data_source': 'Ephys aligned histology track',
  'ontology': 'CCF 2017',
  'acronym': 'ACAd6a'},
 {'subject_uuid': UUID('b55c97f2-1024-4b16-9774-2d9049942f98'),
  'session_start_time': datetime.datetime(2020, 1, 27, 16, 52, 31),
  'probe_idx': 0,
  'cluster_id': 242,
  'insertion_data_source': 'Ephys aligned histology track',
  'ontology': 'CCF 2017',
  'acronym': 'ACAd6a'},
 {'subject_uuid': UUID('b55c97f2-1024-4b16-9774-2d9049942f98'),
  'session_start_time': datetime.datetime(2020, 1, 27, 16, 52, 31),
  'probe_idx': 0,
  'cluster_id': 243,
  'insertion_data_source': 'Ephys aligned histology track',
  'ontology': 'CCF 2017',
  'acronym': 'ACAd6a'},
 {'subject_uuid': UUID('b55c97f2-1024-4b16-9774-2d9049942f98'),
  'session_start_time': datetime.datetime(2020, 1, 27, 16, 52, 31),
  'probe_idx': 0,
  'cluster_id': 244,
  'insertion_data_source': 'Ephys aligned histology track',
  'ontology': 'CCF 2017',
  'acronym': 'ACAd6a'},
 {'subject_uuid': UUID('b55c97f2-1024-4b16-9774-2d9049942f98'),
  'session_start_time': datetime.datetime(2020, 1, 27, 16, 52, 31),
  'probe_idx': 0,
  'cluster_id': 245,
  'insertion_data_source': 'Ephys aligned histology track',
  'ontology': 'CCF 2017',
  'acronym': 'ACAd6a'},
 {'subject_uuid': UUID('b55c97f2-1024-4b16-9774-2d9049942f98'),
  'session_start_time': datetime.datetime(2020, 1, 27, 16, 52, 31),
  'probe_idx': 0,
  'cluster_id': 246,
  'insertion_data_source': 'Ephys aligned histology track',
  'ontology': 'CCF 2017',
  'acronym': 'ACAd6a'},
 {'subject_uuid': UUID('b55c97f2-1024-4b16-9774-2d9049942f98'),
  'session_start_time': datetime.datetime(2020, 1, 27, 16, 52, 31),
  'probe_idx': 0,
  'cluster_id': 247,
  'insertion_data_source': 'Ephys aligned histology track',
  'ontology': 'CCF 2017',
  'acronym': 'ACAd6a'},
 {'subject_uuid': UUID('b55c97f2-1024-4b16-9774-2d9049942f98'),
  'session_start_time': datetime.datetime(2020, 1, 27, 16, 52, 31),
  'probe_idx': 0,
  'cluster_id': 248,
  'insertion_data_source': 'Ephys aligned histology track',
  'ontology': 'CCF 2017',
  'acronym': 'ACAd6a'},
 {'subject_uuid': UUID('b55c97f2-1024-4b16-9774-2d9049942f98'),
  'session_start_time': datetime.datetime(2020, 1, 27, 16, 52, 31),
  'probe_idx': 0,
  'cluster_id': 249,
  'insertion_data_source': 'Ephys aligned histology track',
  'ontology': 'CCF 2017',
  'acronym': 'ACAd6a'},
 {'subject_uuid': UUID('b55c97f2-1024-4b16-9774-2d9049942f98'),
  'session_start_time': datetime.datetime(2020, 1, 27, 16, 52, 31),
  'probe_idx': 0,
  'cluster_id': 250,
  'insertion_data_source': 'Ephys aligned histology track',
  'ontology': 'CCF 2017',
  'acronym': 'ACAd6a'}]
```

Then run this script to get the number of trials:
```
trials_spike_times_by_cluster = []
for test_cluster in test_clusters:
    trials_spike_times = (ephys.AlignedTrialSpikes & test_cluster & 'event="stim on"').fetch('trial_spike_times')
    trials_spike_times_by_cluster.append(trials_spike_times)
n_trials_per_cluster = [len(trials_spike_times) for trials_spike_times in trials_spike_times_by_cluster]
n_trials_per_cluster
```
outputs: `[872, 628, 872, 846, 745, 787, 867, 853, 872, 872]`

**Is your question related to a specific product?**
Datajoint

**Additional context**
Reporting on behalf of @RylanSchaeffer

**Comment by nbonacchi** [comment]
Can't run your code need more context but it looks like you're trying to: for each cluster, get all the spike_times aligned on " stim on". So either some trials have no spikes for that cluster (this could happen for multiple reasons biological or electrical/mechanical noise) OR the stimulus onset was not detected for some trials and AlignedTrialSpikes can't return trial_spike_times aligned to a non existing event. @shenshan stim_on_times is nullable right?
Can you check/run the QC for that session to see the status of the tests that have stimOn in the name?

**Comment by GaelleChapuis** [comment]
@RylanSchaeffer Could you upload here the code that gave you the clusters data? Thank you !

**Comment by RylanSchaeffer** [comment]
The code is on the IBL Jupyter Hub (https://jupyter.internationalbrainlab.org/user/rylanschaeffer/notebooks/public/Queries%20and%20Plotting/2020-07-01-Rylan-Mouse-Behavior-and-Ephys-Playground.ipynb#). The clusters were selected by identifying the best performing mice (across all trials) and then selecting only their sessions

**Comment by RylanSchaeffer** [comment]
@nbonacchi it seems reasonable for a cluster to have no spikes on a trial, but in that case, I'd expect to find empty arrays, not missing arrays.

**Comment by shenshan** [comment]
For now I skipped the trials with no spikes to save some space for the db, but if there is a good reason to keep them as empty arrays, I could fill them in.

**Comment by RylanSchaeffer** [comment]
So what's the correct way to group spike times within a cluster by each trial or by each block?

**Comment by RylanSchaeffer** [comment]
In case this helps clarify, in my head, I want a DataFrame with the following columns:
- subject uuid
- session uuid
- block index within session
- trial index within session
- trial index since block changepoint
- cluster uuid
- cluster brain region
- spike times for that cluster in that trial/block/session/subject

**Comment by shenshan** [comment]
Ok let me propose to the Data team to place back the empty trials. If they approve I would put them back in. In that case, you could fetch the db to get the frame you would like.

**Comment by RylanSchaeffer** [comment]
A possible alternative to including empty trials is to instead add a trial within session column (and maybe a trial within block column)

**Comment by RylanSchaeffer** [comment]
Any updates on this? I've been blocked on this for two weeks and I really need to get moving

**Comment by shenshan** [comment]
The trials with no spikes were done ingesting now.

**Comment by GaelleChapuis** [comment]
To be clear: Trials with no spikes are now returned as empty arrays.
