### ISSUE TITLE
[Feature request] - Change line style in task viewer GUI

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#47]
**Is your feature request related to a problem? Please describe.**
For ease of visualization it would be best if the same line style could be kept across event type. Current GUI display:
<img width="821" alt="Capture d’écran 2020-09-18 à 13 58 18" src="https://user-images.githubusercontent.com/43007596/93595164-88f04300-f9b7-11ea-9f7e-66995eaceee6.png">

**Describe the solution you'd like**
Could the GUI be changed so as to keep on having _times as solid lines, and Trigger_times as dashed? (the rest is fine)

**Additional context**
https://github.com/int-brain-lab/iblapps/blob/develop/task_qc_viewer/README.md

**Comment by oliche** [comment]
Fixed in iblapps: qc_tasklocal and ibllib:ephys_extraction 
Commit fdbb458e9ed177c9d9232b9208e9b0f4e04c3f0d
