### ISSUE TITLE
[Bug report] - 404 error on ibllib/docs

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#48]
**Describe the bug**
https://int-brain-lab.github.io/ibllib/docs/ > Page not found 404 error

Link taken from README in https://github.com/int-brain-lab/iblenv/tree/docs/docs_gh_pages 

**To Reproduce**
Click on Link

**Expected behavior**
Webpage.
Is there another page to look at ? Is the docs branch the correct one to look into for documentation (for now)?

**Comment by mayofaulkner** [comment]
It is now here https://int-brain-lab.github.io/iblenv/

I have updated the readme!
