### ISSUE TITLE
[Bug report] - TaskQC(eid) returns empty qc.extractor for specific eid

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#50]
**Describe the bug**

Using ibllib master branch and running this code:

from ibllib.qc.task_metrics import TaskQC
from ibllib.qc.qcplots import plot_results
eid = 'c6db3304-c906-400c-aa0f-45dd3945b2ea'
qc = TaskQC(eid)

The last line runs, but qc.extractor is empty. As a result, no plotting can be done.
This is odd at the QC seems to have run, as displayed on Alyx: https://alyx.internationalbrainlab.org/admin/actions/ephyssession/c6db3304-c906-400c-aa0f-45dd3945b2ea/change/

**To Reproduce**
Run code above

**Expected behavior**
qc.extractor not empty

**Comment by k1o0** [comment]
Calling any of the `run`, `load_data` and `compute` methods will load the data.
