### ISSUE TITLE
[Usage question] - How to open 'pqt' files

### ISSUE THREAD

**Issue by ineslaranjeira** [int-brain-lab/iblenv#51]
DLC camera files (e.g. _ibl_leftCamera.dlc) are sometimes found to be in _npy_ format, and sometimes in _pqt_ format. 
How can _pqt_ files be open?
An example session _session_uuid_ with such a file would be: ‘fb9bdf18-76be-452b-ac4e-21d5de3a6f9f’

**Comment by oliche** [comment]
So far we are planning to keep them in parquet format https://parquet.apache.org/
This is already part of the ibl environment here. To read you can just:

I use this:
```
from brainbox.io import parquet
data = parquet.load('myfile')
```

And here the command without any IBL wrapper.
```
import pyarrow.parquet as pq
data = pq.read_table(file).to_pandas()
```
