### ISSUE TITLE
[Feature request] - Adding filter for subject / date in Alyx Task status table

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#52]
**Is your feature request related to a problem? Please describe.**
I am trying to verify whether a specific session (e.g. https://alyx.internationalbrainlab.org/admin/actions/ephyssession/4ecb5d24-f5cc-402c-be28-9d0f7cb14b3a/change/) has all of the extraction jobs completed.
Currently, it is quite hard to find back that session in the table.
https://alyx.internationalbrainlab.org/admin-tasks/status/EphysExtractionPipeline/mrsicflogellab?page=1
(as a matter of fact, it does not seem to appear)

**Describe the solution you'd like**
Adding a filter so as to find easily sessions associated to a given mouse / date.

**Describe alternatives you've considered**
CTRL + Find using the subject name.

**Additional context**
Alyx.

**Comment by oliche** [comment]
It is the second session of the `hoferlab` ephys page.

This is quite hard to do as this is not a standard page. There are a few other items concerning this page that will have to be dealt with, so I will add this feature request to the backlog and close this issue.

An alternative is to use the rest endpoint at the python prompt, client side:
`one.alyx.rest('tasks', session='4ecb5d24-f5cc-402c-be28-9d0f7cb14b3a')`
