### ISSUE TITLE
[Usage question] - How to filter sessions that have a given QC outcome in the extendedQC frame

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#53]
**Describe the question you have**
I would like to retrieve all the session eid that have a the specific QC '_task_goCue_delays' failing.
What is the best approach?

**Comment by GaelleChapuis** [comment]
I think a found a way using Django:
`sess = one.alyx.rest('sessions', 'list', django='extended_qc___task_goCue_delays__lt,0.95')`

However it required at present to know the criterion for failure. It would be best to change it so as to have a string marking the outcome (e.g. 'FAIL').

**Comment by oliche** [comment]
If I understood, @k1o0 philosophy was to label the database with all information necessary to aggregate the session indicator based on the criteria. I don't think this criteria belongs server side.

A first step is to define CRITERIA as a default constant in ibllib, commit 00443a03663dcd6a1168597ac3ba4f282b1e78d3.
Then do:

```
from ibllib.qc.task_metrics import CRITERIA
sess = one.alyx.rest('sessions', 'list', django=f'extended_qc___task_goCue_delays__lt,{CRITERIA["WARNING"]}')
```

We could propose features in ONE2 or in the qc module that wraps this low-level usage.

Closing it for now.
