### ISSUE TITLE
[Bug report] - Python crashing in behavioral rig after stopping criteria

### ISSUE THREAD

**Issue by noamroth** [int-brain-lab/iblenv#55]
After a mouse gets an alert for the stopping criterion (no. 2: mouse is inactive), python stops responding. Sometimes one or two more trials will be run, but at some point, there are no further trials started, and no errors or further messages in the anaconda prompt. Upon pressing "Stop" in pybpod, the stop seems to be sensed, but windows do not close and there is no prompt for poop count, and the window with behavior plots says (not responding). Python needs to be force quit and pybpod needs to be started from the beginning.  This has happened every time we have seen this stopping criterion.

**Comment by nbonacchi** [comment]
Have you tried focusing on the cmd prompt and pressing enter? 
This is a known windows bug, the fact that it happens consistently when hitting criterion 2 is interesting. 
It might be hard/lenghty to reproduce on the test rig though. Mybe it's some interaction with the plotting, but then again why only for painting the plot background yellow and not red or green...
Just thinking with my fingers...
Let me know when it happens again if pressing enter after clicking on the command prompt works

**Comment by k1o0** [comment]
No follow-up in over a month.  Closing for now.
