### ISSUE TITLE
Failed to define the connection JSON using ONE.setup()

### ISSUE THREAD

**Issue by yeebc** [int-brain-lab/iblenv#56]
Follow this document here https://docs.internationalbrainlab.org/en/latest/02_installation_python.html, I have set up the iblenv and successfully import ONE. However when I used ONE.setup() to define the connection JSON file, it showed that 'function' object has no attribute 'setup' (it is my first time to define it).

**Comment by oliche** [comment]
Yes this is a regression. We need to fix the doc, but in the short term you can use this:
```
from oneibl.one import OneAlyx
OneAlyx.setup()
```

**Comment by oliche** [comment]
fixed doc in 8ded571f5134cf9dfaf22ec28d29442bef6d6838
