### ISSUE TITLE
[Bug report] - qcplots.py not compatible with python 3.6

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblenv#57]
My `iblenv` is running on python 3.6 (as per the specifications, which state >= 3.6). However, when running `qcplots.py` (from `ibllib` master) I get

```
Traceback (most recent call last):
  File "/Users/urai/Documents/code/int-brain-lab/ephysCW_qc.py", line 12, in <module>
    plot_results(qc)
  File "/Users/urai/Documents/code/int-brain-lab/ibllib-repo/ibllib/qc/qcplots.py", line 33, in plot_results
    ref = f"{datetime.fromisoformat(det['start_time']).date()}_{det['number']:d}_{det['subject']}"
AttributeError: type object 'datetime.datetime' has no attribute 'fromisoformat'
```

which is caused by the `fromisoformat` being python 3.7 specific. 

If I try to update to python 3.7 in my iblenv, I get tons of package conflicts. Should the `iblenv` have a fixed python version?

**Comment by k1o0** [comment]
Okay I'll look into it

**Comment by k1o0** [comment]
We discussed version this morning and we're leaning towards removing support for 3.6.  What are the conflicts?

**Comment by anne-urai** [comment]
There are many.. I may just re-install the `iblenv` and start from scratch if the env file is updated. Output is too long for github, adding as a file.
[iblenv_conflicts.txt](https://github.com/int-brain-lab/iblenv/files/5291980/iblenv_conflicts.txt)
