### ISSUE TITLE
documentation on behavior of conda-develop

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblenv#6]
Installing the `iblenv` works great, but I've struggled to get an clear overview of the expected behavior of `conda-develop`. Specifically, I have found that different branches/versions of brainbox are available depending on whether I launch python from within the `ibllib-repo` vs another folder, even when `iblenv` is active in all cases.

Googling hasn't resulted in a description of what to expect with `conda-develop` - is there some hidden documentation that could be linked for clarification?

**Comment by oliche** [comment]
The idea of the install here is to clone the IBL repositories and then make them part of your environment using `conda-develop`. Unlike a package installation where the sources are non-editable and in the anaconda env folder, they stay where they are and you can edit them.

The goal is to provide to IBL members:
-  a single environment for our applications
-  the ability to edit sources without having to setup a dev environment

The behaviour you describe may come from an old version of ibllib, possibly in your base environment, that gets shadowed when you are in the repository directory.
`pip list | grep ibllib` should not return anything from any environment.

For reference: https://docs.conda.io/projects/conda-build/en/latest/resources/commands/conda-develop.html
