### ISSUE TITLE
[Usage question] - How to download spikes data from a specific probe via ONE

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#60]
**Describe the question you have**
I want to download the spikes data from one specific probe in a given session.
```
dataset_types = ['spikes.times',
                 'spikes.amps',
                 'spikes.depths']
```
There are 2 loader alternative:

1. `spikes = alf.io.load_object(probe_path, 'spikes')` does not load the data from Flatiron locally.

2. ` _ = one.load(eid, dataset_types, download_only=True)` but it is unclear whether this would download the data for 1 or 2 probes.

I am assuming:
```
    _ = one.load(eid, dataset_types, download_only=True)
    spikes = alf.io.load_object(probe_path, 'spikes')
```
would download the data for all probes there is, and the `alf` command serves loading only the one of interest.

Is there no way around downloading all the probe data per session ?
    
When doing
`spike_times, spike_amps, spike_depths = one.load(eid, dataset_types=dataset_types)`, it is unclear for which probe the data is returned (feature request for ONE2 already mentioned).

**Is your question related to a specific product?**
ONE / alf

**Comment by mayofaulkner** [comment]
Examples below
```
one.load_object(eid, obj='spikes', collection='probe00')

one.load_dataset(eid, dataset='spikes.times', collection='probe01')
```
