### ISSUE TITLE
[Usage question] - Several ephys subject-sessions have < 50 trials

### ISSUE THREAD

**Issue by RylanSchaeffer** [int-brain-lab/iblenv#62]
Run the following code in JupyterHub:

```
sessions = acquisition.Session & 'task_protocol like "%ephys%"'
b = (sessions * subject.Subject * subject.SubjectLab * reference.Lab * behavior.TrialSet.Trial)
# reduce the size of the fetch
b2 = b.proj('institution_short', 'task_protocol', 'session_uuid',
            'trial_stim_contrast_left', 'trial_stim_contrast_right', 'trial_response_choice',
            'task_protocol', 'trial_stim_prob_left', 'trial_feedback_type',
            'trial_response_time', 'trial_stim_on_time')
# construct pandas dataframe
behav = b2.fetch(format='frame').reset_index()

# count number of trials per subject-session
behav.groupby(['subject_uuid', 'session_uuid']).size().hist(bins=50)
```

The histogram shows that quite a few subject-session pairs have less than 200 trials. What's going on with these?

![image](https://user-images.githubusercontent.com/8942987/94851783-c30d0c00-03dd-11eb-81c5-6a473ec42e1b.png)

We can inspect them in more detail

```
grouped = behav.groupby(['subject_uuid', 'session_uuid'])['trial_id'].size()
grouped = grouped.sort_values(ascending=True)
grouped
```

![image](https://user-images.githubusercontent.com/8942987/94852043-2a2ac080-03de-11eb-9434-3f4a311f12e4.png)

Someone suggested that maybe sessions crashed and needed to be restarted, but when I investigated, I found that couldn't explain this.

![image](https://user-images.githubusercontent.com/8942987/94852117-40d11780-03de-11eb-982a-63655be9d4d0.png)

**Comment by shenshan** [comment]
Hi Rylan, I have checked those sessions. `behavior.TrialSet & 'n_trials<50' & (acquisition.Session & 'task_protocol like "%ephys%"')` gives me 9 sessions, and `behavior.TrialSet & 'n_trials<200' & (acquisition.Session & 'task_protocol like "%ephys%"')` gives me 46 sessions. 
I further checked the trial numbers in DJ vs ONE and found that they matched pretty well. So this should be real. 

![image](https://user-images.githubusercontent.com/2539832/94974472-8a476280-04c3-11eb-9ede-54267c2b4f9b.png)
