### ISSUE TITLE
[Bug report] - problem with ONE.setup? 

### ISSUE THREAD

**Issue by nsteinme** [int-brain-lab/iblenv#64]
**Describe the bug**
Tried to use ONE.setup but it didn't work

**To Reproduce**
Installed everything for the first time on this computer, using instructions at this repository. Then, following instructions at https://int-brain-lab.github.io/iblenv/one_docs/one_credentials.html#using-the-one-setup-method:

```
(iblenv) nicksteinmetz@MacBook-Pro-2 int-brain-lab % python
Python 3.7.9 (default, Aug 31 2020, 07:22:35) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from oneibl.one import ONE
>>> ONE.setup()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'function' object has no attribute 'setup'
>>> 
```

**Desktop (please complete the following information):**
 - OS: OSX

**Comment by nsteinme** [comment]
P.s. I did really appreciate that the link above has enough information about what the intended outcome of the setup method is, that I was able to create the appropriate one_params file anyway manually - it worked. thanks for that documentation!

**Comment by rossant** [comment]
If you just do `ONE()`, does it work?
Otherwise, try `ONE().setup()`
The documentation should be fixed accordingly

**Comment by nsteinme** [comment]
Doing ONE() worked (once I deleted the existing .one_params file - when that file was in place, both ONE() and ONE().setup() failed).

**Comment by oliche** [comment]
closing: duplicate #56

**Comment by nsteinme** [comment]
Sorry about that! I think I searched the issues first, guess I missed it.
