### ISSUE TITLE
[Bug report] - Suggestion for documentation

### ISSUE THREAD

**Issue by zashwood** [int-brain-lab/iblenv#65]
This might be obvious, but it might be worth pointing out in the README that, after installing the iblenv environment and cloning the relevant repos, that to call an ibllib function, you actually have to cd into the ibllib-repo repository.  

EDIT: after chatting to Berk, it became clear that I should just have cd'ed into each of the cloned repos and ran` pip install -e .`. Can we add this as a step to the README?

**Comment by oliche** [comment]
Yes we don't rely on the local path of the Python interpreter to run code by installing in dev mode.
So in the README instructions we setup all the repositories in develop mode here:

```
conda env create -f ./iblenv/iblenv.yaml
conda activate iblenv
conda develop ./ibllib-repo
conda develop ./iblapps
conda develop ./analysis
conda develop ./IBL-pipeline
conda develop ./phy
conda develop ./phylib
```

Is your issue related to the fact that you're not using `conda` ? In this case you need to `pip install -e` all packages above.

**Comment by zashwood** [comment]
Hi Olivier, thanks for writing back.  My issue was that, before this code snippet, the text says "If you upgrade or try to fix iblenv:"  so I assumed that I shouldn't run this code as I was just installing iblenv for the first time.  So I think some restructuring of the text would be useful in order to make the instructions clearer.

**Comment by oliche** [comment]
Yes I see your point, I hope there is no more ambiguity now.
Don't hesitate to fix the README.md yourself and make a PR if you see this kind of things again !
