### ISSUE TITLE
[Bug report] - alf.io.load_object(probe_path, 'spikes') ValueError

### ISSUE THREAD

**Issue by mschart** [int-brain-lab/iblenv#68]
**Describe the bug**
When using `spikes = alf.io.load_object(probe_path, 'spikes')` there's a ValueError for one probe but not the other probe.

**To Reproduce**

```
    eid = '83e77b4b-dfa0-4af9-968b-7ea0c7a0c7e4'
    probe = 'probe01'
    dataset_types = ['spikes.times', 'spikes.depths','spikes.clusters', 'trials.intervals', 'trials.stimOn_times','trials.feedback_times']   
    
    D = one.load(eid, dataset_types = dataset_types, dclass_output=True)
    alf_path = Path(D.local_path[0]).parent.parent / 'alf'  
    probe_path = alf_path / probe

    spikes = alf.io.load_object(probe_path, 'spikes')
```

---> 44     spikes = alf.io.load_object(probe_path, 'spikes')
     45 
     46     trials = alf.io.load_object(alf_path, '_ibl_trials')

~/anaconda3/lib/python3.7/site-packages/alf/io.py in load_object(alfpath, object, glob, short_keys)
    264         if meta_data_file == fil:
    265             continue
--> 266         OUT[att] = load_file_content(fil)
    267         if meta_data_file:
    268             meta = load_file_content(meta_data_file)

~/anaconda3/lib/python3.7/site-packages/alf/io.py in load_file_content(fil)
    165         return
    166     if fil.suffix == '.npy':
--> 167         return np.load(file=fil)
    168     if fil.suffix == '.json':
    169         try:

~/anaconda3/lib/python3.7/site-packages/numpy/lib/npyio.py in load(file, mmap_mode, allow_pickle, fix_imports, encoding)
    438             else:
    439                 return format.read_array(fid, allow_pickle=allow_pickle,
--> 440                                          pickle_kwargs=pickle_kwargs)
    441         else:
    442             # Try a pickle

~/anaconda3/lib/python3.7/site-packages/numpy/lib/format.py in read_array(fp, allow_pickle, pickle_kwargs)
    769             array = array.transpose()
    770         else:
--> 771             array.shape = shape
    772 
    773     return array

ValueError: cannot reshape array of size 3670000 into shape (5753339,)

**Comment by mayofaulkner** [comment]
I ran this on my computer for both probe00 and probe01 and don't have any problems. It looks like you are using a pip installed version of ibllib (~/anaconda3/lib/python3.7/site-packages/alf/io.py in load_object(alfpath, object, glob, short_keys). Could you try `pip uninstall ibllib` and then follow the `conda develop ibllib-repo` steps in this document https://github.com/int-brain-lab/iblenv.

**Comment by k1o0** [comment]
Also I noticed in the error stack that you're searching for `_ibl_trials` as an object.  You should instead search as `trials` and can optionally add a `namespace='ibl'` argument (otherwise the namespace is ignored in the searched).  For the next version I'll add the following message if no ALF object is found: `The ALF object was not found.  This may occur if the object or namespace or incorrectly formatted e.g. the object "_ibl_trials.intervals.npy" would be found with the filters object="trials", namespace="ibl"`.

**Comment by k1o0** [comment]
No follow-up in over a month.  Closing for now.
