### ISSUE TITLE
Error on Mac 10.12 when running Ephys Alignment GUI - seems related to cv2?

### ISSUE THREAD

**Issue by jeanpaulnc** [int-brain-lab/iblenv#7]
(iblenv) Jean-Pauls-MacBook-Pro:~ jean-paulnoel$ python Documents/int-brain-lab/iblapps/atlaselectrophysiology/ephys_atlas_gui.py
Traceback (most recent call last):
 File “Documents/int-brain-lab/iblapps/atlaselectrophysiology/ephys_atlas_gui.py”, line 5, in <module>
  from atlaselectrophysiology.load_data import LoadData
 File “/Users/jean-paulnoel/Documents/int-brain-lab/iblapps/atlaselectrophysiology/load_data.py”, line 4, in <module>
  import ibllib.pipes.histology as histology
 File “/Users/jean-paulnoel/Documents/int-brain-lab/ibllib-repo/ibllib/pipes/histology.py”, line 11, in <module>
  from ibllib.ephys.spikes import probes_description as extract_probes
 File “/Users/jean-paulnoel/Documents/int-brain-lab/ibllib-repo/ibllib/ephys/spikes.py”, line 9, in <module>
  from ibllib.ephys.sync_probes import apply_sync
 File “/Users/jean-paulnoel/Documents/int-brain-lab/ibllib-repo/ibllib/ephys/sync_probes.py”, line 12, in <module>
  from ibllib.io.extractors.ephys_fpga import _get_sync_fronts, get_ibl_sync_map
 File “/Users/jean-paulnoel/Documents/int-brain-lab/ibllib-repo/ibllib/io/extractors/__init__.py”, line 1, in <module>
  from ibllib.io.extractors import (biased_trials, biased_wheel, ephys_fpga,
 File “/Users/jean-paulnoel/Documents/int-brain-lab/ibllib-repo/ibllib/io/extractors/biased_trials.py”, line 5, in <module>
  from ibllib.io.extractors.training_trials import ( # noqa; noqa
 File “/Users/jean-paulnoel/Documents/int-brain-lab/ibllib-repo/ibllib/io/extractors/training_trials.py”, line 2, in <module>
  import cv2
 File “/Users/jean-paulnoel/anaconda3/envs/iblenv/lib/python3.7/site-packages/cv2/__init__.py”, line 5, in <module>
  from .cv2 import *
ImportError: dlopen(/Users/jean-paulnoel/anaconda3/envs/iblenv/lib/python3.7/site-packages/cv2/cv2.cpython-37m-darwin.so, 2): Symbol not found: _inflateValidate
 Referenced from: /Users/jean-paulnoel/anaconda3/envs/iblenv/lib/python3.7/site-packages/cv2/.dylibs/libpng16.16.dylib (which was built for Mac OS X 10.13)
 Expected in: /usr/lib/libz.1.dylib
 in /Users/jean-paulnoel/anaconda3/envs/iblenv/lib/python3.7/site-packages/cv2/.dylibs/libpng16.16.dylib

**Comment by mayofaulkner** [comment]
Fixed by installing opencv with conda rather than pip

pip uninstall opencv-python
conda install -c conda-forge opencv

**Comment by oliche** [comment]
@GaelleChapuis had the same symptom and it was fixed by doing exactly the opposite: installing with pip rather than conda.
I guess the rule so far is: whatever opencv was installed with, uninstall and install again using the other one...
