### ISSUE TITLE
Waiting for Camera Pulses

### ISSUE THREAD

**Issue by qas203** [int-brain-lab/iblenv#70]
We're setting up a new computer and we got everything calibrated. I'm trying to test the habituationChoice_world protocol, but it won't start any trials. The protocol will run smoothly, the the second screen turns gray and the anaconda prompt says it's starting the first protocol then says "waiting for camera pulses" and it gets stuck there. No grating shows up on the screen. No tone is played. No new trials are started. The task does not end, and no error message is displayed. When I open flyCap it shows an image from the camera and the light on the camera is green, so I don't think the camera is the issue.

**Desktop:**
 - OS: [Windows 10]
 - Browser [we access alyx through chrome]
 - Version [iblrig 6.4.2]

**Comment by GaelleChapuis** [comment]
The error message "Waiting for the camera pulses" means the Bonsai workflow and Bpod cannot detect the camera TTL input.
Could you check the cabling of your camera onto Bpod ? Have you checked the camera indeed sends out TTL pulses via an oscilloscope?

**Comment by qas203** [comment]
I have not done that yet, but I recalibrated the frame2TTL and now the trials run, the stimulus appears, and the go tone plays

**Comment by GaelleChapuis** [comment]
Great, it seems your setup is then working, I'll close this issue.
