### ISSUE TITLE
[Usage question] - How to access up-to-date movement onset time

### ISSUE THREAD

**Issue by berkgercek** [int-brain-lab/iblenv#71]
**Describe the question you have**
What is the best way to get movement onset times? Recent presentations by @k1o0 and Naoki Hiratani have referenced movement onset times during trials. Where can these be found as recently computed?

**Is your question related to a specific product?**
Datajoint or ONE

**Comment by k1o0** [comment]
A Jupyter Notebook on wheel analysis is available [here](https://github.com/int-brain-lab/ibllib/blob/master/brainbox/examples/wheel_moves.ipynb).  To access movement onset times in ONE, run `one.load_object(eid, 'wheelMoves')`.  In DJ:
```
dj_wheel = dj.create_virtual_module('wheel_moves', 'group_shared_wheel')
dj_wheel.WheelMoveSet.Move.describe();
```

**Comment by berkgercek** [comment]
Thanks, that's what I was looking for!
