### ISSUE TITLE
[Usage question] - How to find a recording with channels in a specific brain region?

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#72]
**Describe the question you have**
I know how to get the brain regions from a given recording, but I do not know how to do the other way around: Find a recording which has channels in a given brain region.

Do we have an example for this?
Thank you in advance !

**Is your question related to a specific product?**
ONE / Datajoint

**Comment by mayofaulkner** [comment]
See line 14 of these example one queries
https://github.com/int-brain-lab/ibllib/blob/master/examples/one/one_queries.py#L14

**Comment by GaelleChapuis** [comment]
Perfect - Thanks!

**Comment by GaelleChapuis** [comment]
Oops sorry. Had already asked. https://github.com/int-brain-lab/iblenv/issues/2
