### ISSUE TITLE
Superstar Ephys Mouse Has No Cluster Data in DataJoint?

### ISSUE THREAD

**Issue by RylanSchaeffer** [int-brain-lab/iblenv#73]
In my [Jupyter Notebook](https://jupyter.internationalbrainlab.org/user/rylanschaeffer/notebooks/public/Queries%20and%20Plotting/2020-07-01-Rylan-Mouse-Behavior-and-Ephys-Playground.ipynb), I found a little superstar mouse on the ephys track:

![image](https://user-images.githubusercontent.com/8942987/95503254-f7de0d80-095f-11eb-83e1-64cc88ea7bc6.png)

But when I query for this subject's clusters in DataJoint, I find nothing

![image](https://user-images.githubusercontent.com/8942987/95503314-0d533780-0960-11eb-84cc-99af4bf293ff.png)

Why does this mouse have no cluster data?

**Comment by RylanSchaeffer** [comment]
Subject: 05e97eea-64e2-4e52-a78a-5b78875b4fa3

**Comment by berkgercek** [comment]
If I'm reading your code right, you're filtering on over 7500 trials? 7500 trials is an insane number, and my guess is an artifact or some kind of data error. 

Most mice barely ever reach 1000 trials, as seen in an earlier plot in your notebook. I'd highly recommend against trying to analyze dataset which present great extrema in any summary measure like # of trials.

**Comment by RylanSchaeffer** [comment]
Each dot is a mouse

![image](https://user-images.githubusercontent.com/8942987/95522665-89aa4280-0981-11eb-9bda-82cc6a9a8ae6.png)

**Comment by RylanSchaeffer** [comment]
The problem in my post exists for both the mouse in the top right quadrant as well as the mouse at the top right of the top left quadrant

**Comment by berkgercek** [comment]
Again, I'm a bit concerned because this plot you just posted directly contradicts this plot:

![image](https://user-images.githubusercontent.com/17750267/95522792-5c838180-09cd-11eb-9666-6a7dae94732a.png)

and also everything I know about the task and mouse behavior within, which is that >8000 trials absolutely is not normal

**Comment by RylanSchaeffer** [comment]
^that plot is trials per subject-session. The plot above is total trials per subject, summed across sessions.

**Comment by RylanSchaeffer** [comment]
To run the analyses I have in mind, I think we need a *lot* of trials. The RNN phase portraits only become clear when looking at >100 blocks, and I'm expecting mouse data will be much noisier

**Comment by berkgercek** [comment]
Ah I see what you're saying.

But even then, I'd like to reiterate that on a dataset that is still very much a work in progress it's not a good idea to prototype analyses on extrema subjects that have a metric that is ~2-3x higher than every other subject in the dataset. I'd go for the mice that have 4000 total trials in ephys instead.

**Comment by RylanSchaeffer** [comment]
I guess I don't understand - what's the risk of prototyping with the best performing mouse?

**Comment by berkgercek** [comment]
Also if you really, really want to access the spike data for that animal, try ONE too, to make sure it's a problem both on DJ and on the master database

**Comment by berkgercek** [comment]
> I guess I don't understand - what's the risk of prototyping with the best performing mouse?

Because that mouse is doing twice as many trials as about 100 other mice, which means something is very different about that mouse. In a dataset which relies on replicability between animals as closely as possible, this is not a good thing.

**Comment by RylanSchaeffer** [comment]
Ok point well taken.

**Comment by GaelleChapuis** [comment]
Hi Rylan,
It's possible the data you're looking into may not yet be extracted.
You can visually check the status of data extraction on Alyx : https://alyx.internationalbrainlab.org/admin-tasks/status/EphysExtractionPipeline/danlab
(Change the last lab name in the link according to the subject/lab you want to look into)
Also, please check you are filtering by the correct project code, otherwise you'll end up using data from personal projects (for which you'd need to ask author permission).

**Comment by RylanSchaeffer** [comment]
Anytime I try to access Alyx, I get the error `The connection has timed out. The server at alyx.internationalbrainlab.org is taking too long to respond.`

**Comment by RylanSchaeffer** [comment]
![image](https://user-images.githubusercontent.com/8942987/95535061-4b6e4c80-099c-11eb-919d-20da4937b868.png)

**Comment by GaelleChapuis** [comment]
It's surely because you are not on a registered network. You have to vpn into your institution, or ask one of the SW dev to add your institution IP to the list.

**Comment by shenshan** [comment]
The three sessions now have data in the tables ephys.DefaultCluster and ephys.AlignedTrialSpikes. The data for probe right in the last session was missing from FlatIron.

**Comment by anne-urai** [comment]
To re-iterate what @berkgercek said: I wouldn't start by summing all trials from a mouse across sessions and then finding clusters. In each session, the mouse will have probes somewhere else in the brain, with different neurons; so whenever you want to link neural activity to behavior, this has to happen at the session level.

**Comment by RylanSchaeffer** [comment]
@anne-urai , the point of summing all trials from a mouse across sessions is to see which mice we have the most data for. I won't be combining probe data from different sessions.
