### ISSUE TITLE
[Bug report] - DLC data on flatiron but not accessible via one

### ISSUE THREAD

**Issue by mschart** [int-brain-lab/iblenv#74]
**Describe the bug**
DLC data is on flatiron:

http://ibl.flatironinstitute.org/cortexlab/Subjects/KS023/2019-12-10/001/alf/

But not included in:

a = one.list('aad23144-0e52-4eac-80c5-c4ee2decb198','dataset-types')

**Comment by oliche** [comment]
Fixed by commit on Alyx 5f4e170204a20b5e9dead6d83ecefa1fff39027d
