### ISSUE TITLE
[Usage question] - Are Camera.timestamps aligned to behavior?

### ISSUE THREAD

**Issue by ineslaranjeira** [int-brain-lab/iblenv#77]
Are _iblrig_Camera.timestamps  aligned to bPod time?

**Comment by k1o0** [comment]
I believe they are in Bpod time (but not necessarily aligned to behaviour).  Instead, use the `camera.times` dataset type, which is an npy file instead of an ssv file.  Note though that even these times are slightly misaligned.

Don't forget to close if this answers your question
