### ISSUE TITLE
Request: be able to use task_protocol with one.alyx.rest('trajectories', ...)

### ISSUE THREAD

**Issue by guidomeijer** [int-brain-lab/iblenv#8]
It would be nice to be able to select only a particular task protocol (e.g. ephysChoiceWorld) when querying trajectories using one.alyx.rest.

**Comment by oliche** [comment]
So I designed generic filters to avoid having to write code each time I had this kind of request. It uses Django syntax for queries, which I find quite compact. In this case you're looking at the related table `session` field `task_protocol` and doing and insensitive contain match:

`one.alyx.rest('insertions', 'list', django='session__task_protocol__icontains,choiceworld')`

I've added it to the examples as well.

**Comment by guidomeijer** [comment]
Thanks! But this does not seem to work with `trajectories` as endpoint instead of `insertions`

**Comment by oliche** [comment]
`one.alyx.rest('trajectories', 'list', django='probe_insertion__session__task_protocol__icontains,choiceworld')`
