### ISSUE TITLE
[Usage question] - How to get eids of session that do not contain specific dataset type(s)

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#83]
**Describe the question you have**

Let's take those example dataset types:
```
ds_types = ['spikes.times', 'spikes.amps', 'spikes.depths']
```

`one.search(dataset_types=ds_types)` can be used to search for session that contain those datasets.

I would like to do the opposite, i.e. find the sessions that do **not** contain those datasets.
Something like `one.search(dataset_types!=ds_types)` (which obviously won't work as written).

What is the recommended way ?

**Is your question related to a specific product?**
ONE

**Additional context**
The workaround I thought of at first was to 
1. Get all sessions eids ( but see https://github.com/int-brain-lab/iblenv/issues/82 ) - `all_eids`
2. Get the subset of session eids with the dataset types using one.search() the classical way - `ds_in_eids`
3. Filter out all the sessions so as to get only those without the dataset types (example Matlab scripting:  `all_eids(~ismember(all_eids, ds_in_eids)` ).

But it does not seem efficient.

**Comment by k1o0** [comment]
See the documentation: [ONE query examples](https://github.com/int-brain-lab/ibllib/blob/master/examples/one/one_queries.py#L23-L25)
