### ISSUE TITLE
[Feature request] - Speed up brainbox.io.one.load_spike_sorting_with_channel

### ISSUE THREAD

**Issue by berkgercek** [int-brain-lab/iblenv#84]
**Is your feature request related to a problem? Please describe.**
I'm currently fitting GLMs to all of the brainwide map data to date with ephys-aligned histology. I use the `load_spike_sorting_with_channel` function [here, in brainbox](https://github.com/int-brain-lab/ibllib/blob/master/brainbox/io/one.py) to get spike times, clusters, and brain regions. This function currently is the single most time-consuming part of my analysis, and I'd like to see if it could be accelerated somehow.

**Describe the solution you'd like**
I'd like to get a speedup within `bbone.load_spike_sorting_with_channels`. I notice that within the function it is using a general call to the alyx REST API:

```
Line 47 :        ses = one.alyx.rest('sessions', 'read', id=eid)
```
which likely loads in the entire session data. This could probably be improved to target only channel location information.

Thanks!
Berk

**Comment by mayofaulkner** [comment]
https://github.com/int-brain-lab/ibllib/pull/235 has now been merged to develop and improvements can be found on develop branch. On my computer with data already downloaded it sped up from 20s to 5s. 

I will close this issue but feel free to reopen if further improvements are needed
