### ISSUE TITLE
[Usage question] - How to retrieve the job task outcome from Alyx via ONE

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#89]
**Describe the question you have**
I would like to know which sessions have a given job task at a given status, e.g. which session have
"SPIKESORTING_KS2_MATLAB" as "Errored"
or
"DLC" as **not** "Complete"

I can look through the web interface:
https://alyx.internationalbrainlab.org/admin-tasks/status/EphysExtractionPipeline?page=1

But would like to do it programmatically so as to count how much backlog we have.
How can I access this info via ONE ?

**Is your question related to a specific product?**
Alyx, ONE

**Additional context**
https://alyx.internationalbrainlab.org/admin-tasks/status/EphysExtractionPipeline?page=1

**Comment by GaelleChapuis** [comment]
I could alternatively do it on the Alyx page itself by adding a line to the code in alyx > jobs > views https://github.com/cortex-lab/alyx/blob/02c047169f5f7c04df9309629049268aabd5ba0e/alyx/jobs/views.py#L26 : 
```
        cerr = Count('session__tasks', filter=Q(session__tasks__status=40))

        context['labs'] = Lab.objects.annotate(
            count_error=cerr,
            count_waiting=cw, last_session=ls, last_job=lj).order_by('name')
```
But I'd need someone (@rossant ?) to walk me through whether this change would be sufficient (not sure how to test this sorry).

**Comment by k1o0** [comment]
There should be no need to add this to Alyx, it can all be done via rest queries:
```
from oneibl.one import ONE
one = ONE()
errored = one.alyx.rest('tasks', 'list', status='Errored', lab='angelakilab', name='SpikeSorting_KS2_Matlab')
incomplete = one.alyx.rest('tasks', 'list', lab='angelakilab', name='EphysDLC', django='~status__contains,Complete')
```

Please close this issue if this answers your question

**Comment by nbonacchi** [comment]
You can do:

```
from oneibl.one import ONE

one = ONE()
tasks = one.alyx.rest('tasks', 'list')  # this will get everything atm 33170 tasks
errored_tasks = one.alyx.rest('tasks', 'list', status='Errored')
```
you can further, filter by lab and task name by using the keywords: `lab='somelab', name='EphysTrials'`
and of course you can use the django query to get all but some status by using something like `django='~status__contains,Errored'`


You get something like this for all the tasks:
```
{'id': 'c5e58d29-72e7-4210-ab10-341f7aafd98d',
 'parents': [],
 'session': '9629b04d-f904-439a-9987-b9aa46f59c7e',
 'status': 'Complete',
 'name': 'TrainingRegisterRaw',
 'priority': 100,
 'io_charge': 5,
 'level': 0,
 'gpu': 0,
 'cpu': 1,
 'ram': 4,
 'time_out_secs': None,
 'time_elapsed_secs': 0.444675922393799,
 'executable': 'ibllib.pipes.training_preprocessing.TrainingRegisterRaw',
 'graph': 'TrainingExtractionPipeline',
 'log': "2020-10-28 17:39:57,762,762 INFO     [tasks.py:68] Starting job <class 'ibllib.pipes.training_preprocessing.TrainingRegisterRaw'>\n2020-10-28 17:39:58,207,207 INFO     [tasks.py:74] Job <class 'ibllib.pipes.training_preprocessing.TrainingRegisterRaw'> complete\n2020-10-28 17:39:58,207,207 INFO     [tasks.py:87] N outputs: 0\n2020-10-28 17:39:58,207,207 INFO     [tasks.py:88] --- 0.44467592239379883 seconds run-time ---",
 'version': '1.5.19',
 'datetime': '2020-10-28T17:39:58.238031'}
```

**Comment by nbonacchi** [comment]
I guess @k1o0 beat me to it :open_mouth:

**Comment by GaelleChapuis** [comment]
Thanks, perfect !
