### ISSUE TITLE
Bug in query of sessions with an atlas acronym using Alyx REST

### ISSUE THREAD

**Issue by guidomeijer** [int-brain-lab/iblenv#9]
Querying a brain region that is at the lowest level of the hierarchy returns an empty list.

Examples:
`one.alyx.rest('sessions', 'list', atlas_acronym="CA")` works but `one.alyx.rest('sessions', 'list', atlas_acronym="CA1")` does not
`one.alyx.rest('sessions', 'list', atlas_acronym="VIS")` works but `one.alyx.rest('sessions', 'list', atlas_acronym="VISp2/3")` does not
`one.alyx.rest('sessions', 'list', atlas_acronym="MBmot")` works but `one.alyx.rest('sessions', 'list', atlas_acronym="SNr")` does not

**Comment by oliche** [comment]
Fixed in Alyx-dev and updated the prod database
