### ISSUE TITLE
_ibl_rightCamera.times.npy is empty 

### ISSUE THREAD

**Issue by mschart** [int-brain-lab/iblenv#91]
http://ibl.flatironinstitute.org/zadorlab/Subjects/CSH_ZAD_024/2020-06-08/001/alf/

There's DLC and camera times for the left cam but for the body and right cam the file 
`_ibl_rightCamera.times.npy` is empty (see file size 128). Is it still uploading maybe later or did something go wrong?

![image](https://user-images.githubusercontent.com/17218515/97711710-573dc200-1ab5-11eb-8985-a81772cb3abd.png)

 
Same here:
http://ibl.flatironinstitute.org/zadorlab/Subjects/CSH_ZAD_017/2020-06-05/001/alf/
FlatIron/zadorlab/Subjects/CSH_ZAD_022/2020-05-28/001/alf

**Comment by nbonacchi** [comment]
@mschart most probably this rig or session did not save the TS for the cameras, they are probably not well configured?
@k1o0 this should be a QC for the rigs to know if their cams are configured properly, the size of an empty np.array is apparently 128 bytes (for the comparison)

**Comment by k1o0** [comment]
Yes this would certainly be picked up by the camera QC.  Ideally we would remove these empty files when we have a compute node...

**Comment by GaelleChapuis** [comment]
Seems related to https://github.com/int-brain-lab/iblenv/issues/76
