### ISSUE TITLE
[Bug report] - spikes.amps missing

### ISSUE THREAD

**Issue by noamroth** [int-brain-lab/iblenv#92]
I've found many datasets where spikes contains clusters and times, but not amps. 

One example session: 
subject='ibl_witten_14', date=['2019-12-11'], probe = 'probe00'

I am using the following code to load spikes:                
spk, clus, chn = load_spike_sorting_with_channel(eid, one=one)

Is there a different way to load amplitudes, or is this a pipeline issue? 

Thanks!

**Comment by mayofaulkner** [comment]
By default `load_spike_sorting_with_channel` only loads the following datasets
```
[‘clusters.channels’, ‘clusters.depths’, ‘clusters.metrics’, ‘spikes.clusters’, ‘spikes.times’]
```
To also load in `spikes.amps` you can add in an extra argument `dataset_types = ['spikes.amps`]

See example 3 of this example in the docs https://int-brain-lab.github.io/iblenv/notebooks_external/docs_load_spike_sorting.html

**Comment by noamroth** [comment]
Great thank you!
