### ISSUE TITLE
[Usage question] - Are qc status propagated from `session__extended_qc__experimenter` to `session__qc` ?

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#93]
**Describe the question you have**
Are qc status propagated from `session__extended_qc__experimenter` to `session__qc` ?

It looks like it from the example below but I'd like someone to confirm.

This query:
`sess_expcrit = one.alyx.rest('sessions', 'list', django='extended_qc__experimenter,CRITICAL')`
returns 1 session:
```
[{'subject': 'CSH_ZAD_029',
  'start_time': '2020-09-10T12:30:39',
  'number': 1,
  'lab': 'zadorlab',
  'project': 'ibl_neuropixel_brainwide_01',
  'url': 'https://alyx.internationalbrainlab.org/sessions/000c057b-fe85-41a7-9c3c-645dce09c1fb',
  'task_protocol': '_iblrig_tasks_ephysChoiceWorld6.4.2'}]
```

Whilst this query returns 20 sessions:
`sess_crit = one.alyx.rest('sessions', 'list', django='qc,50')`
including the one above.

[I assume it is normal this query returns more as we only recently changed the user input to go into `session__extended_qc__experimenter` and not `session__qc` directly]

**Is your question related to a specific product?**
Alyx, QC pipeline

**Comment by GaelleChapuis** [comment]
Sub-question:

Where to look to find how the `session_qc` field value is defined ?
It could be for example a mixture of `session__extended_qc__experimenter` and `session__extended_qc__task`.

I looked into the class definition but no help there.

```
class Session(BaseAction):
    """
    A recording or training session performed on a subject. There is normally only one of
    these per day, for example corresponding to a  period of uninterrupted head fixation.

    Note that you can organize sessions hierarchically by assigning a parent_session.
    Sub-sessions could for example corresponding to periods of time in which the same
    neurons were recorded, or a particular set of stimuli were presented. Top-level sessions
    should have parent_session set to null.

    If the fields (e.g. users) of a subsession are null, they should inherited from the parent.
    """
    parent_session = models.ForeignKey('Session', null=True, blank=True,
                                       on_delete=models.SET_NULL,
                                       help_text="Hierarchical parent to this session")
    project = models.ForeignKey('subjects.Project', null=True, blank=True,
                                on_delete=models.SET_NULL, verbose_name='Session Project')
    type = models.CharField(max_length=255, null=True, blank=True,
                            help_text="User-defined session type (e.g. Base, Experiment)")
    number = models.IntegerField(null=True, blank=True,
                                 help_text="Optional session number for this level")
    task_protocol = models.CharField(max_length=1023, blank=True, default='')
    n_trials = models.IntegerField(blank=True, null=True)
    n_correct_trials = models.IntegerField(blank=True, null=True)

    QC_CHOICES = [
        (50, 'CRITICAL',),
        (40, 'ERROR',),
        (30, 'WARNING',),
        (20, 'NOT_SET',),
        (10, 'PASS',),
    ]

    qc = models.IntegerField(default=20, choices=QC_CHOICES)
    extended_qc = JSONField(null=True, blank=True,
                            help_text="Structured data about session QC,"
                                      "formatted in a user-defined way")
```

**Comment by GaelleChapuis** [comment]
And another quick question on this -- I cannot write
`one.alyx.rest('sessions', 'list', django='qc,CRITICAL')`
because the value for CRITICAL is actually 50 for `session_qc` - so I have to write instead:
`one.alyx.rest('sessions', 'list', django='qc,50')`

I understand why the numerical implementation (to do `lt` for filtering etc).

Why do we have this discrepancy with the `session__extended_qc__experimenter` nomenclature?
(it does not matter eventually, just wondering)

**Comment by k1o0** [comment]
> Are qc status propagated from `session__extended_qc__experimenter` to `session__qc` ?
Yes if the experimenter updated the QC via ibllib.

**Comment by k1o0** [comment]
> Why do we have this discrepancy with the `session__extended_qc__experimenter` nomenclature?

Because Alyx will automatically map the code to the string so users will be able to read the qc field.  This doesn't happen with the JSON field, so I opted to keep the JSON field human readable.

If you want to check for a field I think you can use the `isnull` query: `django='extended_qc__blah__isnull,true'`
