### ISSUE TITLE
[Usage question] - How can I retrieve the session info given a specific session eid ?

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#96]
**Describe the question you have**
I am looking to get the session info for a specific session eid; I am doing this:
`sess_eid = '17231390-9b95-4ec6-806d-b3aae8af76ac'`
`sess_info = one.alyx.rest('sessions', 'list', eid = sess_eid)`
However
`len(sess_info) = 26627`
(not = 1)

How can I retrieve the session info given a specific session eid ?

**Is your question related to a specific product?**
Alyx, ONE

**Comment by GaelleChapuis** [comment]
```
sess_info_django = one.alyx.rest('sessions', 'list',
                                 django=f'id,{sess_eid}')
```
Managed via a Django query.

**Comment by nbonacchi** [comment]
The rest command is: 
`dets = self.alyx.rest("sessions", "read", eid)`
I made a convenience function that gets the details
one.get_details(eid, full=False) will return the details as the one_search method does
one.get_details(eid, full=True) will return the full details of the session
